TravelMapping/HighwayData

- hwy_data/MA/usai/ma.i091.wpt
Writing and testing out the new fork and pull instructions for those who wish to contribute to the highway data.  Also, fixed a broken concurrency, so that's good!
> Added shaping point to MA I-91 to match MA 2 along their concurrency.

- hwy_data/BC/cantch/bc.tchbuscha.wpt
- hwy_data/BC/cantch/bc.tchmai.wpt
- hwy_data/_systems/cantch.csv
- hwy_data/_systems/cantch_con.csv
Adding business loop to Chase BC from TCH 1 (Main)
Updates line:
15-08-13;(Canada) British Columbia;TCH 1 Business (Chase BC); bc.tchbuscha;New route
> Tch 1 business in chase bc 28

- hwy_data/MD/usai/md.i095.wpt
- hwy_data/MD/usamd/md.md200.wpt
Extended MD 200 by two exits, and also added exit 32 for I-95 which was built in the same project. Only the MD 200 change is Update-worthy,
Update text:
15-08-17;(USA) Maryland;MD 200;md.md200;Extended east end of route from
I-95 to US1
> MD 200 .(and related MD I-95) changes

- hwy_data/BC/cantch/bc.tchbuscha.wpt
- hwy_data/MD/usaus/md.us001.wpt
Cleanup on previous pull requests: added missing MD 200 point to MD US1; resubmitting BC TCHBusCha, which is in updates list but not master database.
> Md us1 bc tch business

- hwy_data/KS/usaks/ks.ks010.wpt
- hwy_data/KS/usaks/ks.ks170.wpt
- hwy_data/KS/usaks/ks.ks278.wpt
- hwy_data/KS/usaus/ks.us040.wpt
- hwy_data/KS/usaus/ks.us059.wpt
- hwy_data/KS/usausb/ks.us183byphay.wpt
15-08-19;(USA) Kansas;US 183 Bypass (Hays);ks.us183byphay;Truncated north end from I-70 Exit 159 (US 183) to I-70 Exit 157.
15-08-19;(USA) Kansas;KS 278;ks.ks278;Truncated west end from KS 170 to Fairlawn Rd.
15-08-19;(USA) Kansas;US 40;ks.us040;Reverted November 2013 changes that are still not signed: Removed from KS 10 and US 59, and relocated back onto 6th Street.
> Kansas 2015-08-19

- hwy_data/WI/usaus/wi.us041.wpt
Fixes new US 41 file, to remove alternate labels accidentally carried over from US 45 file.
No Updates entry required.
> Fixes minor errors in new WI US 41 file

- hwy_data/TX/usai/tx.i069erob.wpt
- hwy_data/TX/usansf/tx.lp375.wpt
Minor label corrections. No update text necessary.
> TX label fixes

- hwy_data/ND/usand/nd.nd200.wpt
- hwy_data/ND/usaus/nd.us085.wpt
- hwy_data/ND/usausb/nd.us085busale.wpt
- hwy_data/_systems/usausb.csv
- hwy_data/_systems/usausb_con.csv
- updates.csv
Can't automatically merge.
I think because: I made a commit to updates.csv on the 15th, then waited for my previous pull request to be merged to avoid wacky hijinks. Then Si made another commit to updates.csv (on the 16th?), which was merged. My new commit today incorporates the changes he made, so things should be OK...
But let's look this one over, shall we?
15-09-20;(USA) North Dakota;US 85;nd.us085;Removed from US 85 Business and relocated onto the western Alexander bypass.
15-09-20;(USA) North Dakota;US 85 Business (Alexander);nd.us085busale;Added route.
15-09-20;(USA) North Dakota;ND 200;nd.nd200.wpt;Removed from US 85 Business and relocated onto the western Alexander bypass.
> Alexander ND bypass

- hwy_data/PA/usapa/pa.pa065trkmck.wpt
- hwy_data/PA/usapa/pa.pa351.wpt
http://clinched.s2.bizhat.com/viewtopic.php?t=2256&mforum=clinched (re-sync PA65TrkMcK with PA51)
http://clinched.s2.bizhat.com/viewtopic.php?t=2373&mforum=clinched (added in missing connection for PA-351 to I-76/I-376 interchange)
Changes don't require any mentions for the update page.
> PA: Some minor PA fixes

- hwy_data/NH/usanh/nh.nh107.wpt
- hwy_data/NH/usanh/nh.nh121a.wpt
A couple point additions in Rockingham county. The most minor of updates. Nothing newsworthy.
> Rockingham NH

- hwy_data/ND/usaus/nd.us085.wpt
- hwy_data/ND/usausb/nd.us085buswat.wpt
Old US85 points added as discussed in #127
> Watford City ND bypass

- hwy_data/PA/usapa/pa.pa115.wpt
- hwy_data/PA/usapa/pa.pa534.wpt
- hwy_data/PA/usapa/pa.pa903.wpt
- hwy_data/PA/usausb/pa.us209trkbro.wpt
- hwy_data/_systems/usausb.csv
- hwy_data/_systems/usausb_con.csv
http://clinched.s2.bizhat.com/viewtopic.php?t=2015&mforum=clinched
Update log info:
15-10-26;(USA) Pennsylvania;US 209 Truck (Brodheadsville);pa.us209trkbro;Added route.
> PA: US-209 Truck (Brodheadsville, PA)

- hwy_data/BC/cansph/bc.bc097low.wpt
> Typo fix for in-dev BC BC97Low

- hwy_data/QC/canqca/qc.a410.wpt
Update entry:
15-10-30;(Canada) Quebec;A-410;qc.a410;Extended route east, to QC 108/143 (exit 13)
> QC A-410 extended east by one exit

- hwy_data/WI/usausb/wi.us053bussol.wpt
- hwy_data/_systems/usaca_con.csv
Replaces erroneous route file for WI US 53 Bus (Solon Springs) with copy from CHM database.
> Responds to issue #188

- hwy_data/WI/usausb/wi.us053bussol.wpt
- hwy_data/_systems/usaca_con.csv
Reverts TravelMapping/HighwayData#189
> Revert "Responds to issue #188"

- hwy_data/WV/usawv/wv.wv017.wpt
- hwy_data/WV/usawv/wv.wv085.wpt
http://www.aaroads.com/forum/index.php?topic=15733.msg2104280#msg2104280
2015-11-07;(USA) West Virginia;WV 85;wv.wv085;Extended north from WV 17 up to US 119.
> WV: Correcting WV-85's northern end

- hwy_data/ON/canonf/on.on401.wpt
Added newly opened Exit #180 for Wonderland Road.
No need for a mention on the update page about this.
> ON: New Exit #180 for ON-401.

- hwy_data/DC/usanp/dc.beadr.wpt
- hwy_data/MD/usanp/md.beadr.wpt
- hwy_data/MD/usasf/md.cabjohnpkwy.wpt
- hwy_data/UT/usanp/ut.kolcynrd.wpt
- hwy_data/UT/usanp/ut.kolterrd.wpt
- hwy_data/UT/usanp/ut.zioncyndr.wpt
- hwy_data/VA/usanp/va.sporunpkwy.wpt
- hwy_data/_systems/usanp.csv
- hwy_data/_systems/usanp_con.csv
- hwy_data/_systems/usasf.csv
- hwy_data/_systems/usasf_con.csv
2015-11-16;(USA) Maryland;Cabin John Parkway;md.cabjohnpkwy;New Route
> per usanp thread

- hwy_data/IN/usai/in.i069whe.wpt
- hwy_data/IN/usain/in.in037.wpt
- hwy_data/IN/usain/in.in045.wpt
- hwy_data/IN/usain/in.in062.wpt
- hwy_data/IN/usain/in.in445.wpt
- hwy_data/IN/usaus/in.us050.wpt
- hwy_data/ITA/eure/ita.e35.wpt
- hwy_data/WY/usai/wy.i080.wpt
- hwy_data/WY/usaib/wy.i080blpin.wpt
- hwy_data/WY/usaus/wy.us030.wpt
- hwy_data/WY/usawy/wy.wy215.wpt
2015-12-09;(USA) Indiana;I-69 (Wheatonville);in.i069whe;Route extended at north end from exit 87 to exit 114
> Indiana I-69, various minor clean ups

- hwy_data/FL/usai/fl.i004.wpt
- hwy_data/FL/usasf/fl.fltpk.wpt
Just added two new exits (1 to FL Turnpike & 1 to I-4).
With the I-4 one, some label tweaking needed to be done.  However, nobody was using the '2' label, so I don't think a mention in the update log is necessary for this change.
> FL: New Exits

- hwy_data/CT/usai/ct.i395.wpt
No .list files are affected.
No updates entry necessary.
> CT I-395: sequential -> milepost

- continents.csv
- countries.csv
- regions.csv
.csv files for the region system. May not be 100% accurate (eg continents for grey areas, geopolitical issues), and is certainly subject to change.
> Region csv files

- hwy_data/HI/usahi/hi.hi3000.wpt
- hwy_data/_systems/usahi.csv
- hwy_data/_systems/usahi_con.csv
Adds HI 3000 (partially-completed Lahaina Bypass on Maui) to usahi.
Updates item:
2015-12-26;(USA) Hawaii;HI 3000;hi.hi3000;Route added
> HI 3000 addition

- hwy_data/NM/usanm/nm.nm028.wpt
- hwy_data/NM/usanm/nm.nm101.wpt
- hwy_data/NM/usanm/nm.nm478.wpt
Responds to issue #282. Relabels waypoints in three USANM route files, to NM188 (part of former I-10BL). Only one of those waypoints was in use, and its former ;label remains as an alternate label.
No Updates item needed.
> Las Cruces NM tweaks

- hwy_data/KY/usaky/ky.ky0008.wpt
- hwy_data/KY/usaky/ky.ky0008van.wpt
- hwy_data/KY/usaky/ky.ky0018.wpt
- hwy_data/KY/usaky/ky.ky0059.wpt
- hwy_data/KY/usaky/ky.ky0236.wpt
- hwy_data/KY/usaky/ky.ky0237.wpt
- hwy_data/KY/usaky/ky.ky0338.wpt
- hwy_data/KY/usaky/ky.ky0472.wpt
- hwy_data/KY/usaky/ky.ky0638.wpt
- hwy_data/KY/usaky/ky.ky0687.wpt
- hwy_data/KY/usaky/ky.ky0717.wpt
- hwy_data/KY/usaky/ky.ky0842.wpt
- hwy_data/KY/usaky3/ky.ky1017.wpt
- hwy_data/KY/usasf/ky.weskypkwy.wpt
- hwy_data/KY/usaus/ky.us421.wpt
http://clinched.s2.bizhat.com/viewtopic.php?t=2314
2016-01-04;(USA) Kentucky;KY 717;ky.ky0717;Extended at north end from KY 1017 (east) to KY 3076
2016-01-04;(USA) Kentucky;KY 8;ky.ky0008;Truncated at west end from 39.129095°, -84.759178° to KY 237
> Old forum issues part 2

- hwy_data/NC/usaif/nc.i495futroc.wpt
- hwy_data/OH/usaoh/oh.oh003.wpt
- hwy_data/OH/usaoh/oh.oh028.wpt
- hwy_data/OH/usaoh/oh.oh061.wpt
- hwy_data/OH/usaoh/oh.oh083.wpt
- hwy_data/OH/usaoh/oh.oh707.wpt
- hwy_data/OH/usaus/oh.us062.wpt
2016-01-07;(USA) Ohio;OH 61;oh.oh061;Removed from Seltzer Street and relocated onto Thoman Street and Main Street between a closed intersection with Seltzer Street and OH 181.
2016-01-07;(USA) Ohio;OH 83;oh.oh083;Removed from Center Road and Main Street and Avon, and relocated onto Chester Road and Avon Belden Road.
2016-01-07;(USA) Ohio;OH 707;oh.oh707;Removed from Mercer Road between US 33 and US 127, and relocated onto US 33 & US 127.
> More old forum issues

- hwy_data/SC/usausb/sc.us015consum.wpt
- hwy_data/_systems/usausb.csv
- hwy_data/_systems/usausb_con.csv
See comments in #295.
2016-01-08;(USA) South Carolina;US 15 Connector (Sumter);;Route deleted
> SC: US-15 Connector removal in Sumter, SC.

- systemupdates.csv
- updates.csv
> KY tweaks: updates & systemupdates CSVs

- hwy_data/KY/usaky3/ky.ky1076.wpt
- systemupdates.csv
system in preview status; no updates text necessary
addresses part of #332
> KY1076: relocation at south end, to TN state line

- hwy_data/MI/usai/mi.i696.wpt
- hwy_data/MI/usami/mi.mi005.wpt
http://clinched.s2.bizhat.com/viewtopic.php?t=1922&mforum=clinched
2016-01-21;(USA) Michigan;I-696;mi.i696;Extended at west end from waypoint 1A to I-96.
> MI: I-96, M-5, I-696

- hwy_data/MI/usai/mi.i075.wpt
- hwy_data/MI/usai/mi.i096.wpt
- hwy_data/MI/usami/mi.mi153.wpt
- hwy_data/MI/usaus/mi.us012.wpt
2016-01-23;(USA) Michigan;MI 153;mi.mi153;Removed from McGraw St and Weir St between Wyoming Ave and I-94, and relocated onto Wyoming Ave between McGraw St and US 12.
http://clinched.s2.bizhat.com/viewtopic.php?t=2303
**MI153:**
Moved McGSt from McGraw & Weir to McGraw & Wyoming
I-94(210B) moved from Weir to Wyoming; deprecated in favor of I-94
US12 added
**US12:**
MI153 added
No new waypoints at Weir or Addison; that'd make the density a bit much...
LonSt, CecAve, LivAve, WestGraBlvd added. (Is WestGraBlvd a bit much?)
I-75 moved onto road centerline; deprecated in favor of I-96†
RosaParBlvd added
**I-96:**
+I-75_N moved to "middle of the central ramp triangle", and thus folded into...
US12, now conveniently also on US12 centerline. Label deprecated in favor of 191A, invoking the "Two …
> MI153 E end relocation; Detroit-area tweaks/cleanup

- hwy_data/CA/usai/ca.i305.wpt
- hwy_data/CA/usaus/ca.us101.wpt
Updates I-305, to restore its concurrencies with I-80BL Sacramento and US 50, and also tweaks south end of US 101 to restore its short concurrency with I-5, while I complete the rest of the CA Interstates cleanup.
> CA Interstates cleanup part 4

- hwy_data/CA/usai/ca.i305.wpt
Error fix on just-updated I-305 route file, based on what turned out to be an out-of-sync version of the I-80BLSac route file. Double-checked to make sure this one will sync with the master versions of I-80BLSac and US 50.
> CA interstates cleanup part 4A

- hwy_data/UT/usaut/ut.ut007san.wpt
> Delete UT 007San

- hwy_data/UT/usaut/ut.ut007.wpt
The two routes are now connected.
> Merge UT007 and UT007 San

- hwy_data/AL/usai/al.i085.wpt
Just added new exits 14 (opened 01/26/16) & 50 (http://clinched.s2.bizhat.com/viewtopic.php?t=2209&mforum=clinched).  I also re-centered 16 which was way off of the correct location.
No need for an update entry for this one.
> AL: Some I-85 fixes

- hwy_data/PA/usapa/pa.pa378.wpt
- hwy_data/PA/usapa/pa.pa412.wpt
This solves #111.
No update mention needed as there was no highway alignment changes to either route.
> PA: PA-378 & PA-412 tweaks

- hwy_data/KY/usaky/ky.ky0581.wpt
- hwy_data/KY/usausb/ky.us031wbypeli.wpt
- hwy_data/OH/usaoh/oh.oh007.wpt
- hwy_data/OH/usaoh/oh.oh032.wpt
- hwy_data/OH/usaoh/oh.oh339.wpt
- hwy_data/OH/usausb/oh.us050busbel.wpt
Add missing alt labels & other minor corrections
> KY & OH fixes

- hwy_data/ND/usand/nd.nd023btrknew.wpt
swapped ND23 & ND1804 labels; reversed point order
> ND23BTrkNew point label correction

- hwy_data/PA/usapa/pa.pa034.wpt
- hwy_data/PA/usausb/pa.us015busget.wpt
per http://tm.teresco.org/forum/index.php?topic=95.msg450#msg450
> PA: PA 34 at US 15 Business (Gettysburg, PA) point relocations

- hwy_data/TX/usai/tx.i169.wpt
per http://tm.teresco.org/forum/index.php?topic=99.msg0#new
> TX I-169: delete BakLn

- hwy_data/NC/usai/nc.i073.wpt
- hwy_data/NC/usai/nc.i074hig.wpt
- hwy_data/NC/usanc/nc.nc211.wpt
- hwy_data/NC/usanc/nc.nc906.wpt
- hwy_data/NC/usaus/nc.us017.wpt
- hwy_data/NC/usaus/nc.us220.wpt
- hwy_data/NC/usausb/nc.us017busbol.wpt
- hwy_data/NC/usausb/nc.us220altcan.wpt
- hwy_data/_systems/usai.csv
- hwy_data/_systems/usaif.csv
- hwy_data/_systems/usaif_con.csv
- hwy_data/_systems/usanc.csv
- hwy_data/_systems/usanc_con.csv
YYYY-MM-DD;Country;Route;Root;Description
2016-02-17;(USA) North Carolina;NC 906;nc.nc906;added newly commissioned NC 906 requiring additional points to US 17 and US 17busbol
2016-02-17;(USA) North Carolina;I-74 High Point;nc.i074hig;added fut I-74 high point exits to this as it is now an interstate...also added new waypoint at 72B(73)
2016-02-17;(USA) North Carolina;I-73;nc.i073;added new waypoint at 72B
2016-02-17;(USA) North Carolina;US 220;nc.us220;added new waypoint at 72B(73)
2016-02-17;(USA) North Carolina;I-74 Future (High Point);nc.i074futhig;Route deleted
> NC changes from mapmikey

- updates.csv
updates.csv: changes as discussed on 2abfb83
> updates.csv: changes as discussed on 2abfb83

- hwy_data/KY/usaky/ky.ky0018.wpt
- hwy_data/KY/usaus/ky.us042.wpt
- hwy_data/KY/usaus/ky.us127.wpt
http://tm.teresco.org/forum/index.php?topic=117.0
> Waypoint rename: KY3157->MallRd

- hwy_data/PA/usapa/pa.pa010.wpt
- hwy_data/PA/usapa/pa.pa023.wpt
- hwy_data/PA/usapa/pa.pa134.wpt
- hwy_data/PA/usapa/pa.pa174.wpt
- hwy_data/PA/usapa/pa.pa394.wpt
- hwy_data/PA/usapa/pa.pa533.wpt
- hwy_data/PA/usaus/pa.us011.wpt
- hwy_data/PA/usaus/pa.us015.wpt
- hwy_data/PA/usausb/pa.us015busget.wpt
http://tm.teresco.org/forum/index.php?topic=95.msg560#msg560
http://tm.teresco.org/forum/index.php?topic=115
http://tm.teresco.org/forum/index.php?topic=116
All non-newsworthy.
> PA changes per Markkos1992

- hwy_data/MD/usamd/md.md002.wpt
- hwy_data/MD/usaus/md.us015.wpt
- hwy_data/MD/usaus/md.us340.wpt
http://tm.teresco.org/forum/index.php?topic=143.0
> MD US15/340: JefTecPkwy added

- hwy_data/GA/usai/ga.i075.wpt
- hwy_data/GA/usai/ga.i575.wpt
http://tm.teresco.org/forum/index.php?topic=145.0
No need for a mention on the update page.
> GA: New Interstate exits

- hwy_data/FL/usai/fl.i095.wpt
http://tm.teresco.org/forum/index.php?topic=123.0
No update entry needed.
> fl.i095: Added Exit 293.

- systems.csv
- systemupdates.csv
Activates
- Åland Kantatiet
- Åland Valtatiet
- Belgium Ringwegen
- Corsica Routes Territoriales
- Denmark Primærruter
- Finland Valtatiet
- Finland Kantatiet
- France Routes Nationales
- French Guiana Routes Nationales
- French Polynesia Routes Territoriale
- Guadaloupe Routes Nationales
- Guam Territorial Highways
- Latvia Galvenā Ceļš
- Lithuania Magistraliniai Keliai
- Martinique Routes Nationales
- Mayotte Routes Nationales
- New Caledonia Routes Territoriales
- New Caledonia Voie Express
- Northern Mariana Islands Territorial Highways
- Reunion Routes Nationales
- Sainte Pierre and Miquelon Routes Territoriales
- US Virgin Islands Territorial Highways
- Wallis and Futuna Routes Territoriales
as I said I would do it at the end of the month.
> Activate systems

- hwy_data/PA/usaus/pa.us209.wpt
http://tm.teresco.org/forum/index.php?topic=172
> PA US209: PA902_W -> PA902; PA902_E +-> MainLn

- hwy_data/MD/usamd/md.md004.wpt
- hwy_data/MD/usamd/md.md717.wpt
- hwy_data/MD/usamd/md.md725.wpt
- hwy_data/_systems/usamd.csv
- hwy_data/_systems/usamd_con.csv
Adds to HB newly-signed MD 717 in Upper Marlboro, which I spotted yesterday evening. Conforming edits to MD 4 and MD 725.
Update item:
2016-4-24;(USA) Maryland MD 717;md.md717;Added route
> Add MD 717

- hwy_data/GA/usaib/ga.i075blval.wpt
- hwy_data/GA/usaus/ga.us041.wpt
This should resync I-75BL Valdosta with the US Highways it travels along.
http://tm.teresco.org/forum/index.php?topic=216.0
> GA: Minor file resyncs

- hwy_data/PA/usapa/pa.pa031.wpt
Re-syncing PA-31 with PA-96 multiplex.
> PA: PA-31 resync with PA-96

- hwy_data/KY/usaky/ky.ky0610.wpt
- hwy_data/KY/usaky8/ky.ky3519.wpt
- hwy_data/KY/usaky8/ky.ky3525.wpt
- hwy_data/KY/usaky8/ky.ky3527.wpt
- hwy_data/KY/usaky8/ky.ky6011.wpt
- hwy_data/KY/usaky8/ky.ky6074.wpt
Looks ready to be moved to preview.
> Final usaky8 cleanup

- hwy_data/MA/usama/ma.ma003aman.wpt
- hwy_data/MA/usama/ma.ma016.wpt
> MA16: MysValPlwy +-> MysValPkwy

- hwy_data/_systems/usausb.csv
- hwy_data/_systems/usausb_con.csv
Wasn't included in the system files when added to the site.  This fixes that.
http://tm.teresco.org/forum/index.php?topic=278.msg1455#msg1455
> NC: US-70 Bypass (Goldsboro)

- systems.csv
- systemupdates.csv
Activates andcg, estt, luxn, mltt and roudn.
Allows preview of hunf, srbb and svki
> 21 june activations

- hwy_data/GA/usaga/ga.ga052altcha.wpt
GA52 Alt Chatsworth: GA255 -> GA225
> usaga - Label fix

- hwy_data/PA/usapa/pa.pa034.wpt
See: http://tm.teresco.org/forum/index.php?topic=318.0
> PA: PA-34 fix

- hwy_data/SC/usasc/sc.sc028.wpt
- hwy_data/SC/usasc/sc.sc034.wpt
Fixes broken multiplex with US-321. See: http://tm.teresco.org/forum/index.php?topic=321.msg1617#msg1617
> SC: SC multiplex resync coordinates fixes

- hwy_data/TN/usaif/tn.i269futmem.wpt
- hwy_data/TN/usansf/tn.tn111dun.wpt
- hwy_data/TN/usansf/tn.tn153.wpt
- hwy_data/TN/usansf/tn.tn155.wpt
- hwy_data/TN/usansf/tn.tn385.wpt
- hwy_data/TN/usansf/tn.tn396.wpt
- hwy_data/TN/usansf/tn.tn840.wpt
- hwy_data/TN/usaus/tn.us031.wpt
- hwy_data/TN/usaus/tn.us064.wpt
- hwy_data/TN/usaus/tn.us070.wpt
- hwy_data/TN/usaus/tn.us079.wpt
- hwy_data/TN/usaus/tn.us231.wpt
See: http://tm.teresco.org/forum/index.php?topic=335.0
> TN: coordinate resync

- hwy_data/RI/usari/ri.ri012.wpt
- hwy_data/RI/usari/ri.ri015.wpt
Whoopsie. I meant to edit these in the yakra/NMP branch, and not yakra/master. We should be okay, though.
> Rhode Island NMP fixes

- hwy_data/MA/usama/ma.ma122awor.wpt
- hwy_data/MA/usama/ma.ma146.wpt
http://tm.teresco.org/forum/index.php?topic=362
> MA146 exit numbers

- hwy_data/MT/usaus/mt.us002.wpt
Request to add point in Cut Bank, at east end of detour around downtown segment closed for reconstruction, which is now the only part of US 2 I haven't traveled. The west end of the detour is just east of SR213, no waypoint needed there,
Si, OK with you?
> MT US2 point request

- hwy_data/WA/usaib/wa.i090blspo.wpt
- hwy_data/WA/usawa/wa.wa027.wpt
- hwy_data/_systems/usaib.csv
- hwy_data/_systems/usaib_con.csv
As discussed in the TM forum. Includes conforming point addition to intersecting WA 27.
Updates entry:
2016-07-28;(USA) Washington;I-90 Business Loop (Spokane Valley);wa.i090blspo;Route added
> Add WA I-90BL Spokane Valley

- chm_final/usaus/al.us082.wpt
Update US 82 onto the Centreville bypass.
> US 82 Centreville

- hwy_data/AL/usaus/al.us331.wpt
Remove ALT US 331 Opp designation and revise waypoint.
> US 331 Opp

- chm_final/usaus/al.us082.wpt
Reverts TravelMapping/HighwayData#709
Mistakenly updated chm_final instead of hwy_data.
> Revert "US 82 Centreville"

- hwy_data/AL/usaus/al.us082.wpt
Update US 82 list to reflect completion of Centreville bypass.   Correct file location this time.
> Update al.us082.wpt for Centreville bypass

- hwy_data/PA/usapa/pa.pa024.wpt
- hwy_data/PA/usapa/pa.pa183.wpt
- hwy_data/PA/usapa/pa.pa248.wpt
Just fixed a few outstanding PA errors from the forum.
http://tm.teresco.org/forum/index.php?topic=388.0
http://tm.teresco.org/forum/index.php?topic=387.0
http://tm.teresco.org/forum/index.php?topic=379.0
> Misc PA fixes

- hwy_data/ITA/itaa/ita.a006.wpt
- hwy_data/ITA/itaa/ita.a055mon.wpt
- hwy_data/KAZ/eure/kaz.e123.wpt
- hwy_data/TUR/turo/tur.o006.wpt
- hwy_data/TUR/turo/tur.o006san.wpt
- hwy_data/WY/usaus/wy.us212col.wpt
- hwy_data/_systems/itaa.csv
- hwy_data/_systems/itaa_con.csv
- hwy_data/_systems/turo.csv
- hwy_data/_systems/turo_con.csv
- systemupdates.csv
2016-09-10;Italy;A6;ita.a006;Route truncated at north end from CorTri to A55
2016-09-10;Italy;A55 (Diramazione per Moncalieri);ita.a055mon;New Route
2016-09-10;Turkey;O6 (Sancaktepe (branch));tur.o006san;New Route
> various fixes per requests

- hwy_data/GA/usaga/ga.ga017bypmil.wpt
http://tm.teresco.org/forum/index.php?topic=442.0
> usaga - GA17BypMil Label fix

- hwy_data/TX/usatx/tx.tx285.wpt
tm.teresco.org/forum/index.php?topic=449.0
> TX285: US3281Bus -> US281Bus

- hwy_data/FL/usafl/fl.fl009bjac.wpt
- hwy_data/FL/usaif/fl.i795futjac.wpt
Reversed both ways based on how the exit numbers are being posted now.  Otherwise, no update entry required as exit numbers weren't in use for the file yet.
http://tm.teresco.org/forum/index.php?topic=27.msg2425#msg2425
> FL: Future I-795/FL-9B

- hwy_data/NY/usany/ny.ny085.wpt
- hwy_data/NY/usany/ny.ny378.wpt
http://tm.teresco.org/forum/index.php?topic=453.0
> NY85 & NY378

- hwy_data/BC/cantch/bc.tchmai.wpt
- hwy_data/BC/cantch/bc.tchvan.wpt
Fixes broken concurrences between TCHMai and TCHVan, and corresponding BC 1 routes, by adding points to TCH files.
No Updates items needed.
> BC TCH 1 changes

- hwy_data/KS/usaus/ks.us024.wpt
http://tm.teresco.org/forum/index.php?topic=1762.0
> KS US24: MenRd added

- hwy_data/WA/usawa/wa.wa522.wpt
These intersections have been moved over the past several years, so I am updating their positions.
> Update coordinates for waypoints BotWay and WooDr

- hwy_data/WA/usawa/wa.wa823.wpt
Source: http://www.wsdot.wa.gov/projects/sr823/selahvicinity/
> WA 823 rerouted onto Jim Clements Way

- hwy_data/WA/usawa/wa.wa092.wpt
Rerouted along Quarry Road (Granite Falls Bypass) with three new waypoints added; also added one at 84th St NE.
> Reroute, add additional waypoint (WA 92)

- hwy_data/NY/usai/ny.i390.wpt
- hwy_data/NY/usany/ny.ny015.wpt
- hwy_data/NY/usany/ny.ny015a.wpt
> NY I-390 Exit 16

- hwy_data/MB/canmb/mb.mb002.wpt
- hwy_data/MB/canmb/mb.mb003.wpt
- hwy_data/MB/canmb/mb.mb004.wpt
- hwy_data/MB/canmb/mb.mb005.wpt
- hwy_data/MB/canmb/mb.mb006.wpt
- hwy_data/MB/canmb/mb.mb010.wpt
- hwy_data/MB/canmb/mb.mb014.wpt
- hwy_data/MB/canmb/mb.mb023.wpt
- hwy_data/MB/canmb/mb.mb077.wpt
- hwy_data/MB/canmb/mb.mb083.wpt
- hwy_data/MB/canmb/mb.mb101.wpt
- hwy_data/MB/cantch/mb.tchmai.wpt
SK/MB coords
PTH/PR intersections: use only PTH in label
Streets & Avenues: cardinal -> ordinal
Directional suffix cleanup
NMPs
> canmb preview cleanup

- hwy_data/IN/usaif/in.i265futlou.wpt
- hwy_data/IN/usain/in.in265.wpt
- hwy_data/KY/usaif/ky.i265futlou.wpt
- hwy_data/KY/usaky/ky.ky0841.wpt
2016-12-18;(USA) Indiana;IN265;in.in265;Route extended to Kentucky border at new Ohio River bridge
2016-12-18;(USA) Indiana;I-265 Fut (Louisville, KY);in.i265futlou;Route extended to Kentucky border at new Ohio River bridge
2016-12-18;(USA) Kentucky;KY841;ky.ky0841;Route extended to Indiana border at new Ohio River bridge
2016-12-18;(USA) Kentucky;I-265 Fut (Louisville, KY);ky.i265futlou;Route extended to Indiana border at new Ohio River bridge
> I-265FutLou Ohio River bridge

- hwy_data/MI/usai/mi.i075.wpt
- hwy_data/MI/usai/mi.i094.wpt
- hwy_data/MI/usai/mi.i096.wpt
- hwy_data/MI/usami/mi.mi005.wpt
- updates.csv
MI5 extension per http://tm.teresco.org/forum/index.php?topic=1862.0
Slight adjustments to waypoint locations for interchanges with I-75, I-94, I-96, & MI10.
> MI5 extension

- hwy_data/PA/usai/pa.i476.wpt
- hwy_data/PA/usapa/pa.pa063.wpt
- hwy_data/PA/usapa/pa.pa903.wpt
- hwy_data/PA/usaus/pa.us209.wpt
- updates.csv
Solves:
http://tm.teresco.org/forum/index.php?topic=1865.0
http://tm.teresco.org/forum/index.php?topic=205.0
> PA updates

- hwy_data/WA/usawa/wa.wa100.wpt
- hwy_data/WA/usawa/wa.wa103.wpt
- hwy_data/_systems/usawa.csv
- hwy_data/_systems/usawa_con.csv
- updates.csv
This is a repeat of pull request #1009, but using an updated master fork.
> Extend WA 103 northward, add WA 100 Spur

- hwy_data/AR/usai/ar.i040.wpt
- hwy_data/AR/usai/ar.i049.wpt
- hwy_data/AR/usai/ar.i055.wpt
- hwy_data/AR/usaus/ar.us059.wpt
- hwy_data/AR/usaus/ar.us061.wpt
- hwy_data/AR/usaus/ar.us062.wpt
- hwy_data/AR/usaus/ar.us063.wpt
- hwy_data/AR/usaus/ar.us064.wpt
- hwy_data/AR/usaus/ar.us071.wpt
- hwy_data/AR/usaus/ar.us079.wpt
- hwy_data/AR/usaus/ar.us167.wpt
- hwy_data/AR/usaus/ar.us271.wpt
- hwy_data/AR/usaus/ar.us278.wpt
- hwy_data/AR/usaus/ar.us412.wpt
- hwy_data/AR/usausb/ar.us064busalm.wpt
- hwy_data/AR/usausb/ar.us065buspin.wpt
- hwy_data/AR/usausb/ar.us067busdat.wpt
- hwy_data/AR/usausb/ar.us071busfay.wpt
- hwy_data/AR/usausb/ar.us071busfor.wpt
- hwy_data/AR/usausb/ar.us071buswal.wpt
- hwy_data/AR/usausb/ar.us071sprfay.wpt
- hwy_data/AR/usausb/ar.us082buseld.wpt
- hwy_data/AR/usausb/ar.us167buseld.wpt
requesting an updated TMG file.
> AR Cleanup Part 4

- hwy_data/WA/usawa/wa100sprfor.wpt
Forgot to do this in my previous pull request #1039. This should solve the error that was taking place when @jteresco was doing the site update.
> Create waypoint file for WA 100 Spur

- hwy_data/MB/canmb/mb.mb011.wpt
- hwy_data/MB/canmb/mb.mb044.wpt
- hwy_data/MB/canmb/mb.mb068.wpt
- hwy_data/MB/canmb/mb.mb077.wpt
http://tm.teresco.org/forum/index.php?topic=9.msg4975#msg4975
> canmb peer review part 1

- hwy_data/NY/usai/ny.i084.wpt
- hwy_data/NY/usai/ny.i087.wpt
- hwy_data/NY/usany/ny.ny007.wpt
- hwy_data/NY/usany/ny.ny009d.wpt
- hwy_data/NY/usany/ny.ny009r.wpt
- hwy_data/NY/usany/ny.ny022.wpt
- hwy_data/NY/usany/ny.ny032.wpt
- hwy_data/NY/usany/ny.ny052.wpt
- hwy_data/NY/usany/ny.ny052busbea.wpt
- hwy_data/NY/usany/ny.ny093.wpt
- hwy_data/NY/usany/ny.ny300.wpt
- hwy_data/NY/usany/ny.ny787.wpt
- hwy_data/NY/usasf/ny.fdroodr.wpt
- hwy_data/NY/usaus/ny.us009.wpt
- hwy_data/NY/usaus/ny.us009w.wpt
http://tm.teresco.org/forum/index.php?topic=1885
> NY NMPs, broken multiplexes, and other cleanup

- hwy_data/_systems/usawa.csv
As reported here: http://tm.teresco.org/forum/index.php?topic=1919.msg0#new
> Adding missing city field to wa099fed in usawa.csv file

- hwy_data/WA/usai/wa.i005.wpt
- hwy_data/WA/usaus/wa.us195.wpt
- hwy_data/WA/usawa/wa.wa411.wpt
- hwy_data/WA/usawa/wa.wa501.wpt
- hwy_data/WA/usawa/wa.wa504.wpt
- hwy_data/WA/usawa/wa.wa506.wpt
http://tm.teresco.org/forum/index.php?topic=1890.msg5238#msg5238
> Fixing more NMPs in Washington

- hwy_data/CA/usaca/ca.ca047.wpt
- hwy_data/CA/usaca/ca.ca103.wpt
- hwy_data/HI/usahi/hi.hi380.wpt
Tweaks to ari active HI route, and two in-dev CA routes
> Misc CA and HI changes

- hwy_data/NY/usausb/ny.us006altgar.wpt
http://tm.teresco.org/forum/index.php?topic=1956
> NY US6AltGar endpoint labels

- hwy_data/NY/usany/ny.ny052a.wpt
http://tm.teresco.org/forum/index.php?topic=1963
> NY52A: Fulton Hill Rd bridge closed

- hwy_data/WA/usawa/wa.wa509.wpt
Exit has been closed for several years.
> Remove 176thSt waypoint from WA 509

- hwy_data/ID/usaid/id.id054.wpt
- hwy_data/ID/usaid/id.id058.wpt
- hwy_data/ID/usaid/id.id200.wpt
- hwy_data/ID/usaus/id.us002.wpt
- hwy_data/ID/usaus/id.us020.wpt
- hwy_data/ID/usaus/id.us095.wpt
- updates.csv
Realigned US 95 in Athol, also added some new exits south of there, (http://tm.teresco.org/forum/index.php?topic=1926.msg5607#new) and added US 95 bypass of Sandpoint, ID. Also moving waypoint at US 95/ID 58, and updating position of a waypoint on US 2 in Dover.
EDIT: Added exit 328 to US 20
> Updates in Idaho

- hwy_data/WA/usawa/wa.wa509.wpt
Per suggestion by @rickmastfan67 in pull request #1177
> Re-adding 176thSt waypoint as a "closed" waypoint

- hwy_data/ID/usaus/id.us095.wpt
- updates.csv
Fixes the updates entry and a waypoint label that were changed in #1181.
> Fixes for #1181

- hwy_data/BC/canbc/bc.bc016.wpt
- hwy_data/BC/cantch/bc.tchyel.wpt
In both files, BC62  => ChuRd.
> BC TCH/BC 16 label fix

- hwy_data/ID/usai/id.i090.wpt
Sorry for the multiple pull requests, I screwed up and didn't put all the commits together. Whoops...
> fixing NMP in ID

- hwy_data/ID/usaus/id.us095.wpt
Fixing position of 446 waypoint, re-add SonShiWay as a closed waypoint
> Minor US 95 fixes

- hwy_data/RI/usari/ri.ri005.wpt
- hwy_data/RI/usari/ri.ri015.wpt
- hwy_data/RI/usari/ri.ri114.wpt
- hwy_data/RI/usari/ri.ri115.wpt
- hwy_data/RI/usari/ri.ri117.wpt
- hwy_data/RI/usaus/ri.us001.wpt
- updates.csv
http://tm.teresco.org/forum/index.php?topic=1971
> Rhode Island changes

- hwy_data/SK/cantch/sk.tchmai.wpt
Foxes waypoint SK47_W, with minor tweaks to waypoints SK616 and SK47_E.
> SK TCH 1 point fixes

- hwy_data/KS/usaks/ks.ks010.wpt
- hwy_data/KS/usaus/ks.us040.wpt
http://tm.teresco.org/forum/index.php?topic=1968.msg5723#msg5723
> KS: Bob Billings Pkwy interchange

- hwy_data/NE/usane/ne.ne010.wpt
- hwy_data/NE/usane/ne.ne044.wpt
- hwy_data/NE/usanes/ne.l10f.wpt
- hwy_data/NE/usaus/ne.us030.wpt
- hwy_data/NE/usaus/ne.us136.wpt
- hwy_data/_systems/usanes.csv
- hwy_data/_systems/usanes_con.csv
- updates.csv
http://tm.teresco.org/forum/index.php?topic=1884
http://tm.teresco.org/forum/index.php?topic=2000
Re: 34dc9c0, I went with Option 1. Discussion at:
http://tm.teresco.org/forum/index.php?topic=1889
> NE: Kearney East Bypass and US136 point request

- hwy_data/CA/usaca/ca.ca083.wpt
- hwy_data/CA/usaca/ca.ca091.wpt
- hwy_data/CA/usaca/ca.ca140.wpt
- hwy_data/CA/usaca/ca.ca155.wpt
Fixes for the worst errors I spotted while updating my list file.
> More usaca edits

- hwy_data/WA/usawa/wa.wa169.wpt
> adding CedGroRd waypoint to WA 169

- hwy_data/UT/usaus/ut.us089.wpt
resolves this thread: http://tm.teresco.org/forum/index.php?topic=103.0
> adding missing waypoint on US 89 for UT 175

- hwy_data/WA/usaus/wa.us012.wpt
Adding exit 74 from I-5 multiplex
> Add exit 74 (I-5) to US 12

- hwy_data/WV/usai/wv.i079.wpt
Added new I-79 Exit #153, which opened 09/01/16.
> WV: New I-79 exit

- hwy_data/QC/canqca/qc.a040.wpt
Fixing QC A-40, whose point synch with A-640 didn't make it into my last
pull request.
> QC A-40 point synch

- hwy_data/PA/usapa/pa.pa392.wpt
- hwy_data/PA/usapa/pa.pa419.wpt
- hwy_data/PA/usapa/pa.pa501.wpt
- hwy_data/PA/usapa/pa.pa772.wpt
- hwy_data/PA/usapa/pa.pa897.wpt
- hwy_data/PA/usaus/pa.us030.wpt
http://tm.teresco.org/forum/index.php?topic=2030
http://tm.teresco.org/forum/index.php?topic=2029
http://tm.teresco.org/forum/index.php?topic=1838
> PA fixes from the forum

- hwy_data/ON/canon/on.on017.wpt
- hwy_data/ON/canonf/on.on417.wpt
- hwy_data/ON/cantch/on.tchott.wpt
- updates.csv
Solves http://tm.teresco.org/forum/index.php?topic=423.0
> ON-17/ON-417 changes

- hwy_data/WA/usawa/wa.wa125sprwal.wpt
Fixing location of waypoint at east end (I accidentally copy/pasted the wrong coordinates when I made this file)
> Fixing WA 125 Spur (Walla Walla)

- hwy_data/CT/usact/ct.ct002a.wpt
- updates.csv
http://tm.teresco.org/forum/index.php?topic=346
> CT2A: sequential -> milepost

- hwy_data/MD/usamd/md.md351.wpt
- hwy_data/MD/usaus/md.us015.wpt
- hwy_data/MD/usaus/md.us340.wpt
- hwy_data/_systems/usamd.csv
- hwy_data/_systems/usamd_con.csv
- updates.csv
tm.teresco.org/forum/index.php?topic=1823
> MD351 deleted

- hwy_data/ID/usausb/id.us030buslav.wpt
- updates.csv
Is not signed according to this topic in the forum: http://tm.teresco.org/forum/index.php?topic=2061.0
> Deleting US 30 Bus (Lava Hot Springs, ID)

- hwy_data/ON/cannf/on.redhillpkwy.wpt
- hwy_data/ON/canon/on.on007.wpt
- hwy_data/ON/canon/on.on011.wpt
- hwy_data/ON/canon/on.on061.wpt
- hwy_data/ON/canon/on.on115.wpt
- hwy_data/ON/canonf/on.on403.wpt
- hwy_data/ON/canonf/on.on427.wpt
- hwy_data/ON/canonf/on.onqew.wpt
- hwy_data/ON/cantch/on.tchcen.wpt
- updates.csv
Mostly NMP fixes with a small shortening of ON-427.
http://tm.teresco.org/forum/index.php?topic=335.msg6381#msg6381
> ON: nmp fixes

- hwy_data/MS/usai/ms.i010.wpt
- hwy_data/MS/usai/ms.i110.wpt
- hwy_data/MS/usaus/ms.us049.wpt
Solves http://tm.teresco.org/forum/index.php?topic=118.0
Also re-centered all of I-10 in MS as it needed it badly as all interchanges were off-centered.
> MS: I-110 new interchange

- hwy_data/AL/usaus/al.us231.wpt
Changed US80_E label to AtlHwy due to rerouting of US 80.
> Updated al.us231.wpt

- hwy_data/ND/usaus/nd.us085.wpt
- hwy_data/SK/cansph/sk.sk035.wpt
SK point moved with permission after some discussion with @ovoss
> SK35 & US85 NMP 

- hwy_data/MN/usai/mn.i094.wpt
- hwy_data/MN/usaib/mn.i090blwor.wpt
- hwy_data/MN/usamn/mn.mn060.wpt
- hwy_data/MN/usamn/mn.mn099.wpt
- hwy_data/MN/usamn/mn.mn111.wpt
- hwy_data/MN/usamn/mn.mn610.wpt
- hwy_data/MN/usaus/mn.us014.wpt
- hwy_data/MN/usaus/mn.us059.wpt
- updates.csv
Revisions for the US 14 Nicollet Bypass, MN 60 realignments near Worthington, and the MN 610 extension plus associated routes.
> Minnesota US 14, MN 60, and MN 610 bypasses

- hwy_data/PA/usaus/pa.us322.wpt
http://tm.teresco.org/forum/index.php?topic=2101
> PA US322: HighSt +-> PotPk

- hwy_data/MB/canmbw/mb.rt052.wpt
- hwy_data/MB/canmbw/mb.rt090.wpt
- hwy_data/MB/canmbw/mb.rt135.wpt
Rte52: swap MB1_W & MB1_E labels
Rte90: MB101 -> MB7/101
Rte135: 348 -> MB100/101
> canmbw devel cleanup 2, label fixes

- hwy_data/NJ/usai/nj.i295.wpt
- hwy_data/NJ/usanj/nj.nj440.wpt
- hwy_data/NJ/usasf/nj.garstapkwy.wpt
- hwy_data/NJ/usaus/nj.us001.wpt
- hwy_data/NJ/usaus/nj.us009.wpt
- hwy_data/NJ/usaus/nj.us130.wpt
http://tm.teresco.org/forum/index.php?topic=2103
http://tm.teresco.org/forum/index.php?topic=2104
http://tm.teresco.org/forum/index.php?topic=2105
...and GarStaPkwy along for the ride
> NJ fixes from the forum

- hwy_data/MD/usamd/md.md307.wpt
- hwy_data/MD/usamd/md.md392.wpt
- hwy_data/MD/usaus/md.us013.wpt
http://tm.teresco.org/forum/index.php?topic=306
http://tm.teresco.org/forum/index.php?topic=1949
> MD point additions from the forum

- hwy_data/ID/usaib/id.i090blosb.wpt
- hwy_data/ID/usaid/id.id078.wpt
- updates.csv
Per post in the forum: http://tm.teresco.org/forum/index.php?topic=2091.0
> ID updates

- updates.csv
Removes a dead link that was introduced into the updates.csv file.
> removed dead link

- hwy_data/SC/usasc/sc.sc161.wpt
ping @mapmikey whose region this is
> SC161: add point for Park Road (usanp)

- hwy_data/OK/usaus/ok.us177.wpt
Ping @yakra whose region this is
> OK US177: add point for PerRd (usanp)

- hwy_data/PA/usaus/pa.us219.wpt
- hwy_data/PA/usausb/pa.us219busmey.wpt
at-grade jct -> full interchange
> PA US219BusMey N terminus reconfig 

- hwy_data/PA/usapa/pa.pa023.wpt
http://tm.teresco.org/forum/index.php?topic=2124
> PA23 Minor Point Errors east of Lancaster

- hwy_data/CA/usaca/ca.ca012.wpt
- hwy_data/CA/usaca/ca.ca162oro.wpt
Fixes label error in CA12 file. Also fixes broken concurrency between CA99 and CA162Oro.
> usaca fixes

- hwy_data/_systems/cantch_con.csv
http://tm.teresco.org/forum/index.php?topic=130
> cantch_con.csv: fix 3-pronged "(Main)" route

- hwy_data/MN/usamn/mn.mn060.wpt
- hwy_data/MN/usaus/mn.us059.wpt
Changes needed due to closure of an existing waypoint and realignment of the routes in that same vicinity.
> MN 60/US 59 revision

- hwy_data/AR/usaus/ar.us064.wpt
- hwy_data/AR/usausb/ar.us064busalm.wpt
http://tm.teresco.org/forum/index.php?topic=2112
> AR 162 relocation in Alma

- hwy_data/NE/usane/ne.ne066pol.wpt
http://tm.teresco.org/forum/index.php?topic=2191
> NE66Pol: add LacSt

- hwy_data/FL/usafl/fl.fl414.wpt
- hwy_data/FL/usafl/fl.fl429.wpt
Forgot to add this change for the recent extension of FL-429 north of US-441.
Still not 100% on the exit number for the US-441 interchange, however I used what Wikipedia says it is.
> FL: FL-429

- hwy_data/_systems/usaco.csv
Ping @si404
tm.teresco.org/forum/index.php?topic=2129
> usaco.csv: fix overlong Banner datum

- hwy_data/FL/usafl/fl.fl072.wpt
- hwy_data/FL/usafl/fl.fl776.wpt
- hwy_data/FL/usafl/fl.fl9336.wpt
- hwy_data/FL/usanp/fl.mainparkrd.wpt
Fixes mentioned in usafl thread.
> FL updates

- hwy_data/PA/usapa/pa.pa895.wpt
> PA895: resync PA61_N

- hwy_data/NS/cannsf/ns.ns103.wpt
- hwy_data/NS/cannss/ns.ligrte.wpt
- hwy_data/NS/cannst/ns.ns003.wpt
- hwy_data/NS/cannst/ns.ns003liv.wpt
- hwy_data/NS/cannst/ns.ns004ant.wpt
[$17M Ingramport connector now open along Highway 103](http://www.cbc.ca/news/canada/nova-scotia/highway-103-st-margarets-bay-ingramport-connector-1.3953414)
New interchange 5A on NS103.
New roundabout on NS3.
The rest is just cosmetic; more precise point positioning.
> NS coords from 14.0 shapefiles

- hwy_data/TX/usatx/tx.tx359.wpt
- hwy_data/TX/usatxl/tx.lp020.wpt
- hwy_data/TX/usatxs/tx.sp259.wpt
- hwy_data/_systems/usatxs.csv
- hwy_data/_systems/usatxs_con.csv
- updates.csv
http://tm.teresco.org/forum/index.php?topic=2197
> add TXSpr259

- hwy_data/ME/usai/me.i095.wpt
http://www.maine.gov/tools/whatsnew/index.php?topic=DOT_Press_Releases&id=761369&v=article2015
thanks to @ajfroggie for the heads-up.
> ME I-95: add Exit 124

- hwy_data/PA/usapa/pa.pa225.wpt
http://tm.teresco.org/forum/index.php?topic=2208
> PA225: PetMouRd -> ClaBlvd

- hwy_data/FL/usafl/fl.fl228.wpt
- hwy_data/FL/usafl/fl.fl243.wpt
- hwy_data/FL/usafl/fl.fla1a.wpt
- hwy_data/FL/usafl/fl.fla1afer.wpt
Errors brought to my attention in the thread.
> usafl misc fixes

- hwy_data/NY/usany/ny.ny032.wpt
- hwy_data/NY/usany/ny.ny434.wpt
- hwy_data/NY/usany/ny.ny787.wpt
- hwy_data/NY/usaus/ny.us004.wpt
http://tm.teresco.org/forum/index.php?topic=2225
http://tm.teresco.org/forum/index.php?topic=2226
> NY bits from the forum

- hwy_data/QC/canqca/qc.a070.wpt
Short shift and rename of A-70 east endpoint (label not in use), to synch with corresponding point in revised QC 170 file. Also, A-70's *QC170 waypoint => *ToQC170 +QC170.
> QC A-70 tweaks

- hwy_data/_systems/usaus_con.csv
http://tm.teresco.org/forum/index.php?topic=2237
> usaus_con.csv: southern US45 segment groupName

- hwy_data/PA/usapa/pa.pa372.wpt
http://tm.teresco.org/forum/index.php?topic=1935
> PA372: recenter HolRd_E; add FriDr

- hwy_data/ID/usaus/id.us002.wpt
US95/200 was US95_S/200; this caused a datacheck error
> Minor update to id.us002.wpt

- hwy_data/HI/usahi/hi.hi200.wpt
- hwy_data/HI/usahi/hi.hi2000.wpt
HI 200 east end realigned and extended to HI 2000. Routing of new alignment tentative, based on public documents, until OSM/Mapnik catches up.
> HI 200 extension

- hwy_data/NJ/usasf/nj.garstapkwy.wpt
http://tm.teresco.org/forum/index.php?topic=2283
> NJ GarStaPkwy: points & labels from forum

- hwy_data/MA/usama/ma.ma003aply.wpt
http://tm.teresco.org/forum/index.php?topic=2287
> MA3APly: add HanSt_S

- hwy_data/AR/usausb/ar.us412bushun.wpt
This may just be the final pull request for Operation AR Cleanup. :)
> AR US412BusHun: AR23Cit -> HarSt

- hwy_data/CA/usai/ca.i005.wpt
- hwy_data/CA/usai/ca.i008.wpt
- hwy_data/CA/usai/ca.i305.wpt
- hwy_data/CA/usai/ca.i380.wpt
- hwy_data/CA/usai/ca.i405.wpt
- hwy_data/CA/usai/ca.i605.wpt
- hwy_data/CA/usai/ca.i710.wpt
- hwy_data/CA/usai/ca.i980.wpt
- hwy_data/CA/usaib/ca.i005blorl.wpt
- hwy_data/CA/usaib/ca.i008blalp.wpt
- hwy_data/CA/usaib/ca.i008blelc.wpt
- hwy_data/CA/usaib/ca.i205bltra.wpt
- hwy_data/CA/usaus/ca.us095.wpt
- hwy_data/CA/usaus/ca.us101.wpt
- hwy_data/HI/usahi/hi.hi030.wpt
- hwy_data/HI/usahi/hi.hi031.wpt
- hwy_data/HI/usahi/hi.hi380.wpt
- hwy_data/HI/usahi/hi.hi3800.wpt
- hwy_data/SK/cantch/sk.tchmai.wpt
- hwy_data/SK/cantch/sk.tchyel.wpt
- hwy_data/_systems/cannt_con.csv
> CA, HI, SK removal unused alt labels

- hwy_data/AK/usanp/ak.parkrd.wpt
Resynchs Park Rd, in Denali NP, with intersecting AK 3 and I-A4.
> Denali Natl Park NMP fix

- hwy_data/DE/usade/de.de299.wpt
http://tm.teresco.org/forum/index.php?topic=2315.msg8493#msg8493
> DE299: mark OldDE15 as closed

- hwy_data/CA/usaca/ca.ca001.wpt
- hwy_data/CA/usaca/ca.ca019.wpt
- hwy_data/CA/usaca/ca.ca187.wpt
- hwy_data/_systems/usaca.csv
- hwy_data/_systems/usaca_con.csv
Adds back deleted CA 187. Also tweaks CA 1 to fix broken concurrence with I-280, and CA 19.
> usaca tweaks, add back CA 187

- hwy_data/FL/usafl/fl.fl012.wpt
- hwy_data/FL/usafl/fl.fl039.wpt
- hwy_data/FL/usafl/fl.fl039a.wpt
- hwy_data/FL/usafl/fl.fl269.wpt
- hwy_data/FL/usafl/fl.fl574.wpt
- hwy_data/FL/usai/fl.i095.wpt
- hwy_data/FL/usaus/fl.us090.wpt
- hwy_data/FL/usaus/fl.us092.wpt
Fixes for both FL-12 & FL-39/39A reroutes.
http://tm.teresco.org/forum/index.php?topic=323.msg8615#msg8615
> usafl update

- hwy_data/ON/canonf/on.on407.wpt
- hwy_data/ON/canonf/on.on418.wpt
- hwy_data/_systems/canonf.csv
- hwy_data/_systems/canonf_con.csv
- updates.csv
See: http://tm.teresco.org/forum/index.php?topic=2329.0
Even though ON-418 isn't posted yet, we do know it will be.  This prevents any future problems with list files by just adding the small segment now south of the 407 and not adding it as part of 407 itself.
> ON: New ON-418 & extension of ON-407

- hwy_data/AK/usaak/ak.ak010.wpt
- hwy_data/CA/usaca/ca.ca185.wpt
- hwy_data/CA/usaca/ca.ca238.wpt
- hwy_data/DE/usade/de.de016.wpt
- hwy_data/MD/usamd/md.md851.wpt
- hwy_data/_systems/usamd.csv
- hwy_data/_systems/usamd_con.csv
Per forum discussions, adds MD 851, and extends DE 16 east to Broadkill Beach. Some minor preview system (usaak and usaca) tweaks come along for the ride.
Updates items for DE and MD changes to be added directly to GitHub master.
> DE, MD updates

- hwy_data/CA/usaca/ca.ca019.wpt
- hwy_data/CA/usaus/ca.us101.wpt
Minor tweaks to active US 101 route file, per forum discussion, and preview CA 19 route file.
> Minor CA updates

- hwy_data/MD/usamd/md.md213.wpt
> MD213: add ClaShopRd

- hwy_data/MB/canmb/mb.mb010.wpt
- hwy_data/MB/canmb/mb.mb014.wpt
- hwy_data/MB/canmb/mb.mb083.wpt
no more pull requests planned before tonight's site update
> canmb label fixes

- hwy_data/SK/canab/sk.ab017san.wpt
[On the forum](http://tm.teresco.org/forum/index.php?topic=2169.msg8749#msg8749), I wrote:
> Can't forget sk.ab017san.wpt.
...Disproven by counterexample -- I forgot it. :D
> SK AB17San: TwpRd515A -> TR515A

- hwy_data/NV/usanv/nv.nv529.wpt
SR529 - Carson St. - RMID #114 - S-N
Jct of US50/US395/SR529 to the south R/W line of Fairview Dr.
> Create NV 529.

- hwy_data/MD/usamd/md.md026.wpt
- hwy_data/MD/usaus/md.us015.wpt
http://tm.teresco.org/forum/index.php?topic=2351
> MD26: add MonBlvd

- hwy_data/AK/usaak/ak.ak010cor.wpt
- hwy_data/CA/usaca/ca.ca078.wpt
- hwy_data/MD/usamd/md.md185.wpt
- hwy_data/MD/usamd/md.md191.wpt
Includes new waypoint in MD 185 route file discussed on the forum.
> Misc AK. CA, MD updates

- hwy_data/AB/canab/ab.ab043.wpt
along with #1865, this should resync AB43 with BC2 at the border.
> AB43: resync BC/AB

- hwy_data/TX/usatx/tx.tx136.wpt
http://tm.teresco.org/forum/index.php?topic=2374
> TX136: add CasJohRd

- hwy_data/SK/cansk/sk.sk135.wpt
- hwy_data/SK/cansk/sk.sk204.wpt
Tentatively truncates SK 135 as noted in the forum. SK 204 fixed to eliminate the only remaining non-FP NMP in the province.
> A little more cansk

- hwy_data/SK/cansk/sk.sk018.wpt
- hwy_data/SK/cansk/sk.sk165.wpt
- hwy_data/SK/cansk/sk.sk310.wpt
Fixes waypoint errors in SK 18, SK 165, SK 310.
> Minor cansk file fixes

- hwy_data/DE/usade/de.de273.wpt
- updates.csv
http://tm.teresco.org/forum/index.php?topic=2313.msg8472#msg8472
> DE273 truncated, 6thSt -> DE9/141

- hwy_data/SK/cansk/sk.sk202.wpt
Fixes mis-label at west end of SK 202, in a file updated just before I went on a two-week road trip.
> cansk Datacheck error fix

- hwy_data/PA/usapa/pa.pa026.wpt
http://tm.teresco.org/forum/index.php?topic=2400
> PA26: US322BusAth +-> US322Bus

- hwy_data/PA/usapa/pa.pa088.wpt
Connection to a nearby parallel expressway
> PA88: add CoyCurRd

- hwy_data/MA/usama/ma.ma001asal.wpt
- hwy_data/MA/usama/ma.ma022.wpt
- hwy_data/MA/usama/ma.ma062.wpt
- hwy_data/MA/usama/ma.ma127.wpt
http://tm.teresco.org/forum/index.php?topic=2432
> Beverly MA fixes & tweaks

- hwy_data/CA/usaca/ca.ca001.wpt
- hwy_data/CA/usaca/ca.ca060.wpt
- hwy_data/CA/usaca/ca.ca099.wpt
- hwy_data/CA/usaca/ca.ca135.wpt
- hwy_data/HI/usahi/hi.hi030.wpt
- hwy_data/HI/usahi/hi.hi3000.wpt
Changes to HI 30 and HI 3000 from Lahaina Bypass extension (updates table edits to be done separately). Also some tweaks to usaca files, discussed on the forum.
> usaca and usahi updates

- hwy_data/NY/usany/ny.ny035.wpt
http://tm.teresco.org/forum/index.php?topic=2473
> NY35: US9_S +-> US9

- hwy_data/NJ/usai/nj.i195.wpt
Just received confirmation that this change has been made in the field.
This should complete the NJ changes for http://forum.travelmapping.net/index.php?topic=2321
> NJ I-195: Exit 1 renumbering

- hwy_data/SK/cansk/sk.sk031.wpt
- hwy_data/SK/cansk/sk.sk032.wpt
- hwy_data/SK/cansk/sk.sk036.wpt
- hwy_data/SK/cansk/sk.sk037.wpt
- hwy_data/SK/cansk/sk.sk039.wpt
- hwy_data/SK/cansk/sk.sk040.wpt
Simple pull request -- no file renames or csv changes.
> SK 31-40 peer review

- hwy_data/TX/usaus/tx.us084.wpt
> TX US84: resync TX/LA

- hwy_data/NY/usany/ny.ny005.wpt
- hwy_data/NY/usany/ny.ny033.wpt
- updates.csv
> Downtown Buffalo graph reconnections

- hwy_data/PA/usaus/pa.us209.wpt
http://forum.travelmapping.net/index.php?topic=2524
> PA US209: DaiRd -> HemSt

- hwy_data/NJ/usanj/nj.nj439.wpt
http://forum.travelmapping.net/index.php?topic=2523
> NJ439: CR514 @ Lidgerwood Ave

- hwy_data/NJ/usai/nj.i080.wpt
http://forum.travelmapping.net/index.php?topic=2522
> NJ I-80: unnumbered interchanges

- hwy_data/NY/usany/ny.ny085.wpt
- updates.csv
http://forum.travelmapping.net/index.php?topic=2548
> NY85 extended W, CR351 to CR353

- hwy_data/FL/usafl/fl.fl414.wpt
Added newly opened Exit 5 that I spotted in both Google & OSM.
> FL: FL-414 new Exit 5

- hwy_data/PA/usapa/pa.pa029pho.wpt
- hwy_data/PA/usapa/pa.pa100.wpt
http://forum.travelmapping.net/index.php?topic=2566
> PA29Pho & PA100 point label corrections

- hwy_data/MN/usamn/mn.mn040.wpt
- hwy_data/MN/usamn/mn.mn119.wpt
- hwy_data/MN/usamn/mn.mn275.wpt
- hwy_data/MN/usaus/mn.us212.wpt
- hwy_data/_systems/usamn.csv
- hwy_data/_systems/usamn_con.csv
- updates.csv
File changes associated with the extension of MN 119 south to US 212 and the decommissioning of MN 275.
> MN 119 Extension/MN 275 Turnback

- hwy_data/MD/usamd/md.md135.wpt
- hwy_data/MD/usawv/md.wv046elk.wpt
- hwy_data/_systems/usawv.csv
- hwy_data/_systems/usawv_con.csv
- updates.csv
See: http://forum.travelmapping.net/index.php?topic=2574.0
> usawv: Add WV-46 segment in MD

- hwy_data/NM/usanm/nm.nm017.wpt
- hwy_data/SK/cansk/sk.sk044.wpt
- hwy_data/SK/cansk/sk.sk047.wpt
- hwy_data/SK/cansk/sk.sk048.wpt
- hwy_data/SK/cansk/sk.sk049.wpt
> SK 41-49 peer review, NM 17 NMP fix

- hwy_data/SK/cansk/sk.sk027.wpt
- hwy_data/SK/cansk/sk.sk041.wpt
> SK 27 and 41 tweaks

- hwy_data/FL/usafl/fl.fl009bjac.wpt
- hwy_data/FL/usaif/fl.i795futjac.wpt
https://www.news4jax.com/traffic/northbound-lanes-of-state-road-9b-open-in-st-johns-county?__vfz=medium%3Dsharebar
Not sure if the I-95 will now gain an exit number, but I'll cross that bridge once somebody checks out the new alignment.
> usafl: FL-9B new extention to CR2209

- hwy_data/MA/usama/ma.ma003aply.wpt
- hwy_data/RI/usari/ri.ri138.wpt
http://forum.travelmapping.net/index.php?topic=2590
> New England point requests from forum

- hwy_data/KS/usaks/ks.ks030.wpt
http://forum.travelmapping.net/index.php?topic=2573
> KS30: End +-> MapLim

- hwy_data/AL/usaus/al.us011.wpt
- hwy_data/AL/usaus/al.us080.wpt
- hwy_data/MS/usaus/ms.us011.wpt
- hwy_data/MS/usaus/ms.us080.wpt
> MS/AL US 11/80

- hwy_data/RI/usai/ri.i295.wpt
- hwy_data/RI/usari/ri.ri005.wpt
http://forum.travelmapping.net/index.php?topic=2605
> RI: I-295 Exit 10

- hwy_data/PA/usapa/pa.pa050.wpt
- hwy_data/PA/usaus/pa.us040.wpt
http://forum.travelmapping.net/index.php?topic=2608
> PA point fixes from forum

- hwy_data/PA/usausb/pa.us022busmon.wpt
http://forum.travelmapping.net/index.php?topic=2612
> PA US22BusMon: DonDr +-> EntDr

- hwy_data/NV/usai/nv.i011.wpt
- hwy_data/NV/usai/nv.i215.wpt
- hwy_data/NV/usanv/nv.nv582.wpt
- hwy_data/NV/usaus/nv.us095.wpt
> More Boulder City cleanup

- hwy_data/PA/usapa/pa.pa380.wpt
- hwy_data/PA/usaus/pa.us022.wpt
- hwy_data/PA/usaus/pa.us119.wpt
http://forum.travelmapping.net/index.php?topic=2613
http://forum.travelmapping.net/index.php?topic=2616
http://forum.travelmapping.net/index.php?topic=2618
> PA changes from forum

- hwy_data/PA/usapa/pa.pa010.wpt
- hwy_data/PA/usapa/pa.pa077.wpt
- hwy_data/PA/usapa/pa.pa086.wpt
- hwy_data/PA/usapa/pa.pa130.wpt
- hwy_data/PA/usapa/pa.pa295.wpt
- hwy_data/PA/usapa/pa.pa851.wpt
- hwy_data/PA/usaus/pa.us006.wpt
- hwy_data/PA/usaus/pa.us019.wpt
- updates.csv
Removed MinDr and replaced it with Shiloh Rd (ShiRd).
Removed shaping point for HarRd and moved Furnace Rd(Fur Rd) to the correct intersection.
> PA Updates From The Forum

- hwy_data/NY/usany/ny.ny009n.wpt
http://forum.travelmapping.net/index.php?topic=2636
> NY9N: add I-87(22)

- hwy_data/MN/usamn/mn.mn003.wpt
- hwy_data/MN/usamn/mn.mn005.wpt
- hwy_data/MN/usamn/mn.mn013.wpt
- hwy_data/MN/usamn/mn.mn055.wpt
- hwy_data/MN/usamn/mn.mn062.wpt
- hwy_data/MN/usamn/mn.mn110.wpt
- hwy_data/MN/usamn/mn.mn149.wpt
- hwy_data/_systems/usamn.csv
- hwy_data/_systems/usamn_con.csv
- updates.csv
Changes related to the extension of MN 62 east to I-494 in Inver Grove Heights and the subsequent elimination of MN 110.
> MN 62 extension/MN 110 deletion

- hwy_data/PA/usaif/pa.i099futman.wpt
- hwy_data/PA/usapa/pa.pa010.wpt
- hwy_data/PA/usaus/pa.us006.wpt
- hwy_data/PA/usaus/pa.us015.wpt
- hwy_data/PA/usausb/pa.us015busman.wpt
http://forum.travelmapping.net/index.php?topic=2639.0
Also includes replacing LauRd label on PA 10 with regular shaping point and adding PinRd (Pinchtown Rd) point on US 15 south of Williamsport as it briefly was outside tolerance there.
> US 15 BUS NMP and Mansfield Fixes

- regions.csv
- regions_countries_continents.csv
Fixes the following:
* No graph was produced for MEX-EMEX, as no such region was included in regions.csv
* No graph was produced for MEX-E0, as no such directory containing any hwy data existed
* Estado de México was not included in MEX-country.tmg
Tested on my local machine with full siteupdate.py, graphs & everything.
> Estado de México

- hwy_data/CA/usaib/ca.i008blyum.wpt
- hwy_data/NT/cannt/nt.nt010.wpt
- hwy_data/NV/usanv/nv.nv163.wpt
Fixes errors from my last batch of file changes. Also tweaks NT 10 endpoints, using readings from my handheld GPS receiver during last month's field check.
> CA and NV fixes, NT 10 endpoint tweaks

- hwy_data/NY/usany/ny.ny005.wpt
- hwy_data/NY/usausb/ny.us219bussal.wpt
http://forum.travelmapping.net/index.php?topic=2709
http://forum.travelmapping.net/index.php?topic=2710
> WNY fixes from forum

- hwy_data/NJ/usanj/nj.nj029.wpt
- hwy_data/NJ/usaus/nj.us001.wpt
http://forum.travelmapping.net/index.php?topic=2712
> US1 / NJ29 jct

- hwy_data/NY/usany/ny.ny007.wpt
- hwy_data/NY/usany/ny.ny281.wpt
http://forum.travelmapping.net/index.php?topic=2637
While at it, tidied up shaping on NY7 nearby.
> usany points for Interstate interchanges

- hwy_data/NY/usany/ny.ny031.wpt
- hwy_data/NY/usany/ny.ny036.wpt
- hwy_data/NY/usany/ny.ny531.wpt
- updates.csv
http://www.aaroads.com/forum/index.php?topic=14591.msg2235925#msg2235925
> NY 531 Terminus Project

- hwy_data/NJ/usanj/nj.nj124.wpt
http://forum.travelmapping.net/index.php?topic=2744
> NJ124: End +-> Map/Irv

- hwy_data/HI/usahi/hi.hi030.wpt
- hwy_data/HI/usahi/hi.hi200.wpt
- hwy_data/HI/usahi/hi.hi2000.wpt
- hwy_data/HI/usahi/hi.hi3000.wpt
Includes HI 3000 extension, discussed in forum.
> usahi updates

- hwy_data/BC/canbc/bc.bc037.wpt
- hwy_data/YT/canyt/yt.yt001wat.wpt
- hwy_data/YT/canyt/yt.yt006mac.wpt
- hwy_data/YT/canyt/yt.yt037.wpt
Includes one canbc file with a changed border point.
> Yukon NMP fixes

- hwy_data/NY/usany/ny.ny434.wpt
http://forum.travelmapping.net/index.php?topic=2750
> NY434: 1PPI @ NY96

- hwy_data/CA/usaca/ca.ca084.wpt
CA114 => WilRd, now that CA 114 is removed from HB.
> CA 84 label fix

- hwy_data/WA/usasf/wa.airexpy.wpt
- hwy_data/WA/usawa/wa.wa518.wpt
- hwy_data/_systems/usasf.csv
- hwy_data/_systems/usasf_con.csv
As requested in the forum: http://forum.travelmapping.net/index.php?topic=2757.0
> Add SeaTac Airport Expressway

- updates.csv
Forgot to add the updates entry for #2343
> Add updates entry for Airport Expressway

- hwy_data/AL/usaal/al.al027.wpt
- hwy_data/AL/usaal/al.al047trkmon.wpt
- hwy_data/AL/usaal/al.al088.wpt
- hwy_data/AL/usaus/al.us084.wpt
- hwy_data/AL/usaus/al.us431.wpt
> Alabama label corrections

- hwy_data/ME/usame/me.me024busbru.wpt
- hwy_data/ME/usaus/me.us201.wpt
extraneous, essentially part of the US201_N/ME24BusBru_N intersection
> remove Winter St in Topsham ME

- hwy_data/AK/usanp/ak.parkrd.wpt
- hwy_data/SK/cansk/sk.sk055.wpt
- hwy_data/SK/cansk/sk.sk056.wpt
As discussed in usanp and cansk topics on forum.
> AK ParkRd, SK review changes

- hwy_data/PA/usapa/pa.pa981.wpt
Yeah I really should have just marked WhiRd as closed instead.
> PA 981: Marking WhiRd as closed

- regions.csv
> MEX-CAMP -> MEX-CAM

- hwy_data/PA/usapa/pa.pa032alttrkmor.wpt
> PA 32 ALT TRUCK: Fixing Label

- hwy_data/AK/usasf/ak.hicpkwy.wpt
- hwy_data/_systems/usasf.csv
- hwy_data/_systems/usasf_con.csv
As discussed in forum earlier this month.
Includes csv changes. Updates item included in separate pull request.
> AK: Add Hickel Parkway to usasf

- hwy_data/SK/cansk/sk.sk011.wpt
- hwy_data/SK/cansk/sk.sk012.wpt
- hwy_data/SK/cansk/sk.sk305.wpt
Due to new construction near Warman and Martensville SK,
> cansk updates north of Saskatoon

- hwy_data/CA/usanp/ca.genhwy.wpt
- hwy_data/CA/usanp/ca.kincanrd.wpt
- hwy_data/CA/usanp/ca.laspeakhwy.wpt
- hwy_data/CA/usanp/ca.minsumrd.wpt
- hwy_data/CA/usanp/ca.tiopassrd.wpt
- hwy_data/CA/usanp/ca.wawrd.wpt
> usanp California review

- hwy_data/SK/cansk/sk.sk210.wpt
- hwy_data/SK/cansk/sk.sk211.wpt
- hwy_data/SK/cansk/sk.sk219.wpt
- hwy_data/SK/cansk/sk.sk240.wpt
> cansk review through SK271

- hwy_data/UT/usanp/ut.neescedr.wpt
Per forum discussion.
@si404 @Duke87ofST  any comments, etc.?
> UT point additions to Needles Scenic Drive

- hwy_data/DE/usade/de.de273.wpt
This Pull Request seems to be fine unlike my PA one.  This is more of a test to verify what may be up with 2506.
> DE 273: Removing 6thSt as Alt Label

- hwy_data/_systems/usausb.csv
This closes https://github.com/TravelMapping/DataProcessing/issues/170.
Was never done correctly back in #99.
> TX US67BusAvr -> TX US67BusAlv

- hwy_data/NT/cannt/nt.nt008.wpt
CamSt => CarnSt (connection in Inuvik to still-open Aklavik Ice Road)
> NT 8 label fix

- hwy_data/NY/usany/ny.ny173.wpt
http://forum.travelmapping.net/index.php?topic=2917
> NY173: add West Genesee St

- hwy_data/NY/usany/ny.ny173.wpt
Follow-up to #2610
Discussion at http://forum.travelmapping.net/index.php?topic=2917.msg13176#msg13176
> NY173: WestGenSt -> GenSt

- hwy_data/GLP/glpn/glp.n004.wpt
@si404 I'd like to add a point to N4, for the turnoff to the Club Med resort (RueCar) where I stayed more than three decades ago. That would add about four miles to my travels on that route. OK?
> Guadeloupe (French West Indies) point request

- hwy_data/TX/usaib/tx.i010blvan.wpt
- hwy_data/TX/usaus/tx.us090.wpt
- updates.csv
http://forum.travelmapping.net/index.php?topic=2929
> TX US90 extended W, I-10 -> I-10BL

- hwy_data/NY/usany/ny.ny005s.wpt
- hwy_data/NY/usany/ny.ny163.wpt
- updates.csv
http://forum.travelmapping.net/index.php?topic=2942
> END NY163, Fort Plain

- hwy_data/NY/usasf/ny.tacstapkwy.wpt
http://forum.travelmapping.net/index.php?topic=2264
> NY TacStaPkwy exit numbers

- hwy_data/SK/cansk/sk.sk011reg.wpt
- hwy_data/SK/cansk/sk.sk033.wpt
- hwy_data/SK/cansk/sk.sk303.wpt
- hwy_data/SK/cansk/sk.sk310.wpt
- hwy_data/SK/cansk/sk.sk312.wpt
- hwy_data/SK/cansk/sk.sk335.wpt
- hwy_data/SK/cansk/sk.sk343.wpt
- hwy_data/_systems/cansk.csv
- hwy_data/_systems/cansk_con.csv
Not yet tested with datacheck.sh. Will try to do so later today.
> cansk changes

- hwy_data/PA/usapa/pa.pa857.wpt
Added Glendale Church Rd (GleChuRd) and Church St (ChuSt).
> PA 857: Recentering

- hwy_data/PA/usaus/pa.us022.wpt
As noted by PM from @rickmastfan67
> US 22: Added Old William Penn Hwy (OldWPHwy_A)

- hwy_data/WV/usaus/wv.us019.wpt
- hwy_data/WV/usawv/wv.wv310.wpt
- updates.csv
See: http://forum.travelmapping.net/index.php?topic=2553.0
> usawv: WV-310 extension

- hwy_data/SK/cansk/sk.sk376.wpt
- hwy_data/SK/cansk/sk.sk377.wpt
- hwy_data/SK/cansk/sk.sk379.wpt
- hwy_data/_systems/usaak.csv
- hwy_data/_systems/usaak_con.csv
Deletes ak.ak010.chi (Childs Glacier segment), peer review edits to some cansk files. All discussed on forum.
> ovoss-patch-999

- hwy_data/TX/usatx/tx.tx114.wpt
> TX114: add AveH

- hwy_data/NY/usai/ny.i587.wpt
- updates.csv
http://forum.travelmapping.net/index.php?topic=2971
> NY I-587 W end

- hwy_data/FL/usafl/fl.fl009bjac.wpt
- hwy_data/FL/usafl/fl.fl126.wpt
- hwy_data/FL/usafl/fl.fl9336.wpt
- hwy_data/FL/usafl/fl.fl997.wpt
- hwy_data/FL/usafl/fl.fl998.wpt
- hwy_data/FL/usai/fl.i095.wpt
- hwy_data/FL/usaus/fl.us001.wpt
- hwy_data/FL/usausb/fl.us001altjac.wpt
- hwy_data/_systems/usafl.csv
- hwy_data/_systems/usafl_con.csv
Some random cleanups.  No update messages needed, as usafl is still in preview
> usafl minor cleanups

- hwy_data/PA/usapa/pa.pa051.wpt
- hwy_data/PA/usapa/pa.pa065.wpt
Added shaping point to keep line south of PleSt point on PA 18.
> PA 51 and PA 65: Added +X(PA18)

- hwy_data/PA/usapa/pa.pa581.wpt
- hwy_data/PA/usapa/pa.pa944.wpt
- hwy_data/PA/usaus/pa.us011.wpt
- hwy_data/PA/usaus/pa.us015.wpt
US 11: Added +X1, Country Club Rd (CouClubRd),  Schoolhouse Rd (SchRd_E), and +X208.
US 15: Added Country Club Rd (CouClubRd), Schoolhouse Rd (SchRd_E), and +X208.
PA 581: Added +X1.
PA 944: Added Creekview Dr (CreDr).
> US 11, US 15, PA 581, and PA 944 Mapping Changes

- hwy_data/TX/usaus/tx.us069.wpt
concurrent southbound but not northbound
> TX: break US69/75 concurrency

- hwy_data/DE/usade/de.de001.wpt
- hwy_data/DE/usade/de.de014.wpt
- hwy_data/DE/usade/de.de036.wpt
Mainly done due to [opening of DE 14 Interchange](https://deldot.gov/About/news/index.shtml?dc=release&id=7644&q=&exact=&mon=05&yr=2019).
> DE 1 Minor Recentering at DE 14 and DE 36

- hwy_data/FL/usafl/fl.fl010.wpt
Minor fix to a relocation of an intersection for FL-10, & corrected it's label.
> usafl: minor

- hwy_data/MA/usai/ma.i090.wpt
- hwy_data/ME/usame/me.me009.wpt
> I-90: Boston University shaping point

- hwy_data/NY/usany/ny.ny155.wpt
http://forum.travelmapping.net/index.php?topic=3081
> NY155: add DelRd

- hwy_data/DE/usade/de.de896.wpt
http://forum.travelmapping.net/index.php?topic=2922.0
> DE 896: Moving Jamison Corner Rd (JamCorRd)

- hwy_data/MA/usama/ma.ma105.wpt
- hwy_data/MA/usaus/ma.us006.wpt
- updates.csv
http://forum.travelmapping.net/index.php?topic=3092
> MA105 S end correction

- hwy_data/_systems/usaush.csv
- hwy_data/_systems/usaush_con.csv
http://forum.travelmapping.net/index.php?topic=97.msg13982#msg13982
preview system; no updates entry needed
> remove NE US20HisCra

- hwy_data/TX/usatxs/tx.sp380.wpt
- hwy_data/TX/usaus/tx.us090.wpt
- hwy_data/TX/usaus/tx.us175.wpt
- hwy_data/_systems/usausb.csv
- hwy_data/_systems/usausb_con.csv
- updates.csv
http://forum.travelmapping.net/index.php?topic=3068.msg14149#msg14149
http://forum.travelmapping.net/index.php?topic=3068.msg14250#msg14250
> revert unsigned TX/usaus changes

- hwy_data/MA/usai/ma.i093.wpt
- hwy_data/MA/usama/ma.ma028.wpt
- hwy_data/MA/usama/ma.ma038.wpt
- hwy_data/MA/usama/ma.ma099.wpt
- updates.csv
*Visible* waypoints, OTOH... :)
* one interchange
* one to-interchange-on-parallel-route
* one "disambiguation" point
> Boston area points; MA38 Winchester

- hwy_data/NY/usai/ny.i781.wpt
- hwy_data/NY/usany/ny.ny232.wpt
- hwy_data/NY/usaus/ny.us009.wpt
- updates.csv
http://forum.travelmapping.net/index.php?topic=3109
http://forum.travelmapping.net/index.php?topic=3111
> NY fixes from forum

- hwy_data/NM/usanm/nm.nm500.wpt
- hwy_data/NM/usanm/nm.nm501.wpt
- hwy_data/NM/usanm/nm.nm502.wpt
- hwy_data/QC/canqc/qc.qc132.wpt
- hwy_data/QC/canqc/qc.qc243.wpt
- hwy_data/QC/canqca/qc.a010.wpt
- hwy_data/QC/canqca/qc.a015.wpt
- hwy_data/QC/canqca/qc.a020.wpt
> NM and QC edits

- hwy_data/NM/usanm/nm.nm502.wpt
I somehow placed NM 502 west end at wrong intersection with NM 501.
> NM 502 error fix

- hwy_data/NM/usanm/nm.nm500.wpt
- hwy_data/NM/usaush/nm.us066hisalb.wpt
Adds point to both NM 500 and US 66 Historic (Albuquerque), for their intersection just south of I-40.
> NM 500 and US 66 His tweaks

- hwy_data/NY/usany/ny.ny052.wpt
- hwy_data/PA/usapa/pa.pa371.wpt
- hwy_data/PA/usapa/pa.pa652.wpt
- hwy_data/PA/usaus/pa.us006.wpt
Other Changes:
PA 371: Added Galilee Rd (GalRd).
PA 652: Added Bethel School Rd (BetSchRd), Catholic Church Rd (CatChuRd), Peggy Runway Rd (PegRunRd), and +X2A (to keep off river somewhat).
@yakra, I slightly moved the NY 52 PA/NY point.
> PA 652 Recentering

- hwy_data/WA/usawa/wa.wa240busric.wpt
- hwy_data/WA/usawa/wa.wa525.wpt
- hwy_data/_systems/usawa.csv
- hwy_data/_systems/usawa_con.csv
Add WA 240 Business Loop Richland, and make some fixes to WA 525.
> WA updates

- hwy_data/QC/canqc/qc.qc112.wpt
- hwy_data/QC/canqc/qc.qc175.wpt
- hwy_data/QC/canqca/qc.a010.wpt
- hwy_data/QC/canqca/qc.a020.wpt
- hwy_data/QC/canqca/qc.a030.wpt
- hwy_data/QC/canqca/qc.a030bec.wpt
- hwy_data/QC/canqca/qc.a035.wpt
- hwy_data/QC/canqca/qc.a040.wpt
- hwy_data/QC/canqca/qc.a050.wpt
- hwy_data/QC/canqca/qc.a055.wpt
- hwy_data/QC/canqca/qc.a085not.wpt
- hwy_data/QC/canqca/qc.a440equ.wpt
- hwy_data/QC/canqca/qc.a440wqu.wpt
- hwy_data/QC/canqca/qc.a530.wpt
- hwy_data/QC/canqca/qc.a740.wpt
- hwy_data/QC/canqca/qc.a930.wpt
- hwy_data/QC/canqca/qc.a955.wpt
- hwy_data/QC/canqca/qc.a973.wpt
Truncates several Autoroutes. Minor changes such as label and NMP fixes for others. Also label fixes for two other provincial routes.
> Quebec updates

- hwy_data/PA/usapa/pa.pa980.wpt
Made Reissing Rd (ReiRd) and Beech Hollow Rd (BeeHolRd) visible.  Added hidden point for Fort Cherry Rd (FortCheRd) future connection to PA 576.
http://forum.travelmapping.net/index.php?topic=3156.0
> PA 980: Point Changes

- hwy_data/PA/usapa/pa.pa997.wpt
> PA 997: Added Mountain Rd (MouRd_A)

- hwy_data/CA/usaush/ca.us101hissan.wpt
- hwy_data/QC/canqc/qc.qc132.wpt
- hwy_data/QC/canqca/qc.a030bec.wpt
Extension of north end of preview route CA US101HisSan. Truncation of east end of QC A-30Bec. Conforming change to preview route QC QC132. Discussed in forum.
> CA and QC tweaks

- hwy_data/PA/usapa/pa.pa034.wpt
- hwy_data/PA/usapa/pa.pa944.wpt
- hwy_data/PA/usaus/pa.us011.wpt
US 11: Added Middlesex Rd (MidRd).
PA 34: Added Longs Gap Rd (LonGapRd) and Mountain Rd (MouRd_A).
PA 944: Added Longs Gap Rd (LonGapRd), Sheaffer Rd (SheRd), Middlesex Rd (MidRd), and Mountain Rd (MouRd).
> US 11, PA 34, and PA 944 Minor Point Additions

- hwy_data/NY/usany/ny.ny104.wpt
- hwy_data/NY/usanyp/ny.niascepkwy.wpt
http://forum.travelmapping.net/index.php?topic=1928.msg15102#msg15102
> NiaScePkwy demolition, part 1

- hwy_data/_systems/usafl.csv
Fixes issue mentioned in #3107.
> usafl: fix ';' issue

- hwy_data/ON/canon/on.on063.wpt
http://forum.travelmapping.net/index.php?topic=2038.msg15239#msg15239
> on.on063: correct QC border

- updates.csv
In HighwayData pull request #3122. Per forum discussion, no updates items (for now) for SK preview route changes in that PR.
> updates.csv entry for qc.tchkir relocation

- hwy_data/MB/canmb/mb.mb001.wpt
- hwy_data/MB/canmb/mb.mb059.wpt
- hwy_data/MB/canmbw/mb.rt020.wpt
- hwy_data/MB/canmbw/mb.rt030.wpt
- hwy_data/MB/canmbw/mb.rt037.wpt
- hwy_data/MB/canmbw/mb.rt052.wpt
- hwy_data/MB/canmbw/mb.rt085.wpt
- hwy_data/MB/canmbw/mb.rt090.wpt
- hwy_data/MB/canmbw/mb.rt150.wpt
- hwy_data/MB/cantch/mb.tchmai.wpt
http://forum.travelmapping.net/index.php?topic=1846.msg15262#msg15262
> canmbw peer review

- hwy_data/CA/usaca/ca.ca016.wpt
To clear an error picked up in Datacheck.
> CA 16 invalid character fix

- hwy_data/FL/usafl/fl.fl016.wpt
- hwy_data/FL/usafl/fl.fl100.wpt
- hwy_data/FL/usaus/fl.us301.wpt
- hwy_data/FL/usausb/fl.us301altsta.wpt
- hwy_data/_systems/usausb.csv
- hwy_data/_systems/usausb_con.csv
- updates.csv
http://forum.travelmapping.net/index.php?topic=3209.0
> FL: US-301 Alt (Starke)

- hwy_data/QC/cantch/qc.tchmai.wpt
Problem seems to be extra hidden point on concurrent TCH (Main), which this pull removes.
> Fix hidden junction on A-85

- hwy_data/NY/usany/ny.ny009n.wpt
- hwy_data/NY/usany/ny.ny373.wpt
label changed to meet standards
coords from shapefiles
> NY373 endpoint

- hwy_data/ON/cannf/on.allrd.wpt
- hwy_data/ON/cannf/on.donvalpkwy.wpt
- hwy_data/ON/cannf/on.linalepkwy.wpt
- hwy_data/ON/cannf/on.redhillpkwy.wpt
- hwy_data/ON/canon/on.on006.wpt
- hwy_data/ON/canon/on.on006man.wpt
- hwy_data/ON/canonf/on.on401.wpt
- hwy_data/ON/canonf/on.on417.wpt
- hwy_data/ON/canonf/on.ondvp.wpt
- hwy_data/ON/cantch/on.tchott.wpt
Some random updates to Ontario from the forums.
> Ontario updates

- hwy_data/ID/usaid/id.id041.wpt
- hwy_data/ID/usaus/id.us002.wpt
- hwy_data/ID/usaus/id.us030.wpt
- hwy_data/WA/usaus/wa.us002.wpt
Fixing NMP on US 2 at WA/ID border and ID 41 waypoint with US2. http://forum.travelmapping.net/index.php?topic=3217.0
Also doing some waypoint corrections and updates on US 30 in Idaho. http://forum.travelmapping.net/index.php?topic=3215.0
> ID updates and fixes

- hwy_data/WV/usaus/wv.us011.wpt
- hwy_data/WV/usawv/wv.wv051.wpt
- updates.csv
http://forum.travelmapping.net/index.php?topic=3231.0
> WV: WV-51 reroute

- hwy_data/CA/usaca/ca.ca013.wpt
- hwy_data/CA/usaca/ca.ca025.wpt
Added to yesterday's pull requests, which were successfully pulled in after fix of a bad csv file.
> More usaca peer review

- hwy_data/NY/usany/ny.ny005s.wpt
- hwy_data/NY/usany/ny.ny155.wpt
http://forum.travelmapping.net/index.php?topic=3274
http://forum.travelmapping.net/index.php?topic=3271
> NY point additions

- hwy_data/SK/cannf/sk.ringrd.wpt
- hwy_data/SK/cansk/sk.sk001.wpt
- hwy_data/SK/cansk/sk.sk006.wpt
- hwy_data/SK/cansk/sk.sk007.wpt
- hwy_data/SK/cansk/sk.sk011.wpt
- hwy_data/SK/cansk/sk.sk011a.wpt
- hwy_data/SK/cansk/sk.sk011reg.wpt
- hwy_data/SK/cansk/sk.sk033.wpt
- hwy_data/SK/cansk/sk.sk046.wpt
- hwy_data/SK/cansk/sk.sk219.wpt
- hwy_data/_systems/cannf.csv
- hwy_data/_systems/cannf_con.csv
- hwy_data/_systems/cansk.csv
- hwy_data/_systems/cansk_con.csv
Multiple changes in Saskatchewan associated with just-opened Regina Bypass. Also minor point relabels on a few other SK routes.
Datacheck successful. Will create separate pull request for changes to Updates table.
> Regina Bypass and other SK changes

- hwy_data/SK/cantch/sk.tchmai.wpt
For some reason, I didn't include the updated TCHMai route file in my latest pull requests.
> Replace outdated SK TCHMai file

- hwy_data/AB/canab/ab.ab054.wpt
AB2 graph connection
AB590 -> LakDr
> AB54 Innisfail fixes

- hwy_data/MA/usai/ma.i090.wpt
- hwy_data/MA/usai/ma.i093.wpt
- hwy_data/MA/usai/ma.i290.wpt
- hwy_data/MA/usai/ma.i495.wpt
- hwy_data/MA/usama/ma.ma001asal.wpt
- hwy_data/MA/usama/ma.ma003.wpt
- hwy_data/MA/usama/ma.ma122awor.wpt
- hwy_data/MA/usama/ma.ma128.wpt
- hwy_data/MA/usama/ma.ma146.wpt
- hwy_data/MA/usaus/ma.us001.wpt
- hwy_data/RI/usai/ri.i095.wpt
- hwy_data/RI/usari/ri.ri003.wpt
- hwy_data/RI/usari/ri.ri117.wpt
http://forum.travelmapping.net/index.php?topic=3286
http://forum.travelmapping.net/index.php?topic=3291
http://forum.travelmapping.net/index.php?topic=3293
http://forum.travelmapping.net/index.php?topic=3294
http://forum.travelmapping.net/index.php?topic=3296
http://forum.travelmapping.net/index.php?topic=3298
> MA & RI fixes from forum

- hwy_data/MA/usai/ma.i095.wpt
- hwy_data/RI/usai/ri.i095.wpt
- hwy_data/RI/usari/ri.ri146.wpt
http://forum.travelmapping.net/index.php?topic=3287
http://forum.travelmapping.net/index.php?topic=3296.msg16227#msg16227
> More MA & RI fixes from forum

- hwy_data/NJ/usai/nj.i095.wpt
- hwy_data/NJ/usanj/nj.nj027.wpt
- hwy_data/NJ/usanj/nj.nj183.wpt
- hwy_data/NJ/usasf/nj.garstapkwy.wpt
- hwy_data/NJ/usasf/nj.njtpk.wpt
- hwy_data/NJ/usaus/nj.us001.wpt
- hwy_data/NJ/usaus/nj.us009.wpt
- hwy_data/NJ/usaus/nj.us046.wpt
http://forum.travelmapping.net/index.php?topic=3318
http://forum.travelmapping.net/index.php?topic=3319
> NJ fixes from forum

- hwy_data/FL/usafl/fl.fl686.wpt
- hwy_data/FL/usafl/fl.fl688.wpt
- hwy_data/FL/usafl/fl.fl693.wpt
- hwy_data/FL/usafl/fl.fl708.wpt
- hwy_data/FL/usafl/fl.fl710.wpt
- hwy_data/FL/usafl/fl.fl713.wpt
- hwy_data/FL/usafl/fl.fl717.wpt
- hwy_data/FL/usafl/fl.fl739.wpt
- hwy_data/FL/usafl/fl.fl776.wpt
- hwy_data/FL/usafl/fl.fl780.wpt
- hwy_data/FL/usai/fl.i075.wpt
- hwy_data/FL/usausb/fl.us041busfor.wpt
http://forum.travelmapping.net/index.php?topic=323.0
> usafl: forum fixes

- hwy_data/CT/usaus/ct.us006.wpt
> CT US6: Old Rt 6

- hwy_data/ME/usame/me.me007.wpt
Wow. Has this really been wrong the whole darn time? Almost 10 years?
> ME7: ME15/16 +-> ME15

- hwy_data/NY/usany/ny.ny014a.wpt
> NY14A: disambiguate Water St

- hwy_data/_systems/usapa.csv
- hwy_data/_systems/usausb.csv
http://forum.travelmapping.net/index.php?topic=3372.0
These three are currently not in-use by anyone based on searching Github.
> Fixing PA Alternate Route Names

- hwy_data/FL/usai/fl.i095.wpt
- hwy_data/ON/canon/on.on035.wpt
- hwy_data/ON/canon/on.on115.wpt
- hwy_data/ON/canonf/on.on401.wpt
- hwy_data/ON/canonf/on.on407.wpt
- hwy_data/ON/canonf/on.on412.wpt
- hwy_data/ON/canonf/on.on418.wpt
- updates.csv
http://forum.travelmapping.net/index.php?topic=3393.0
Also quickly threw in a new FL I-95 exit that opened (or is just about to open, not sure which, lol) because I just wanted to make sure it got in because not sure when next FL update will be.
> ON: ON-407/418 extensions

- hwy_data/AZ/usaib/az.i017blbla.wpt
- hwy_data/AZ/usaib/az.i040blkin.wpt
These appear to have been unprocessed since the CHM days.
> AZ unprocessed wpts

- hwy_data/CT/usact/ct.ct009.wpt
- hwy_data/CT/usasf/ct.wilbrocon.wpt
- hwy_data/_systems/usasf.csv
- hwy_data/_systems/usasf_con.csv
- updates.csv
http://forum.travelmapping.net/index.php?topic=3424
> Willow Brook Connector

- hwy_data/ROU/eure/rou.e673.wpt
- hwy_data/ROU/roua/rou.a001sib.wpt
- hwy_data/ROU/roudn/rou.dn68a.wpt
- updates.csv
A1 is being extended, Lugoj-Deva L3 is finally open.
> ROU A1 opening

- hwy_data/NJ/usanj/nj.nj003.wpt
http://forum.travelmapping.net/index.php?topic=3432
> NJ3 label fixes from forum

- hwy_data/PA/usapa/pa.pa052alttrktho.wpt
- hwy_data/PA/usapa/pa.pa926alttrktho.wpt
- hwy_data/PA/usaus/pa.us001.wpt
http://forum.travelmapping.net/index.php?topic=3463.0
> Fixing US 1/PA 926 ALT TRUCK/PA 52 ALT TRUCK Broken Concurrency

- hwy_data/GA/usaga/ga.ga045altarl.wpt
- hwy_data/GA/usaga/ga.ga045trkarl.wpt
- hwy_data/GA/usaga/ga.ga062.wpt
- hwy_data/GA/usaga/ga.ga062trkarl.wpt
- hwy_data/GA/usaga/ga.ga111.wpt
- hwy_data/GA/usaga/ga.ga117.wpt
- hwy_data/GA/usaga/ga.ga120.wpt
- hwy_data/GA/usaus/ga.us019.wpt
- hwy_data/GA/usaus/ga.us023.wpt
- hwy_data/GA/usaus/ga.us025.wpt
- hwy_data/GA/usausb/ga.us441bypdub.wpt
> HDX fixes through GA100

- hwy_data/PA/usapa/pa.pa425.wpt
Added Indian Steps Rd (IndSteRd_S and IndSteRd_N), +X0, Shoff Rd (ShoRd), and Chapel Church Rd (ChaChuRd).
> PA 425: Fixed Shaping

- hwy_data/CA/usai/ca.i080.wpt
- hwy_data/NV/usasf/nv.cr215.wpt
- hwy_data/SK/cansk/sk.sk034.wpt
- hwy_data/SK/cansk/sk.sk123.wpt
Synchs NV CR 215 beltway with I-15.
De-synchs SK 34 with MT SR 511, to remove false intersection at long-closed border crossing.
Adds waypoint on long SK 123 segment with no visible points.
Fixes CA I-80(130), to synch with anticipated  US40HisAub edit.
> Misc CA NV SK edits

- hwy_data/PA/usapa/pa.pa100.wpt
- hwy_data/PA/usapa/pa.pa309.wpt
- hwy_data/PA/usapa/pa.pa329.wpt
- hwy_data/PA/usapa/pa.pa873.wpt
PA 100: Added Kernsville Rd (KerRd).
PA 309: Added Orefield Rd (OreRd).
PA 329: Added Coplay Creek Rd (CopCreRd), Old Post Rd (OldPostRd_N), and Church St (ChuSt).
PA 873: Added Old Post Rd.
> Miscellaneous PA 100, PA 309, PA 329, and PA 873 Changes

- hwy_data/ROU/eure/rou.e577.wpt
- hwy_data/ROU/eure/rou.e671.wpt
- hwy_data/ROU/roudj/rou.dj101b.wpt
- hwy_data/ROU/roudj/rou.dj109k.wpt
- hwy_data/ROU/roudj/rou.dj131.wpt
- hwy_data/ROU/roudj/rou.dj571c.wpt
- hwy_data/ROU/roudn/rou.dn73a.wpt
> rou corrections

- hwy_data/NH/usanh/nh.nh121a.wpt
- hwy_data/NH/usanh/nh.nh125.wpt
- updates.csv
http://forum.travelmapping.net/index.php?topic=3515
> NH121A S end

- updates.csv
> Fixed US 62 Updates Entry

- hwy_data/DE/usade/de.de007.wpt
- hwy_data/DE/usade/de.de072.wpt
- hwy_data/DE/usade/de.de273.wpt
- hwy_data/DE/usade/de.de896.wpt
http://forum.travelmapping.net/index.php?topic=3246.0
> DE Pk to Pike Grepped Labels

- hwy_data/WV/usaus/wv.us019.wpt
- hwy_data/WV/usaus/wv.us040.wpt
- hwy_data/WV/usaus/wv.us250.wpt
- hwy_data/WV/usaus/wv.us522.wpt
- hwy_data/WV/usawv/wv.wv004.wpt
- hwy_data/WV/usawv/wv.wv088.wpt
See: http://forum.travelmapping.net/index.php?topic=3526.0 & http://forum.travelmapping.net/index.php?topic=3551.0
> WV forum fixes

- hwy_data/NY/usai/ny.i390.wpt
http://forum.travelmapping.net/index.php?topic=3561
> NY: I-390 issues

- hwy_data/RI/usai/ri.i195.wpt
- hwy_data/RI/usari/ri.ri001apro.wpt
- hwy_data/RI/usari/ri.ri010.wpt
- hwy_data/RI/usari/ri.ri037.wpt
- hwy_data/RI/usaus/ri.us006.wpt
- hwy_data/RI/usaus/ri.us044.wpt
- updates.csv
http://forum.travelmapping.net/index.php?topic=3529
> I-195, RI10, RI37 exit numbers

- graphs/areagraphs.csv
For https://github.com/TravelMapping/DataProcessing/issues/297.
Getting the HighwayData side of this in a bit early for sanity/organizational purposes.
> areagraphs.csv header: place -> title

- hwy_data/NY/usany/ny.ny481.wpt
http://forum.travelmapping.net/index.php?topic=3570
> NY481 exit numbers etc

- hwy_data/PA/usapa/pa.pa050.wpt
Previously missed Pk to Pike Change. (http://forum.travelmapping.net/index.php?topic=3246.0)
> PA 50: WasPk>-WasPike

- hwy_data/PA/usapa/pa.pa670.wpt
http://forum.travelmapping.net/index.php?topic=3246.0
> PA 670: Pk to Pike

- hwy_data/ON/canon/on.on148.wpt
http://forum.travelmapping.net/index.php?topic=2038.msg18353#msg18353
> on.on148: Update ON/QC border + other fixes

- hwy_data/PA/usapa/pa.pa867trkroa.wpt
Created Via: https://github.com/TravelMapping/HighwayData/pull/3798
I am very good at creating broken concurrencies with Truck Routes.
> PA 867 TRUCK: Fixed Broken Concurrency With PA 36/PA 164

- hwy_data/MA/usama/ma.ma088.wpt
- hwy_data/MA/usama/ma.ma114.wpt
- hwy_data/MA/usama/ma.ma125.wpt
- hwy_data/MA/usama/ma.ma133.wpt
- updates.csv
http://forum.travelmapping.net/index.php?topic=3577
http://forum.travelmapping.net/index.php?topic=3578
> MA fixes from forum

- hwy_data/QC/canqc/qc.qc347.wpt
- hwy_data/QC/cantch/qc.tchkir.wpt
- hwy_data/QC/cantch/qc.tchmai.wpt
Fixes NMPs and hidden junction error from last pull request.
> canqc error cleanup

- hwy_data/QC/canqc/qc.qc101.wpt
- hwy_data/QC/canqc/qc.qc116.wpt
- hwy_data/QC/canqc/qc.qc132.wpt
- hwy_data/QC/canqc/qc.qc141.wpt
- hwy_data/QC/canqc/qc.qc157.wpt
- hwy_data/QC/canqc/qc.qc211.wpt
- hwy_data/QC/cantch/qc.tchmai.wpt
Still need to review comments on QC 125, and QC 221-399, to pick up anything I missed.
> canqc tweaks

- hwy_data/PA/usapa/pa.pa073.wpt
- hwy_data/PA/usausb/pa.us322trkdow.wpt
Syncing errors from https://github.com/TravelMapping/HighwayData/pull/3880.
> Fixing PA 73 and US 322 TRUCK (Downingtown)

- hwy_data/NY/usai/ny.i087.wpt
- hwy_data/NY/usai/ny.i287.wpt
- hwy_data/NY/usasf/ny.garstapkwy.wpt
- updates.csv
http://forum.travelmapping.net/index.php?topic=3621
http://forum.travelmapping.net/index.php?topic=3622
> Cuomo Update

- hwy_data/DEU-BY/deub/deuby.b470.wpt
- hwy_data/DEU-BY/deubyst/deuby.st2222.wpt
- hwy_data/DEU-BY/deubyst/deuby.st2253.wpt
- hwy_data/DEU-BY/deubyst/deuby.st2419.wpt
@jteresco please hold on this one until @michihdeu confirms it's ok.
@michihdeu I added a few WPs that I need after my trip to Rothenburg today. Please check if it's ok.
> New WPs in BY

- hwy_data/QC/canqc/qc.qc105.wpt
- hwy_data/QC/canqc/qc.qc138mon.wpt
- hwy_data/QC/canqc/qc.qc236.wpt
- hwy_data/QC/canqc/qc.qc340.wpt
- hwy_data/QC/canqc/qc.qc342.wpt
- hwy_data/QC/canqc/qc.qc344.wpt
- hwy_data/QC/canqc/qc.qc366.wpt
- hwy_data/QC/canqc/qc.qc369.wpt
> canqc review cleanup

- systems.csv
This pull request, and related pull requests 3923 and 3924, activates canqc.
> Update systems.csv for canqc activation

- hwy_data/NY/usany/ny.ny098.wpt
http://forum.travelmapping.net/index.php?topic=3672
> NY98: fix NY16 concurrency

- hwy_data/WV/usawv/wv.wv061.wpt
https://forum.travelmapping.net/index.php?topic=2859.msg19282#msg19282
> wv.wv061: LABEL_INVALID_CHAR fix

- hwy_data/FL/usausb/fl.us221trkper.wpt
> fl.us221trkper: NMP fix

- hwy_data/RI/usari/ri.ri024.wpt
- updates.csv
https://forum.travelmapping.net/index.php?topic=3690
> RI24 Exit Number Conversion

- hwy_data/TX/usai/tx.i045.wpt
- hwy_data/TX/usaus/tx.us175.wpt
- updates.csv
North end removed from S. M. Wright Freeway between TX 310 and I-45 Exit 283, and relocated onto C. F. Hawn Freeway between TX 310 and I-45 Exit 282.
Ping @ajfarina @ajfroggie @ovoss @jteresco
This will require changes to your .list files.
> US175 N end relocation

- hwy_data/TX/usai/tx.i369.wpt
- hwy_data/TX/usaus/tx.us059.wpt
- hwy_data/TX/usaus/tx.us067.wpt
https://forum.travelmapping.net/index.php?topic=3703
> I-369 exit numbers

- hwy_data/FL/usausb/fl.us221trkper.wpt
Add missing point that otherwise broke an overlap with 3 other routes.
> fl.us221trkper: add missing point

- hwy_data/MN/usai/mn.i035.wpt
- hwy_data/MN/usai/mn.i090.wpt
- hwy_data/MN/usamn/mn.mn003.wpt
- hwy_data/MN/usamn/mn.mn005.wpt
- hwy_data/MN/usamn/mn.mn007.wpt
- hwy_data/MN/usamn/mn.mn040.wpt
- hwy_data/MN/usamn/mn.mn062.wpt
- hwy_data/MN/usamn/mn.mn093.wpt
- hwy_data/MN/usamn/mn.mn099.wpt
- hwy_data/MN/usamn/mn.mn101ch2.wpt
- hwy_data/MN/usamn/mn.mn112.wpt
- hwy_data/MN/usamn/mn.mn120.wpt
- hwy_data/MN/usamn/mn.mn197.wpt
- hwy_data/MN/usamn/mn.mn244.wpt
- hwy_data/MN/usamn/mn.mn253.wpt
- hwy_data/MN/usamn/mn.mn254.wpt
- hwy_data/MN/usamn/mn.mn277.wpt
- hwy_data/MN/usaus/mn.us014.wpt
- hwy_data/MN/usaus/mn.us053.wpt
- hwy_data/MN/usaus/mn.us061.wpt
- hwy_data/MN/usaus/mn.us063.wpt
- hwy_data/MN/usaus/mn.us169.wpt
- hwy_data/MN/usaus/mn.us212.wpt
- hwy_data/WI/usaus/wi.us063.wpt
- hwy_data/_systems/usamn.csv
- hwy_data/_systems/usamn_con.csv
- updates.csv
Updates and corrections to several Minnesota lists, including route deletions.  Also includes relocating two points on the WI US 63 file (with Jeff Morrison's approval) that are the result of the Red Wing Eisenhower Bridge project.
> Minnesota Updates - 7/1/20

- hwy_data/MA/usama/ma.ma062.wpt
- hwy_data/MA/usama/ma.ma070.wpt
- updates.csv
https://forum.travelmapping.net/index.php?topic=3492
> MA62 relocation, Clinton

- hwy_data/PA/usapa/pa.pa018.wpt
- hwy_data/PA/usaus/pa.us011.wpt
https://github.com/TravelMapping/HighwayData/pull/4035
> Fixing PA 18 Update from PR# 4035

- hwy_data/NY/usany/ny.ny104.wpt
- hwy_data/NY/usany/ny.ny409.wpt
- hwy_data/NY/usany/ny.ny419.wpt
https://forum.travelmapping.net/index.php?topic=3759
https://forum.travelmapping.net/index.php?topic=3754.msg20046#msg20046
> NY104 & Watkins Glen SP routes

- systemupdates.csv
Canada Select Named Freeways (cannf), promoted to preview for peer review
> cannf devel => preview

- hwy_data/ROU/eure/rou.e574.wpt
- hwy_data/ROU/eure/rou.e671.wpt
- hwy_data/ROU/eure/rou.e85.wpt
- hwy_data/ROU/roua/rou.a003ora.wpt
- hwy_data/ROU/roudj/rou.dj119.wpt
- hwy_data/ROU/roudn/rou.dn002.wpt
- hwy_data/ROU/roudn/rou.dn011.wpt
- hwy_data/ROU/roudn/rou.dn019.wpt
- hwy_data/ROU/roudn/rou.dnvo2t.wpt
- hwy_data/_systems/roua.csv
- hwy_data/_systems/roua_con.csv
- hwy_data/_systems/roudn.csv
- hwy_data/_systems/roudn_con.csv
- updates.csv
@jteresco please wait with this one until @michihdeu confirms it is ok
> ROU A3 and DNVO2T openings

- hwy_data/ROU/eure/rou.e60.wpt
- hwy_data/ROU/roua/rou.a003ier.wpt
- hwy_data/ROU/roudn/rou.dn015.wpt
- hwy_data/ROU/roudn/rou.dn14a.wpt
- updates.csv
A3 opens today between Iernut and Ludus.
> ROU A3 opening

- hwy_data/TX/usatx/tx.tx031.wpt
- hwy_data/TX/usatx/tx.tx031bushub.wpt
- hwy_data/TX/usatx/tx.tx171.wpt
- hwy_data/TX/usatx/tx.tx176.wpt
- hwy_data/TX/usatxf2/tx.fm0700.wpt
- hwy_data/TX/usatxf2/tx.fm0936.wpt
- hwy_data/TX/usatxs/tx.sp0380.wpt
- hwy_data/TX/usaus/tx.us087.wpt
- hwy_data/TX/usaus/tx.us090.wpt
- hwy_data/TX/usausb/tx.us087busbig.wpt
- hwy_data/_systems/usatx.csv
- hwy_data/_systems/usatx_con.csv
- updates.csv
https://forum.travelmapping.net/index.php?topic=2060.msg20442#msg20442
> TX: At Last The 2017 AASHTO

- hwy_data/TX/usatx/tx.tx249.wpt
- hwy_data/TX/usatxf/tx.fm0149.wpt
- hwy_data/TX/usatxf3/tx.fm1488.wpt
- hwy_data/TX/usatxf4/tx.fm1774.wpt
- updates.csv
https://www.navasotaexaminer.com/article/news/aggieland-expressway-opening-first-stretch
https://publicdocs.txdot.gov/minord/MinuteOrderDocLib/115785.pdf
> TX249 Section 1A

- hwy_data/TX/usatx/tx.tx016.wpt
- hwy_data/TX/usatx/tx.tx195.wpt
- hwy_data/TX/usatx/tx.tx207.wpt
- hwy_data/TX/usatx/tx.tx289buspro.wpt
- hwy_data/TX/usatxf/tx.fm0146.wpt
- hwy_data/TX/usatxf/tx.fm0437.wpt
- hwy_data/TX/usatxf/tx.fm0437spr.wpt
- hwy_data/TX/usatxf/tx.fm0487.wpt
- hwy_data/TX/usatxf3/tx.fm1193.wpt
- hwy_data/TX/usatxf4/tx.fm1560.wpt
- hwy_data/_systems/usatx.csv
- hwy_data/_systems/usatx_con.csv
- hwy_data/_systems/usatxf.csv
- hwy_data/_systems/usatxf2_con.csv
- hwy_data/_systems/usatxf_con.csv
- updates.csv
https://forum.travelmapping.net/index.php?topic=3076.msg20445#msg20445
> TxDOT Highway Designations changes 2020-08-19

- updates.csv
@Duke87ofST Please post here clarifying that you have seen this before Jim pulls it in.  Thankfully this is just a typo.
> Fixing MD 327 Update

- hwy_data/AB/canab/ab.ab002.wpt
- hwy_data/AB/canab/ab.ab008.wpt
- hwy_data/AB/canab/ab.ab012.wpt
- hwy_data/AB/canab/ab.ab022x.wpt
- hwy_data/AB/canab/ab.ab040.wpt
- hwy_data/AB/canab/ab.ab043.wpt
- hwy_data/AB/canab/ab.ab043x.wpt
- hwy_data/AB/canab/ab.ab201sca.wpt
- hwy_data/AB/canab/ab.ab201sig.wpt
- hwy_data/AB/canab/ab.ab201woo.wpt
- hwy_data/AB/canabs/ab.ab670.wpt
- hwy_data/_systems/canab.csv
- hwy_data/_systems/canab_con.csv
- updates.csv
Not bothering with adding AB43X as an AltRouteName or adding its AltLabels to AB43, as only @ovoss has traveled AB43X, and presumably will need to edit oscar.list to unclinch the new bypass segments. In any case, I know you stay on top of maintaining your .list file.
> Alberta openings

- hwy_data/NJ/usai/nj.i295.wpt
- hwy_data/NJ/usaus/nj.us030.wpt
https://forum.travelmapping.net/index.php?topic=3823
> I-295/US30 coords

- hwy_data/WV/usaus/wv.us019.wpt
- hwy_data/WV/usausb/wv.us019bypbec.wpt
- hwy_data/WV/usawv/wv.wv016.wpt
- hwy_data/WV/usawv/wv.wv041.wpt
- hwy_data/_systems/usausb.csv
- hwy_data/_systems/usausb_con.csv
- updates.csv
https://forum.travelmapping.net/index.php?topic=3149.0
> WV: US-19 Bypass (Beckley)

- hwy_data/WV/usawv/wv.wv054.wpt
- hwy_data/WV/usawv/wv.wv121.wpt
- updates.csv
https://forum.travelmapping.net/index.php?topic=3790.0
> WV: WV-121 extension

- hwy_data/NY/usai/ny.i084.wpt
- hwy_data/NY/usany/ny.ny017m.wpt
- hwy_data/NY/usany/ny.ny052.wpt
- hwy_data/NY/usany/ny.ny104.wpt
- hwy_data/NY/usanyp/ny.lakeweldr.wpt
- hwy_data/NY/usanyp/ny.niascepkwy.wpt
- hwy_data/NY/usanyp/ny.westrivpkwy.wpt
- hwy_data/NY/usaus/ny.us006.wpt
- hwy_data/NY/usaus/ny.us011.wpt
- hwy_data/_systems/usanyp.csv
- hwy_data/_systems/usanyp_con.csv
- updates.csv
NY I-84: sequential -> milepost
> NY I-84: sequential -> milepost; nix WestRivPkwy

- hwy_data/PA/usaus/pa.us219.wpt
https://forum.travelmapping.net/index.php?topic=2954.0
> US 219: Relocated Brick Rd (BriRd) Point

- hwy_data/NY/usany/ny.ny112.wpt
- hwy_data/NY/usany/ny.ny347.wpt
https://forum.travelmapping.net/index.php?topic=3848
https://forum.travelmapping.net/index.php?topic=3849
> NY112 & 347 points

- hwy_data/PA/usaus/pa.us015.wpt
https://forum.travelmapping.net/index.php?topic=3856.0
> US 15: I-81(65)>-I-81

- hwy_data/AB/canab/ab.ab002.wpt
- hwy_data/AB/canab/ab.ab016.wpt
- hwy_data/AB/canab/ab.ab201.wpt
- hwy_data/AB/cantch/ab.tchyel.wpt
https://forum.travelmapping.net/index.php?topic=3857
https://forum.travelmapping.net/index.php?topic=3858
https://forum.travelmapping.net/index.php?topic=3859
> AB exits from forum

- hwy_data/_systems/usausb_con.csv
https://forum.travelmapping.net/index.php?topic=3840.msg20641#msg20641
> US20Bus (South Sioux City, NE) -> US20Bus (Sioux City, IA)

- hwy_data/NY/usai/ny.i099.wpt
- hwy_data/NY/usai/ny.i890.wpt
- hwy_data/NY/usaif/ny.i086futmon.wpt
- hwy_data/NY/usany/ny.ny005.wpt
- hwy_data/NY/usany/ny.ny005s.wpt
- hwy_data/NY/usany/ny.ny005trksch.wpt
- hwy_data/NY/usany/ny.ny016.wpt
- hwy_data/NY/usany/ny.ny017bin.wpt
- hwy_data/NY/usany/ny.ny017c.wpt
- hwy_data/NY/usany/ny.ny017m.wpt
- hwy_data/NY/usany/ny.ny021.wpt
- hwy_data/NY/usany/ny.ny023.wpt
- hwy_data/NY/usany/ny.ny025a.wpt
- hwy_data/NY/usany/ny.ny026.wpt
- hwy_data/NY/usany/ny.ny059.wpt
- hwy_data/NY/usany/ny.ny079.wpt
- hwy_data/NY/usany/ny.ny100.wpt
- hwy_data/NY/usany/ny.ny304.wpt
- hwy_data/NY/usany/ny.ny417.wpt
- hwy_data/NY/usany/ny.ny426.wpt
- hwy_data/NY/usaus/ny.us006.wpt
- hwy_data/NY/usaus/ny.us015.wpt
- hwy_data/NY/usaus/ny.us020.wpt
https://forum.travelmapping.net/index.php?topic=62.msg20712#msg20712
> NY: add/remove exit numbers

- hwy_data/NB/cannbc/nb.nb105.wpt
- hwy_data/NB/cannbl/nb.nb695.wpt
- hwy_data/NS/cannss/ns.glotrl.wpt
https://forum.travelmapping.net/index.php?topic=62.msg20712#msg20712
> extraneous exit numbers (Maritimes)

- hwy_data/ID/usaid/id.id071.wpt
- hwy_data/ID/usaus/id.us095.wpt
- hwy_data/ID/usaus/id.us195.wpt
- hwy_data/ID/usausb/id.us195sprlew.wpt
- hwy_data/WA/usai/wa.i082.wpt
- hwy_data/WA/usai/wa.i090.wpt
- hwy_data/WA/usaus/wa.us101.wpt
- hwy_data/WA/usaus/wa.us195.wpt
- hwy_data/WA/usaus/wa.us395.wpt
- hwy_data/WA/usausb/wa.us195spruni.wpt
- hwy_data/_systems/usausb.csv
- hwy_data/_systems/usausb_con.csv
- updates.csv
Various updates to WA and ID:
-Fixing NMPs at border waypoints
-Removing some unused alt labels
-Renaming waypoint at west end of I-90 (old waypoint kept as alt label)
-Truncating ID 71 at northern end and adding updates entry for this change
> WA and ID updates

- hwy_data/KS/usai/ks.i070.wpt
- hwy_data/KS/usasf/ks.turdia.wpt
- hwy_data/KS/usaus/ks.us024.wpt
- hwy_data/KS/usaus/ks.us040.wpt
- hwy_data/_systems/usasf.csv
- hwy_data/_systems/usasf_con.csv
- updates.csv
With a new diverging diamond in place at I-70, now the Turner Diagonal is *really*...
> Turner Diagonal diverging diamond

- hwy_data/NY/usany/ny.ny036.wpt
- hwy_data/NY/usany/ny.ny070.wpt
- hwy_data/NY/usany/ny.ny107.wpt
@denishanson, this adds `ArkCanRd` to NY70, in case it may be more useful to you than `MorRd`.
> AARoads chat usany tweaks

- hwy_data/MA/usai/ma.i195.wpt
- updates.csv
Relabeled exits from sequential to mileage-based. All numbers changed except for Exit 1.
https://forum.travelmapping.net/index.php?topic=7.new#new
65 out of 78 list files will be broken.
Of those, 24 have updated via GitHub. Ping:
@43054dude @atsiatas @cl994 @dgolub @Duke87ofST @freakwentflier @ajfroggie @axadiver @mrpoodlepants @jjbers @jonfmorse @jweeksiii @warrenkubat @mapcat @ssoworld @neilbert @neroute2 @denishanson @ovoss @pnrrth @jimttesting ;) @mbeller2016 @ua747sp @vdeane
Although, @freakwentflier only updated formulanone.list once, then went back to using email.
@jteresco, if you want to give the rest an update by email, they're:
1 1995hoo aaroads baugh17 bhemphill brendan capn chaddean charliezeb dantheman dcm55343 deathtopumpkins dfilpus dharwood dnthrox dougtone drebbin37 …
> MA I-195 exit renumbering

- hwy_data/QC/canqc/qc.qc169.wpt
- hwy_data/QC/canqc/qc.qc172.wpt
As discussed in forum. Includes conforming changes to QC 172.
> QC 169 bypass in Alma

- hwy_data/MA/usama/ma.ma003.wpt
- hwy_data/MA/usama/ma.ma083.wpt
- hwy_data/MA/usama/ma.ma085.wpt
- hwy_data/MA/usaus/ma.us007.wpt
http://malmeroads.net/mass21c/neexitrenumbering.html#photos
Submitting this partial renumbering now before anyone starts using the `13` or `15` labels.
> MA3 partial exit renumbering as of 2020-12-02

- hwy_data/ROU/eure/rou.e81.wpt
- hwy_data/ROU/eure/rou.e85.wpt
- hwy_data/ROU/roua/rou.a001sib.wpt
- hwy_data/ROU/roua/rou.a007.wpt
- hwy_data/ROU/roua/rou.a010alb.wpt
- hwy_data/ROU/roudn/rou.dn001.wpt
- hwy_data/ROU/roudn/rou.dn002.wpt
- hwy_data/ROU/roudn/rou.dn02f.wpt
- hwy_data/ROU/roudn/rou.dncalb.wpt
- hwy_data/ROU/roudn/rou.dnvo2t.wpt
- hwy_data/_systems/roua.csv
- hwy_data/_systems/roua_con.csv
- updates.csv
@jteresco please hold on this one until @michihdeu confirms it's ok
> ROU A7 & A10 openings

- hwy_data/NY/usaif/ny.i086futmon.wpt
- hwy_data/NY/usany/ny.ny017bin.wpt
- hwy_data/NY/usaus/ny.us006.wpt
https://forum.travelmapping.net/index.php?topic=3850.msg21087#msg21087
> NY17 new exit 125

- hwy_data/NY/usany/ny.ny012.wpt
- hwy_data/NY/usany/ny.ny028.wpt
https://forum.travelmapping.net/index.php?topic=3961
> NY12/28: add MapAve

- hwy_data/QC/canqc/qc.qc108.wpt
- hwy_data/QC/canqc/qc.qc143.wpt
- hwy_data/QC/canqca/qc.a410.wpt
Final extension of A-410 opened yesterday.
Datacheck successful. Updates table item in #4405.
> QC A-410 extension

- hwy_data/FL/usafl/fl.fl010.wpt
- hwy_data/FL/usafl/fl.fl010ajac.wpt
- hwy_data/FL/usafl/fl.fl113.wpt
- hwy_data/FL/usafl/fl.fl115.wpt
- hwy_data/_systems/usafl.csv
- hwy_data/_systems/usafl_con.csv
- updates.csv
https://forum.travelmapping.net/index.php?topic=3996.0
> usafl: FL-10A (Jacksonville) now posted

- hwy_data/GA/usaga/ga.ga038.wpt
- hwy_data/GA/usaga/ga.ga072.wpt
- hwy_data/GA/usaga/ga.ga093.wpt
- hwy_data/GA/usaga/ga.ga111.wpt
- hwy_data/GA/usaus/ga.us001.wpt
- hwy_data/GA/usaus/ga.us023.wpt
- hwy_data/GA/usaus/ga.us084.wpt
Missed changes from the previous GA route updates
> GA route updates

- hwy_data/NJ/usaus/nj.us040.wpt
- hwy_data/NJ/usaus/nj.us322.wpt
https://forum.travelmapping.net/index.php?topic=4010
https://forum.travelmapping.net/index.php?topic=4011
> US40/322 fixes from @Markkos1992 in forum

- hwy_data/NY/usany/ny.ny291.wpt
https://forum.travelmapping.net/index.php?topic=4024
> NY291: +X01 -> ChaRd

- hwy_data/WA/usawa/wa.wa525.wpt
- updates.csv
The new Mukilteo ferry terminal opened a week ago. Updating location of the northern terminus route to reflect that. New ferry terminal is about a 1/2 mile east of the old one, so I figured this counts as a re-routing and would thus require an updates entry.
> WA 525 Updates

- hwy_data/MA/usai/ma.i090.wpt
- hwy_data/MA/usama/ma.ma009.wpt
22->133 and 26->137 were still not confirmed on Bob Malme's photos page, but close enough.
I wanna get I-90 over & done with and move on to the next route.
No .list files broken.
> I-90 phase 2 (E of I-95)

- hwy_data/OK/usai/ok.i040.wpt
- hwy_data/OK/usaok/ok.ok003.wpt
- hwy_data/OK/usasf/ok.kiktpk.wpt
- hwy_data/OK/usaus/ok.us270.wpt
- updates.csv
https://www.aaroads.com/forum/index.php?topic=21959.msg2563354#msg2563354
> OK KikTpk extended S, 138 -> 130

- hwy_data/MA/usama/ma.ma024.wpt
- hwy_data/MA/usama/ma.ma079.wpt
- updates.csv
afarina baugh17 ben114 dantheman dcharlie dfilpus M3200 neroute2 regoarrarr scott_stieglitz ssgtcrusty
afarina ben114 neroute2
@ajfarina @benchase1 @neroute2 
baugh17 dantheman dcharlie dfilpus M3200 regoarrarr scott_stieglitz ssgtcrusty
> MA24 exit renumbering

- hwy_data/PA/usapa/pa.pa926.wpt
Adding points due to minor realignment in area under construction.  This seems to be more of a vertical realignment than a horizontal one, but I still think it is enough to where some people may consider this segment one to reclinch.
https://www.penndot.gov/regionaloffices/district-6/pages/details.aspx?newsid=6354
> PA 320: Added Upper Gulph Rd (UppGulRd) and Arden Rd (ArdRd)

- hwy_data/NY/usausb/ny.us006altgar.wpt
- hwy_data/NY/usausb/ny.us202altgar.wpt
https://forum.travelmapping.net/index.php?topic=4057
> US9 concurrency fix

- hwy_data/MA/usai/ma.i295.wpt
- updates.csv
Exit 2 moved from I-95 to US1.
1995hoo 43054dude atsiatas Beerman bejacob ben114 bhemphill brendan chaddean charliezeb cl94 dantheman dave1693 dcm55343 deathtopumpkins dharwood dlsterner dnthrox dougtone drebbin37 duke87 epzik8 flroads foresthills93 formulanone froggie highway63 htm_duke johninkingwood julmac lakewy17 lkefct mapcat mariethefoxy master_son mikeandkristie myselfalso neilbert new_friends_gr nezinscot okroads oscar osu_lsu ovoss_old pahighways scott_stieglitz ssgtcrusty tbwillie terescoj terminal_moraine valedc03ls vdeane vespertine wadsteckel walkabout44 yakra
43054dude atsiatas Beerman bejacob ben114 cl94 dave1693 dlsterner duke87 formulanone froggie mapcat master_son myselfalso neilbert …
> MA I-295 exit renumbering

- hwy_data/NY/usany/ny.ny107.wpt
- updates.csv
https://forum.travelmapping.net/index.php?topic=4064
> NY107 north end

- hwy_data/WV/usaus/wv.us340.wpt
- hwy_data/WV/usawv/wv.wv051.wpt
- hwy_data/WV/usawv/wv.wv259.wpt
https://forum.travelmapping.net/index.php?topic=3900.0
https://forum.travelmapping.net/index.php?topic=3901.0
https://forum.travelmapping.net/index.php?topic=3902.0
> WV: label corrections

- hwy_data/AR/usaar/ar.ar549bel.wpt
- hwy_data/AR/usaif/ar.i049futbel.wpt
- hwy_data/AR/usaus/ar.us061.wpt
- hwy_data/AR/usaus/ar.us062.wpt
- hwy_data/AR/usaus/ar.us067.wpt
- hwy_data/AR/usaus/ar.us165.wpt
- hwy_data/AR/usaus/ar.us167.wpt
- hwy_data/AR/usaus/ar.us412.wpt
- hwy_data/AR/usausb/ar.us062bussal.wpt
- hwy_data/AR/usausb/ar.us063bushar.wpt
- hwy_data/AR/usausb/ar.us064busaug.wpt
- hwy_data/AR/usausb/ar.us067buswal.wpt
- hwy_data/AR/usausb/ar.us082busmag.wpt
- hwy_data/TX/usatx/tx.tx006.wpt
- hwy_data/_systems/usausb.csv
https://forum.travelmapping.net/index.php?topic=4095
https://forum.travelmapping.net/index.php?topic=4096
> TX/AR points, labels, unused alts

- hwy_data/NB/cannbc/nb.nb102.wpt
- hwy_data/NB/cannbc/nb.nb176.wpt
- hwy_data/NB/cannbl/nb.nb705.wpt
- updates.csv
I hate writing updates entries like these. Indeed, we should [avoid saying "old end", "new end", etc.](https://travelmapping.net/devel/manual/maintenance.php#newsavoid) but something there's just not much in the way of better options. I hope this adequately explains it.
> NeuBraunschweig ferry cleanup

- hwy_data/FL/usafl/fl.fl010.wpt
- hwy_data/FL/usafl/fl.fl470.wpt
- hwy_data/FL/usafl/fl.fl953.wpt
- hwy_data/FL/usasf/fl.fltpk.wpt
- hwy_data/_systems/usafl.csv
- hwy_data/_systems/usafl_con.csv
- updates.csv
Fixes for the following threads:
https://forum.travelmapping.net/index.php?topic=4130.0
https://forum.travelmapping.net/index.php?topic=4026.0
https://forum.travelmapping.net/index.php?topic=4133.0
https://forum.travelmapping.net/index.php?topic=102.0
> usafl updates

- hwy_data/TX/usatxl/tx.lp0111.wpt
- hwy_data/TX/usaus/tx.us183.wpt
https://forum.travelmapping.net/index.php?topic=1808.msg22697#msg22697
> US183 Austin

- hwy_data/TX/usatx/tx.tx121.wpt
> TX121: TelRd -> *CR275

- hwy_data/DE/usade/de.de001.wpt
- hwy_data/DE/usaus/de.us013.wpt
Fixing Mapview line between DE 1 (Exit 119) and DE 1 (Exit 136).  (see https://github.com/TravelMapping/HighwayData/pull/4594)  Of course, I messed up the Mapview here.
Ironically, I was listening to "About You Know" by Miranda Cosgrove as I did this.  I will consider more changes at a later time.
> DE: DE 1 and US 13

- hwy_data/WA/usawa/wa.wa519.wpt
- hwy_data/_systems/usawa.csv
- hwy_data/_systems/usawa_con.csv
- updates.csv
It is now signed again, so I'm re-adding this route.
https://forum.travelmapping.net/index.php?topic=3974.0
> Re-add WA 519

- hwy_data/MA/usai/ma.i084.wpt
- updates.csv
Exit 3 moved from US 20 (now Exit 6) to Mashapaug Rd.
afarina baugh17 klundgren M3200 mr_matt_k trobster
afarina mr_matt_k
@ajfarina @mr-matt-k 
baugh17 klundgren M3200 trobster
> MA I-84 exit renumbering
