TravelMapping/HighwayData

hwy_data/NY/usany/ny.ny100.wpt

Moved southern terminus from NYST Exit 4 to NYST Exit 5.

NY 100 Southern terminus fix.

---

hwy_data/NY/usany/ny.ny205.wpt
updates.csv

Fix for issue in old CHM forum where NY 205's labels for the ends of its concurrency with NY 23 were reversed.

Jteresco ny205 fix 2

---

hwy_data/ME/usame/me.me026.wpt
updates.csv

(USA) Maine ME 26: Truncated between the old southern end at Congress Street and the new end at Cumberland Avenue.

ME26 truncation

---

hwy_data/PA/usausb/pa.us322bussta.wpt

Fixed location for 'US322_W' to re-sync route with mainline US-322 (and I-99/US-220).  Also added in one additional point at the most logical road that connects to I-99 Exit #71.  See: http://clinched.s2.bizhat.com/viewtopic.php?t=2388&mforum=clinched

Minor fix for PA US-322 Business (State College).

---

hwy_data/CA/usaib/ca.i015bllak.wpt
hwy_data/CA/usaib/ca.i015bllke.wpt
hwy_data/_systems/usaib.csv
hwy_data/_systems/usaib_con.csv

Truncate existing BL to CA 74@Lakeshore Dr, and add branch BL on Main
St. between Lakeshore Dr. and I-15
Updates entries:
15-08-13;(USA) California;I-15BL (Lake Elsinore);ca.i15bllak;Truncated north end of route from I-15 exit 77 to CA 74@Lakeshore Dr.
15-08-13;(USA) California;I-15BL (Lake Elsinore - Main St. branch);ca.i15bllke;.New route

Lake Elsinore CA I-15 BL changes

---

hwy_data/QC/canqca/qc.a035.wpt
hwy_data/QC/canqca/qc.a410.wpt
hwy_data/QC/canqca/qc.a730.wpt

This is first phase of my updates to Quebec autoroutes, limited to three routes where the changes do not require .csv changes:
A-35: Extended south to QC 133 near Saint-Sebastien; all existing exits renumbered. Waypoint for former exit 1 moved to new exit 38 (old A-35 segment now folded into QC 133, not signed as an A- route). Old waypoint 18A, hidden -- signed as part of exit 55, too close to treat as separate exit, but point is in use.
A-410: Extended east to rue Belvedere (exit 10). Both halves of split interchange at exit 7 (to ch. Ste-Catharine and rue Dunant) signed as exit 7, but far enough apart to treat as separate exits with rue Dunant given waypoint 7A.
A-730:  A-30 -> 1
Updates text for first two:
15-08-18;(Canada) Quebec;A-35;qc.a035;Extended route south to St-Sebastien, with …

Updates to QC A-35, A-410, A-730

---

hwy_data/ON/canon/on.on028.wpt
hwy_data/ON/canonf/on.on404.wpt

With these updates, this will bring me up-to-date with submissions that I had made to Tim, but didn't get processed on the old CHM website.  From now on, any updates I submit will be 'new' work.
15-08-21;(Canada) Ontario;ON 404;on.on404;Extended northward from the interchange with Green Lane (Exit 53) to Woodbine Avenue (Exit 65).
15-08-21;(Canada) Ontario;ON 28;on.on028;Removed from Peterborough Road 29 just NorthEast of Lakefield, ON, and relocated onto a brand new alignment SouthEast of Peterborough Road 29 between the closed intersection of *OldON28 and the intersection of Peterborough Road 6/Peterborough Road 29 (RR6/29).

Ontario updates

---

hwy_data/WI/usawi/wi.wi035.wpt

Two points in the just-updated WI 35 file were switched. I switched them back. CHM Waypoints editor indicates that removes the Datacheck
errors.

Fixes Datacheck errors in WI 35

---

hwy_data/NJ/usaus/nj.us009.wpt
hwy_data/_systems/usaus.csv

-- usaus .csv file edited to add Bishop, CA as city name for southern US 395 segment (northern segment city name is Susanville, CA, so there is a
city name for both segments); no filename change, so connecting routes csv file is unchanged
-- primary label for NJ US 9 south end changed from DE/NJ to CapeMayFry (matching label for DE US9 north end); old label hidden
No Updates entries needed.

Minor CA and NJ US route changes

---

hwy_data/PA/usai/pa.i076.wpt
hwy_data/PA/usai/pa.i476.wpt
hwy_data/PA/usapa/pa.pa903.wpt

Added the new EZ-Pass ONLY interchange for PA-903 (Exit 87) along I-476.
Also fixed the location for Exit 201 along I-76 as it's been moved slightly to the East from it's original location because of the Turnpike working on widening the area.
No updates needed in the change logs for these fixes.
Also see #87 about the FP's changes that will be needed because of this.

PA: PA Turnpike network tweaks

---

hwy_data/WV/usaus/wv.us048.wpt
hwy_data/WV/usawv/wv.wv093.wpt

@ovoss brought up that I accidentally flipped the county label on US-48's file in #85.  Here's a very quick fix for it.  Also tweaked WV-93's file to match.

WV: Label corrections

---

hwy_data/IL/usail/il.il097.wpt
hwy_data/MO/usamo/mo.mo005.wpt

Fixes for duplicate label and sharp angle Datacheck errors in MO 5 (one of Jeff's updates earlier this weekend) and IL 97 (unchanged from CHM). 
MO 5 changes:: switched two out-of-order waypoints, renamed MO240Bus_E to MO240Bus_W. 
IL 97 changes:: renamed WalSt+ and WalSt to, respectively, WalSt_Spr and WalSt_Kil
None of renamed point labels are in use. No Updates items required.

Datacheck error fixes for IL 97, MO 5

---

hwy_data/NE/usane/ne.ne092.wpt
hwy_data/NE/usaus/ne.us077.wpt

15-09-28;(USA) Nebraska;US 77;ne.us077;Removed from 1st St, Chestnut St, 12th St, and CR 16 and relocated onto the northwestern Wahoo bypass, between NE 92 West and NE 109 South.
15-09-28;(USA) Nebraska;NE 92;ne.ne092;Removed from 1st St, Chestnut St, 12th St, and CR 16 and relocated onto the northwestern Wahoo bypass, between US 77 South and NE 109.

Wahoo bypass

---

hwy_data/PA/usapa/pa.pa035.wpt
hwy_data/PA/usapa/pa.pa333.wpt

http://clinched.s2.bizhat.com/viewtopic.php?t=2278&mforum=clinched
Just finally updating locations for the new PA-35 bridge reroute that was done in Mifflin/Mifflintown.  Tim had already put in a ruff alignment for this reroute.  These changes finally put the route on it's true alignment since OSM (I made the fixes awhile back) was updated to show the proper new alignment.
So, no mentions needed for the update page.

PA: PA-35 tweaks in Mifflin/Mifflintown.

---

hwy_data/SC/usaus/sc.us015.wpt
hwy_data/SC/usaus/sc.us401.wpt
hwy_data/SC/usaus/sc.us521.wpt
hwy_data/SC/usausb/sc.us076bussum.wpt

http://clinched.s2.bizhat.com/viewtopic.php?t=2322&mforum=clinched
Only route that needs a mention in the change log is US-521.
15-09-29;(USA) South Carolina;US 521;sc.us521;Removed from Broad Street (US 76 Business), Calhoun Street (US 401), Lafayette Drive (US 15), & Manning Road in Sumter SC, and relocated to the southwest onto Bultman Drive, Guignard Drive, & Guignard Parkway, between the intersections of Broad Street/Bultman Drive & Manning Road/Guignard Parkway.

SC: US-521 reroute in Sumter, SC.

---

hwy_data/ND/usand/nd.nd200.wpt

Edits omitted from #133 as pointed out by @the-spui-ninja in #127.
Fixes the broken US85 concurrency.

ND200: deleted 23rdSt; added 24thSt & 130thAve

---

hwy_data/QC/canqca/qc.a073stg.wpt

5 km northward extension of A-73's St-Georges segment just opened. Exit number of new interchange with Route Petite-Pierrette not yet known.
There is still a gap in A-73, planned completion in autumn 2016.
Updates item:
2015-11-11;(Canada) Quebec;A-73 (St-Georges);qc.a073stg;Extended north about 5 km to Notre-Dame-des-Pins

Extension of QC A-73 (St-Georges)

---

hwy_data/QC/canqca/qc.a020.wpt

Route extended east from old east end at exit 527, to new exit 543 (Route Drapeau) in Notre-Dame-des-Nieges.
Update entry:
2015-11-12;(Canada) Quebec;A-20;qc.a020;Route extended east to new exit 543 (Route Drapeau) in Notre-Dame-des-Nieges

QC A-20 extension

---

hwy_data/MA/usama/ma.ma079.wpt
hwy_data/MA/usaus/ma.us006.wpt

Following up on #204. Nothing newsworthy.
The MA79/138 concurrency was still broken between I-195 & US6_E.
Added MA MA79 US6_E:
* To fix the broken concurrency.
* Because it was really needed anyway, #BecauseTexas.
Deprecated existing US6 label in favor of US6_W.
On US6, MA138_S +-> MA79/138.

Fall River part 2

---

hwy_data/HI/usahi/hi.hi036.wpt
hwy_data/HI/usahi/hi.hi380.wpt

Short part of HI 380 closed and relocated to tie route into new Airport Access Rd. (access road route signage not yet known). Waypoint for access road added to HI 36 route file.
Update entry (needed only for HI 380):
2015-11-17;(USA) Hawaii;HI 380;hi.hi380;Route relocated from closed Dairy Rd. segment between waypoints AirAccRd and PakSt_N, onto parts of Airport Access Rd. and Pakaula St.

Short HI 380 relocation

---

hwy_data/NY/usai/ny.i790.wpt
hwy_data/NY/usany/ny.ny003.wpt
hwy_data/NY/usany/ny.ny012.wpt
hwy_data/NY/usany/ny.ny012e.wpt
hwy_data/NY/usany/ny.ny012f.wpt
hwy_data/NY/usany/ny.ny026.wpt
hwy_data/NY/usany/ny.ny049.wpt
hwy_data/NY/usany/ny.ny069.wpt
hwy_data/NY/usany/ny.ny283.wpt
hwy_data/NY/usany/ny.ny365.wpt
hwy_data/NY/usaus/ny.us009.wpt
hwy_data/NY/usaus/ny.us011.wpt

Addressing issues #7, #57, #67 & #145.
2015-11-19;(USA) New York;I-790;ny.i790;Truncated at east end from Leland Ave to Genesee St
2015-11-19;(USA) New York;US 9;ny.us009;Truncated at north end from a cul-de-sac/turnaround about 1/3 mile north of the I-87 Exit 43 interchange, to the I-87 Exit 43 interchange
Updates for issues #7 & #67 are all non-newsworthy.

Watertown & other NY issues

---

hwy_data/NM/usaib/nm.i040blgra.wpt
hwy_data/NM/usaus/nm.us064.wpt
hwy_data/NM/usaus/nm.us070.wpt
hwy_data/NM/usausb/nm.us064busfar.wpt
hwy_data/_systems/usausb.csv
hwy_data/_systems/usausb_con.csv

Adds US 64 Business (Farmington), reroutes US 64 in Farmington and US 70 in Lordsburg, and adds NM 547 point to I-40BL (Grants).
Updates entries:
2015-11-20;(USA) New Mexico;US 64 Business (Farmington);nm.us064busfar'Route added
2015-11-20;(USA) New Mexico;US 64;nm.us064;In Farmington, route moved from Main St. and Broadway St. (now US 64 Business), south to Murray Dr.
2015-11-20;(USA) New Mexico;US 70;nm.us070;In Lordsburg, route moved from I-10 between exits 22 and 24, and Main St. (NM 494), north to Motel Dr. (I-10BL)

NM US and I- BL routes updates

---

hwy_data/ON/cannf/on.ecrowexpy.wpt
hwy_data/ON/canonf/on.on401.wpt

Final extension till the new International Bridge is built for ON-401 has been opened on Nov. 21st, 2015.
Update log info:
2015-11-29;(Canada) Ontario;ON401;on.on401;Extended westward from the former ending interchange with ON 3 (Exit 5) along a newly built freeway to an interchange with Ojibway Parkway (Exit 1).

ON: ON-401 final extension

---

hwy_data/WV/usaus/wv.us048.wpt
hwy_data/WV/usawv/wv.wv009.wpt
hwy_data/WV/usawv/wv.wv051.wpt
hwy_data/WV/usawv/wv.wv093.wpt
hwy_data/WV/usawv/wv.wv115.wpt
hwy_data/WV/usawv/wv.wv480.wpt

US-48/WV-93: http://clinched.s2.bizhat.com/viewtopic.php?p=16704&mforum=clinched#16704
WV-115: http://clinched.s2.bizhat.com/viewtopic.php?p=16702&mforum=clinched#16702
Update log info:
2015-11-29;(USA) West Virginia;US 48;wv.us048;Extended west from the County Line of Grant and Tucker (CR90/1) to the now closed temporary alignment of WV 93 (WV93_Tuc) along a newly built 4-lane highway.
2015-11-29;(USA) West Virginia;WV 93;wv.wv093;Relocated route near Bismarck from the now abandoned old road and slightly to the south onto a brand new 4-lane US 48 Corridor H alignment between an intersection with CR 90/1 and the now closed alignment of WV 93 (*OldWV93_W).
2015-11-29;(USA) West Virginia;WV 115;wv.wv115;Extended northward from the intersection with CR 9/1 (Currie Road) along War Admiral …

WV: US-48 (Corridor H) & WV-115 updates

---

hwy_data/SC/usausb/sc.us521consum.wpt
hwy_data/_systems/usausb.csv
hwy_data/_systems/usausb_con.csv

This route should have been deleted at the same time when I rerouted US-521 in Sumter, SC along the 'connector's' former route.  This pull request fixes that problem.
2016-01-01;(USA) South Carolina;US 521 Connector (Sumter);;Route deleted

SC: US-521 Connector removal in Sumter, SC.

---

hwy_data/NY/usai/ny.i287.wpt
hwy_data/NY/usany/ny.ny127.wpt

2016-01-02;(USA) New York;I-287;ny.i287;Moved Exit 7 from Bloomingdale Rd (now labeled 8W) to Central Westchester Parkway.

White Plains NY cleanup

---

hwy_data/OK/usaok/ok.ok006.wpt
hwy_data/OK/usaok/ok.ok044.wpt
hwy_data/OK/usaus/ok.us283.wpt

addresses #271:
2016-01-04;(USA) Oklahoma;US 283;ok.us283;Removed from a two-lane north-south roadway and E 1490 between a point (labeled OldUS283) near the Jackson/Greer county line and the OK 6 north split, and relocated onto a divided four-lane diagonal directly between these two points.
2016-01-04;(USA) Oklahoma;OK 6;ok.ok006;Removed from N 2020 Rd, E 1340 Rd and a closed two-lane roadway and relocated onto a divided four-lane diagonal between N 2020 Rd and the closed intersection with Old OK 6.

OK US283 / OK6 / OK44

---

hwy_data/CA/usaus/ca.us050.wpt

Renames two waypoints, not in use, with duplicate labels.
Remaining new Datacheck error in just-updated CA US route files (sharp angle in US050AltPol) is false positive, to be crossed off later.

CA US 50 error fix

---

hwy_data/KY/usaky/ky.ky0016.wpt
hwy_data/KY/usaky/ky.ky0680.wpt
hwy_data/KY/usaky/ky.ky0979.wpt
hwy_data/KY/usaus/ky.us060.wpt
hwy_data/KY/usaus/ky.us062.wpt

2016-01-06;(USA) Kentucky;US 60;ky.us060;Removed from the old demolished Ledbetter Bridge and KY 6074, and relocated onto the new Ledbetter Bridge about 1/2 mile southeast, between US 62 in Reidland and KY 6074.
2016-01-06;(USA) Kentucky;KY 16;ky.ky0016;Removed from KY 3716 and relocated onto Pride Pkwy between the southern and northern KY 3716 intersections.

Old forum issues part 3

---

hwy_data/WV/usaus/wv.us035.wpt
hwy_data/WV/usaus/wv.us052.wpt
hwy_data/WV/usawv/wv.wv044.wpt
hwy_data/WV/usawv/wv.wv065.wpt
hwy_data/WV/usawv/wv.wv817.wpt

Extension of WV-44 down to just South of the King Coal Highway till WV gets their act together and only has one posted route for US-52 in that area.  Also a small extension of WV-817 along US-35.
2016-01-30;(USA) West Virginia;WV 44;wv.wv044;Extended southward from it's former southern end at US 52 down to just south of the intersection with the King Coal Highway at Beech Creek Road.
2016-01-30;(USA) West Virginia;WV 817;wv.wv817;Extended westward along US 35 near Henderson from the old western end at US 35 (US35_HenS) to an intersection with Old US 35 (US35_HenN).

Some WV fixes

---

hwy_data/KY/usaky3/ky.ky1020.wpt
hwy_data/OH/usaoh/oh.oh093.wpt
hwy_data/OH/usaus/oh.us035.wpt
hwy_data/OH/usausb/oh.us035busjac.wpt

Newsworthy:
2016-02-01;(USA) Ohio;US 35 Business (Jackson);oh.us035busjac;Removed from Morton St between Chillicothe St and US-35, and relocated onto Chillicothe St and Chillicothe Pike between Morton St and US 35

Ohio & Kentucky

---

hwy_data/TN/usaus/tn.us064.wpt
hwy_data/TN/usausb/tn.us064buswhi.wpt
hwy_data/_systems/usausb.csv
hwy_data/_systems/usausb_con.csv

This is just part 1.  I decided not to wait till I had finished the route (might take a few days) since I noticed there are _several_ realignments for it that I've missed, & that sticking them all in one update entry log would be completely overkill (I think there's 4+ more than the one mentioned below) and confusing to the end user.  Plus I discovered a missing posted Business route for US-64, and wanted to get it online quickly as well.
Even better news? Eliminates 2 datacheck errors automatically. :)
Update log info:
2016-02-14;(USA) Tennessee;US 64;tn.us064;Removed from old two-lane through Hornsby (now Mitchell Street & Main Street), and moved onto a new 4-lane alignment to the south between the intersections with Mitchell Street (MitSt) & Main Street (MainSt).
2016-02-14;(USA) …

TN: US-64 overhaul P1

---

hwy_data/NC/usanc/nc.nc042.wpt
hwy_data/NC/usanc/nc.nc078.wpt
hwy_data/NC/usanc/nc.nc087.wpt
hwy_data/NC/usanc/nc.nc087bypsan
hwy_data/NC/usanc/nc.nc211.wpt
hwy_data/NC/usaus/nc.us001.wpt
hwy_data/NC/usaus/nc.us015.wpt
hwy_data/NC/usaus/nc.us421.wpt
hwy_data/NC/usaus/nc.us501.wpt
hwy_data/NC/usausb/nc.us001bussan.wpt
hwy_data/NC/usausb/nc.us421bussan
hwy_data/_systems/usanc.csv
hwy_data/_systems/usanc_con.csv
hwy_data/_systems/usausb.csv
hwy_data/_systems/usausb_con.csv

Newsworthy
2016-02-18;(USA) North Carolina;US 421 Bus Sanford;nc.us421bussan;New route
2016-02-18;(USA) North Carolina;US 421;nc.us421;Removed from Boone Trail & Horner Blvd through Sanford (now US421 Bus Sanford) between Exit 143 and US421BusSan_N
2016-02-18;(USA) North Carolina;NC 87 Byp Sanford;nc.nc087bypsan;New route

NC changes from mapmikey #2

---

hwy_data/NS/cannsc/ns.ns255.wpt
hwy_data/NS/cannss/ns.martrl.wpt

2016-02-27;(Canada) Nova Scotia;NS 255;ns.ns255;Removed from a closed roadway and demolished bridge, and relocated onto a new parallel roadway and bridge to the east between points labeled *OldNS255_N and *OldNS255_S.
--
Better off merging #453 first, as that contains changes to updates.csv.

NS255: relocation & new bridge

---

hwy_data/ENG/gbna/eng.a1035.wpt
hwy_data/ENG/gbna/eng.a1079.wpt
hwy_data/ENG/gbna/eng.a1174.wpt
hwy_data/ENG/gbna/eng.a134.wpt
hwy_data/ENG/gbna/eng.a1341.wpt
hwy_data/ENG/gbna/eng.a164.wpt
hwy_data/ENG/gbna/eng.a2036.wpt
hwy_data/ENG/gbna/eng.a2100.wpt
hwy_data/ENG/gbna/eng.a269.wpt
hwy_data/ENG/gbna/eng.a2690.wpt
hwy_data/ENG/gbna/eng.a391.wpt
hwy_data/ENG/gbna/eng.a453not.wpt
hwy_data/ENG/gbna/eng.a500.wpt
hwy_data/ENG/gbna/eng.a5020.wpt
hwy_data/ENG/gbna/eng.a589.wpt
hwy_data/REU/reun/reu.n002.wpt
hwy_data/REU/reun/reu.n006.wpt
hwy_data/REU/reun/reu.n102.wpt
hwy_data/SCT/gbna/sct.a082.wpt
hwy_data/SCT/gbna/sct.a085.wpt
hwy_data/SRB/eure/srb.e75bel.wpt
hwy_data/SRB/eure/srb.e761.wpt
hwy_data/_systems/gbna.csv
hwy_data/_systems/gbna_con.csv
hwy_data/_systems/reun.csv
hwy_data/_systems/reun_con.csv

2016-03-09;England;A164;eng.a164;Route removed from Victoria Road and Molescroft Road and relocated onto Minster Way, Swinemoor Lane and Grange Way between Victoria Road (VicRd_N) and the western junction A1035
2016-03-09;England;A589;eng.a589;Route extended at east end from A6 to M6
2016-03-09;England;A1174;eng.a1174;Route truncated at west end from A1035/A1079 to A1035
2016-03-09;England;A1341;eng.a1341;New Route
2016-03-09;England;A2690;eng.a2690;Route extended at east end from B2092 to A2100
2016-03-09;England;A5020;eng.a5020;Route removed from Weston Road and relocated onto David Whitby Way between A500 and A532
2016-03-09;Scotland;A82;sct.a082;Route removed from Glenfalloch Road and relocated onto Crianlarich bypass between Glenfalloch Road and eastern junction with A85

gbna changes

---

hwy_data/NH/usai/nh.i093.wpt
hwy_data/NH/usanh/nh.nh016.wpt
hwy_data/NH/usanh/nh.nh111.wpt
hwy_data/NH/usaus/nh.us004.wpt

2016-03-17;(USA) New Hampshire;I-93;nh.i093;Northbound roadway relocated approximately 0.2 mi westward immediately parallel to southbound roadway, between a point south of Exit 3 (labeled *OldI-93) and Exit 3. Southbound roadway unaffected.
2016-03-17;(USA) New Hampshire;NH 111;nh.nh111;Removed from Enterprise Drive and relocated onto Indian Rock Road between Enterprise Drive and I-93.

Windham NH

---

hwy_data/CA/usaca/ca.ca152.wpt
hwy_data/CA/usaus/ca.us101.wpt

Minor updates to CA US 101 due to freeway conversion of segment at Marin-Sonoma county line. 472A (not in use) relocated to new interchange, SanAntRd_N (in use) marked as closed intersection, and GamRd (not in use) removed.
Tweak to in-dev CA 152 comes along for the ride.

CA US 101 construction-related update

---

hwy_data/MA/usama/ma.ma109.wpt

2016-04-07;(USA) Massachusetts;MA 109;ma.ma109;Extended at east end from I-95 to VFW Pkwy.

MA109 extended E from I-95 to VFW Pkwy

---

hwy_data/BC/canbc/bc.bc023nak.wpt

Tweaks bc.bc023nak route file, to replace a shaping point between HalRd and BC 31, with one better reflecting my travels on the route. I traveled south from the ferry terminal, past the Central Kootenay Regional District line, to a now-closed private road to the old Halcyon Hot Springs -- exiting the highway about a mile north of the HalRd waypoint.
Si, is this OK with you?

CANBC point request

---

hwy_data/DC/usadc/dc.dc295.wpt
hwy_data/DC/usai/dc.i295.wpt
hwy_data/DC/usai/dc.i395.wpt
hwy_data/DC/usai/dc.i695.wpt

Updates to DC I-295, I-395, and I-695, plus conforming changes to DC295. Main changes are to replace named waypoints on I-695 with new exit numbers, and adjusting point locations as needed on that and other freeways.
Edits discussed at (excessive) length at the old CHM forum, at http://clinched.s2.bizhat.com/viewtopic.php?t=2254&mforum=clinched
No items needed for our Updates list, all affected labels in use kept as alternate labels.

DC Interstates updates

---

hwy_data/NY/usany/ny.ny012.wpt
hwy_data/NY/usany/ny.ny012e.wpt
hwy_data/NY/usany/ny.ny012f.wpt
hwy_data/NY/usany/ny.ny022.wpt
hwy_data/NY/usany/ny.ny314.wpt
hwy_data/NY/usany/ny.ny374.wpt
hwy_data/NY/usany/ny.ny456.wpt
hwy_data/NY/usaus/ny.us009.wpt
hwy_data/NY/usaus/ny.us011.wpt
hwy_data/_systems/usany.csv
hwy_data/_systems/usany_con.csv

Addresses #526 & http://tm.teresco.org/forum/index.php?topic=186
--
2016-05-03;(USA) New York;NY 12E;ny.ny012e;Removed from Main St between Bridge St and NY 12, and relocated onto Bridge St between Main St and NY 12F.
2016-05-03;(USA) New York;NY 22;ny.ny022;Truncated at north end from Canadian border to US 11.
2016-05-03;(USA) New York;NY 314;ny.ny314;Truncated at east end from Cumberland Head - Grand Isle Ferry to US9.
2016-05-03;(USA) New York;NY 374;ny.ny374;Truncated at west end from Canadian border to US 11.
2016-05-03;(USA) New York;NY 456;;Route deleted.

NY: various state route changes /  NY North Country Adjustments

---

hwy_data/ME/usame/me.me161.wpt
hwy_data/ME/usame/me.me167.wpt
hwy_data/ME/usausb/me.us001altfor.wpt

2016-05-16;(USA) Maine;ME 161;me.me161;Extended at south end from US 1 Alternate over Main Street and Boundary Line Road (formerly ME 167) to the New Brunswick border.
﻿﻿2016-05-16;(USA) Maine;ME 167;me.me167;Truncated at east end from the New Brunswick border to US 1 Alternate and Fort Fairfield Road. Former segment from the New Brunswick border to US 1 Alternate and ME 161 redesignated as an extension of ME 161.

ME167 truncated & partially redesignated as ME161

---

hwy_data/TX/usaus/tx.us287.wpt
hwy_data/TX/usausb/tx.us287busftw.wpt

2016-05-26;(USA) Texas;US 287 Business (Fort Worth);tx.us287busftw;South end removed from Main Street south of Mouser Way to US 287, and relocated onto FM 157 north of Mouser Way to US 287.

TX US287BusFtW truncation/relocation

---

hwy_data/FL/usafl/fl.fl009bjac.wpt
hwy_data/FL/usai/fl.i010.wpt
hwy_data/FL/usai/fl.i095.wpt
hwy_data/FL/usaif/fl.i795futjac.wpt
hwy_data/FL/usaus/fl.us090.wpt
hwy_data/GA/usai/ga.i085.wpt
hwy_data/GA/usansf/ga.ga400.wpt
hwy_data/GA/usaus/ga.us019.wpt

See following posts:
http://tm.teresco.org/forum/index.php?topic=215.msg1425#msg1425
http://tm.teresco.org/forum/index.php?topic=27.0
http://tm.teresco.org/forum/index.php?topic=122.0
Update entries that are needed:
2016-06-16;(USA) Florida;I-10;fl.i010;Relocated exit 355 0.8 miles to the west to a new interchange with Hammond Boulvard, and relabeled former interchange (now closed) at Greeland Avenue as *355A.
2016-06-16;(USA) Florida;I-795 Future (Jacksonville);fl.i795futjac;Extended at south end from the interchange US 1 down to a new interchange with I-95.

GA/FL Updates

---

hwy_data/GA/usaus/ga.us019.wpt
hwy_data/GA/usausb/ga.us019busdah.wpt

See: http://tm.teresco.org/forum/index.php?topic=216.0
Entries for update log:
2016-06-27;(USA) Georgia;US 19 Business (Dahlonega);ga.us019busdah;Removed from South Chestatee Street and East Main Street between the intersections of South Chestatee Street/US 19/GA 9/GA 52/GA 60 and North Grove Street/East Main Street. Then rerouted along East Main Street between the intersections of North Grove Street/East Main Street and East Main Street/US 19/GA 9/GA 52/GA 60.
2016-06-27;(USA) Georgia;US 19;ga.us019;Moved label 'US19BusDah_S' from intersection with South Chestatee Street (now 'GA9/52') to the north to the intersection with East Main Street (formerly 'GA9/52_S') in Dahlonega.

GA: US-19/19Bus updates around Dahlonega

---

hwy_data/ND/usand/nd.nd1804.wpt
hwy_data/ND/usaus/nd.us002.wpt
hwy_data/ND/usaus/nd.us085.wpt
hwy_data/ND/usausb/nd.us002buswil.wpt
hwy_data/ND/usausb/nd.us002bypwil.wpt
hwy_data/ND/usausb/nd.us085buswil.wpt
hwy_data/ND/usausb/nd.us085bypwil.wpt
hwy_data/_systems/usausb.csv
hwy_data/_systems/usausb_con.csv

Several reroutes in Williston ND area, including US 85 onto western bypass (absorbing former US 2 Byp and US 85 Byp), new US 85 eastern bypass (replacing former US 85 Byp), and lesser reroutes of Bus US2/85 and ND 1804 in downtown Williston. Previously discussed on the TM and AARoads forums.
Updates items:
2016-07-28;(USA) North Dakota;US 85;nd.us085;Relocated from US 2 to new western Williston bypass, between southern US 2 junction and new US 85 Bypass
2016-07-28;(USA) North Dakota;US 2 Bypass (Williston);(NONE): Route deleted (absorbed into US 85)
2016-07-28;(USA) North Dakota;US 85 Bypass (Williston);nd.us085bypwil:Route relocated from western Williston bypass (now part of US 85) to new eastern bypass
2016-07-28;(USA) North Dakota;US 2 Business (Williston);nd.us002buswil;Relocated from …

Williston ND changes

---

chm_final/usausb/al.us331altopp.wpt

Reverts TravelMapping/HighwayData#710
This commit mistakenly removed a file from the chm_final archive instead of hwy_data.

Revert "Delete al.us331altopp.wpt"

---

hwy_data/AR/usaus/ar.us063.wpt
hwy_data/AR/usaus/ar.us067.wpt

2016-08-12;(USA) Arkansas;US 67;ar.us067;Removed from AR 226, AR 367 and US63, and relocated onto a divided freeway between AR 226 and US63.

AR US67: Swifton to Walnut Ridge

---

hwy_data/TN/usaus/tn.us011.wpt
hwy_data/TN/usaus/tn.us070.wpt
hwy_data/TN/usaus/tn.us129.wpt
hwy_data/TN/usaus/tn.us441.wpt

See: http://tm.teresco.org/forum/index.php?topic=361.0
Update log entries: (note, US-129 gets one because of the label location changing for it's interchange with US-11/70)
2016-08-16;(USA) Tennessee;US 11;tn.us011;Removed from Kingston Pike, Cumberland Avenue, US 441, and East 5th Avenue in Knoxville, and rerouted along Neyland Drive (former TN 158) and Hall of Fame Drive between the intersections of Kingston Pike/Neyland Drive and East 5th Avenue/Hall of Fame Drive.
2016-08-16;(USA) Tennessee;US 70;tn.us070;Removed from Kingston Pike, Cumberland Avenue, US 441, and East 5th Avenue in Knoxville, and rerouted along Neyland Drive (former TN 158) and Hall of Fame Drive between the intersections of Kingston Pike/Neyland Drive and East 5th Avenue/Hall of Fame Drive.
2016-08-16;(USA) …

TN: US-11/70 reroute in Knoxville

---

hwy_data/QC/canqca/qc.a020.wpt
hwy_data/QC/canqca/qc.a085not.wpt
hwy_data/QC/cantch/qc.tchmai.wpt

Exit number corrections for A-85Not (32 -> 33), TCHMai (conforming to A-85 change), and A-20 (543 -> 542). Only label in use retained as alternate label.

QC exit number changes

---

hwy_data/QC/canqca/qc.a073.wpt
hwy_data/QC/canqca/qc.a073stg.wpt
hwy_data/_systems/canqca.csv
hwy_data/_systems/canqca_con.csv

Extends main A-73 route south to QC 204 in St-Georges, and deletes A-73 (St-Georges), with today's opening of new connection between those route segments.
Updates items:
2016-09-30;(Canada) Quebec:A-73;qc.a073;Route extended south from exit 61 near Beauceville, to QC 204 in St.-Georges, absorbing former A-73 (St-Georges) segment
2016-09-30;(Canada) Quebec;A-73 (St-Georges);(NONE);Route deleted (folded into rest of A-73)

QC A-73 completion

---

hwy_data/NH/usanh/nh.nh111.wpt
hwy_data/NH/usanh/nh.nh111apel.wpt
hwy_data/NH/usasf/nh.evetpk.wpt

2016-11-02;(USA) New Hampshire;NH 111A (Pelham);nh.nh111apel;Removed from Range Road between a point near the demolished overpass for the former northbound I-93 alignment and NH 111, and relocated onto a new roadway to the west utilizing the former I-93 north and Exit 3 right-of-way.

NH111A relocation, and one more NMP

---

hwy_data/KS/usaks/ks.ks010.wpt
hwy_data/KS/usaus/ks.us059.wpt

2016-11-14;(USA) Kansas;KS 10;ks.ks010;Removed from US 59 and 23rd Street and relocated onto the South Lawrence Trafficway between its US 59 and 23rd Street interchanges.

KS10: South Lawrence Trafficway completion

---

hwy_data/NS/cannsc/ns.ns316.wpt
hwy_data/NS/cannsf/ns.ns103.wpt
hwy_data/NS/cannsf/ns.ns104.wpt
hwy_data/NS/cannss/ns.ligrte.wpt
hwy_data/NS/cannst/ns.ns003liv.wpt
hwy_data/NS/cannst/ns.ns004ant.wpt
hwy_data/NS/cantch/ns.tchmai.wpt

2016-11-19;(Canada) Nova Scotia;NS 103;ns.ns103;Removed from closed two-lane highway and the surface road through Port Mouton village (now partially NS3), and relocated onto the northwestern Port Mouton bypass between closed intersections labeled *OldNS103_Sum & *OldNS103_PMo
2016-11-19;(Canada) Nova Scotia;NS 104;ns.ns104;Removed from a closed temporary connector and NS 4, and relocated onto a parallel four-lane divided highway between closed intersections labeled *OldNS104_Ant & *OldNS104_LSR
2016-11-19;(Canada) Nova Scotia;TCH (Main);ns.tchmai;Removed from a closed temporary connector and NS 4, and relocated onto a parallel four-lane divided highway between closed intersections labeled *OldNS104_Ant & *OldNS104_LSR
2016-11-19;(Canada) Nova Scotia;NS 3 (Liverpool);ns.ns003liv;West end …

NS: Antigonish phase 2 & Port Mouton bypasses

---

hwy_data/_systems/usasf.csv

This is the actual name for the freeway. Note that the "West" is not a directional prefix, but it refers to the West Seattle neighborhood that the freeway serves.

Change "Seattle Freeway" to "West Seattle Bridge"

---

hwy_data/ON/cannf/on.garexpy.wpt
hwy_data/ON/canon/on.on008.wpt
hwy_data/ON/canonf/on.ongar.wpt
updates.csv

Adds in the newly posted exit numbers along the Gardiner Expressway in Toronto, and adds in the missing extension of ON-8 in Kitchener to ON-401.

Minor Ontario fixes

---

hwy_data/ND/usand/nd.nd022.wpt
hwy_data/ND/usand/nd.nd022buskil.wpt
hwy_data/ND/usand/nd.nd200.wpt
hwy_data/_systems/usand.csv
hwy_data/_systems/usand_con.csv

Changes from relocation of ND22 to new pypass, and conversion of old alignment to new ND 22 business route.
Updates items:
2017-02-24;(USA) North Dakota;ND 22;nd.nd022;Relocated from former route through Killdeer (now ND 22 Business) west to new Killdeer Bypass
2017-02-24;(USA) North Dakota;ND 22 Business (Killdeer);nd.nd022buskil;New route

ND - Killdeer Bypass changes

---

hwy_data/ND/usand/nd.nd200.wpt

In ND200 route file, corrects one waypoint label from ND22.22Bus to ND22/22Bus.

ND 200 typo fix

---

hwy_data/HI/usahi/hi.hi036a.wpt
hwy_data/HI/usahi/hi.hi380.wpt
hwy_data/HI/usahi/hi.hi3800.wpt
hwy_data/_systems/usahi.csv
hwy_data/_systems/usahi_con.csv

Adds HI 3800, and makes minor conforming changes to related routes HI 36A and 380.
Updates item:  
2017-03-03;(USA) Hawaii;HI 3800;hi.hi3800;Route added
03;

HI 3800 addition

---

hwy_data/WA/usawa/wa.wa099.wpt

The AtlSt waypoint effectively replaces the 1stAve one. 
http://tm.teresco.org/forum/index.php?topic=1966.msg5528#msg5528

WA 99: Adding AtlSt waypoint, removing 1stAve waypoint

---

hwy_data/WA/usawa/wa.wa009sprsum.wpt

Fixing location of WA/BC waypoint. Apparently, the border isn't quite at a latitude of 49 degrees.

Fixing WA 9 Spur (Sumas)

---

hwy_data/NY/usai/ny.i086.wpt
hwy_data/NY/usai/ny.i090.wpt
hwy_data/NY/usany/ny.ny017.wpt
hwy_data/OH/usai/oh.i090.wpt
hwy_data/PA/usai/pa.i079.wpt
hwy_data/PA/usai/pa.i090.wpt
hwy_data/PA/usapa/pa.pa008.wpt
hwy_data/PA/usapa/pa.pa018.wpt
hwy_data/PA/usapa/pa.pa098.wpt
hwy_data/PA/usapa/pa.pa832.wpt
hwy_data/PA/usaus/pa.us019.wpt
hwy_data/PA/usaus/pa.us020.wpt
hwy_data/PA/usaush/pa.us020hisnor.wpt

This should clear all NMP errors that have to deal with I-90 in PA.
Also quickly synced up NY's I-86/NY-17 with PA's I-86, as PA's point seemed to be right on target for the state line.
Not much, but should clear out several lines from the log.

PA: I-90/I-86 nmp

---

hwy_data/AR/usausb/ar.us064busalm.wpt

Label not in use. In the next few weeks, this label will be needed elsewhere in the file due to a [relocation of AR162](http://tm.teresco.org/forum/index.php?topic=2112.new#new). Proactively removing the label now, just to ensure nobody adds it to a .list file in the meantime.

AR US64: temporarily remove AR162 primary label

---

hwy_data/CA/usaca/ca.ca299.wpt

When synching CA 299 to revised CA 3 route file, I spliced CA 3 coordinates in the wrong order. This fix corrects the waypoint order for CA 299.

CA 299 error fix

---

hwy_data/QC/canqca/qc.a070.wpt

Reflects latest eastward A-70 extension.
Updates item:
2017-07-31;(Canada) Quebec;A-70;qc.a070;East end extended from closed intersection *QC170 to new interchange with Ch. de la Grande-Anse

QC A-70 extension

---

hwy_data/WV/usaus/wv.us050rom.wpt
hwy_data/WV/usaus/wv.us220.wpt
hwy_data/WV/usawv/wv.wv093.wpt
hwy_data/WV/usawv/wv.wv972.wpt
hwy_data/_systems/usawv.csv
hwy_data/_systems/usawv_con.csv
updates.csv

http://tm.teresco.org/forum/index.php?topic=2153.0
Now, you might wonder why I didn't add 'WV972' to the 'altlabels' for WV-93.  The reason is because I'm trying to avoid FPs in people's lists, as both routes had the 'US50' label at each end, and I could only 'hide' it in one location, and since WV-972 was absorbed by WV-93, the original location of 'US50' in WV-93's file got the 'hidden' label.

WV: WV-972 absorbed by WV-93

---

hwy_data/MN/usamn/mn.mn036.wpt
hwy_data/MN/usamn/mn.mn095.wpt
hwy_data/WI/usawi/wi.wi035.wpt
hwy_data/WI/usawi/wi.wi064.wpt

Changes needed due to the completion of the new MN 36/WI 64 Stillwater Bridge.

MN 36/WI 64 Stillwater Bridge

---

hwy_data/CA/usaib/ca.i005bldun.wpt
hwy_data/CA/usaus/ca.us101.wpt
hwy_data/CA/usausb/ca.us101buspet.wpt

Three updates of CA routes in active systems:
I-5BLDun extended north one exit, as discussed in the forum
Added new exit 467 to US 101
Re-synched southern end of US101BusPet with US 101
Only first item needs an Updates entry, which I'll add to the Updates table separately.
@si404:  First item affects US99HisDun, as noted in the forum.

CA active routes updates

---

hwy_data/CA/usaus/ca.us101.wpt
hwy_data/QC/canqca/qc.a025.wpt

A-25 extended north from exit 46 to northern QC 125/158 intersection. Missing exit 1E added to US 101 in downtown Los Angeles, and rest of route scrubbed to remove unused alternate waypoint labels.
Update entry for A-25 extension to be added later, directly to Updates table.

QC A-25 extension, CA US 101 updates

---

hwy_data/CA/usaca/ca.ca260.wpt

This is part of an oddball situation in Oakland I'll discuss on the forum. It's clear enough CA 260 should be truncated if it remains in the HB, though what to do with concurrent route CA 61 (including the mileage removed from CA 260, and perhaps absorbing the rest of CA 260) is less clear.

usaca CA 260 truncation

---

hwy_data/SK/cansk/sk.sk056.wpt
hwy_data/SK/cansk/sk.sk202.wpt
hwy_data/SK/cansk/sk.sk364.wpt
hwy_data/_systems/cansk.csv
hwy_data/_systems/cansk_con.csv

Restores SK 364 to HB, fixes duplicate label error in SK 56, and re-adjusts SK 202 endpoint.

cansk cleanup

---

hwy_data/AK/usaak/ak.ak007pet.wpt

Minor changes to route file, mainly to relabel side road to now-defunct Rainforest Islands ferry. Relabeled points are not in use.
With these changes, and completion of yakra's review, usaak is ready to activate (per earlier pull requests, except new system updates table entry needs new date).

AK7Pet tweaks

---

hwy_data/PA/usaus/pa.us019.wpt

Deleting ReyAve as a label due to it not being in use.  I also did the same to US 6.

US 19 Label Change At PA 27

---

hwy_data/ND/usand/nd.nd067.wpt
hwy_data/ND/usaus/nd.us012.wpt

I noticed that ND 67 was a bit off (it goes over the railroad tracks on a bridge at the south end), so the adjustment was made.
If this causes any problems let me know (I figured a small thing would be good for my first HighwayData pull request).
Source: http://mapserver.co.bowman.nd.us/

Adjustment of south endpoint of ND 67

---

updates.csv

I removed (NONE) from a field in three recent Nevada updates items. My guess is the removals were undone by someone editing an old version of updates.csv.

Restore my fixes to recent Nevada entries

---

hwy_data/AL/usaus/al.us031.wpt
hwy_data/AL/usaus/al.us078.wpt
hwy_data/AL/usaus/al.us082.wpt
hwy_data/AL/usaus/al.us084.wpt
hwy_data/AL/usaus/al.us231.wpt

Point label corrections or additions for three newly signed Alabama state routes:  AL 378, AL 382, and AL 605.

AL point fixes for newly designated routes

---

hwy_data/VA/usausb/va.us460busbed.wpt

Showed up in the HB as "US"  and in the WPT Editor as "US +221/122 +IndBlvd". This was intended to be US221/122.
http://forum.travelmapping.net/index.php?topic=2839.0
I'll let Mike know I fixed this via PM on the forum.  -Mark

US 460 BUS (Bedford): Fixing Label Error

---

hwy_data/MD/usai/md.i070.wpt

Per forum discussion, removes I-70 point for long-closed exit 54 (label not in use), and moves its label to current I-70 exit 54 (54A in the HB, label in use and will become alt label). The removal of old *54 point also eliminates an NMP.

MD: I-70 exit changes in Frederick

---

hwy_data/PA/usaus/pa.us006.wpt

Put SprSt in as alternate label for ChuSt.
This was done while looking at the latest User Data list files and realizing that I broke griffith's with last night's Pull Request (https://github.com/TravelMapping/HighwayData/pull/2759).

US 6: Readded SprSt as Alternate Label for ChuSt

---

hwy_data/QC/canqca/qc.a010.wpt
hwy_data/QC/canqca/qc.a055.wpt

Reverts to old coordinates for A-10(123A) and corresponding waypoint for A-55. Needed to break false concurrency with QC 112, which is on frontage road rather than A-10/55 mainline.

Quebec Autoroute tweaks

---

hwy_data/ID/usaid/id.id039.wpt
hwy_data/ID/usaus/id.us020.wpt
hwy_data/ID/usausb/id.us095sprpay.wpt
hwy_data/WA/usawa/wa.wa519.wpt
hwy_data/WA/usawa/wa.wa525.wpt
hwy_data/_systems/usausb.csv
hwy_data/_systems/usausb_con.csv
hwy_data/_systems/usawa.csv
hwy_data/_systems/usawa_con.csv
updates.csv

Updates to WA: remove WA 519 due to lack of signage, remove OldMukSpe +106thSt due to its insignificance and proximity to LinWay waypoint
Updates to ID: Remove US 95 Spur Payette due to lack of signage, add shaping point for US 20 in Rigby, extend ID 39 to I-86.

WA and ID updates 

---

hwy_data/NS/cannsc/ns.ns245.wpt
hwy_data/NS/cannsc/ns.ns337.wpt
hwy_data/NS/cannsf/ns.ns104.wpt
hwy_data/NS/cannss/ns.suntrlant.wpt
hwy_data/NS/cannst/ns.ns004ant.wpt
hwy_data/NS/cannst/ns.ns004hav.wpt
hwy_data/NS/cannst/ns.ns004ngl.wpt
hwy_data/NS/cannst/ns.ns007.wpt
hwy_data/NS/cantch/ns.tchmai.wpt
updates.csv

* **NS4Ant** relocated completely off its original CHM alignment, onto the original (before Phase 1 Antigonish bypass) NS104.
* **NS7** truncated from James St (old NS4) to new NS4.
* **NS245** extended over old NS4 and the vacated segment of NS7, to new NS4.
* **NS337** extended over old NS4 to NS245.
* **NS104/TCHMai** gets tightened up near the old alignment at `*ChuRd`, and receives new Exit 36B.
* **NS4NGl** gets a `*OldNS104` point, for the former transition to/from `NS NS104 *ChuRd`.
* **NS4Hav** receives new `NS104(36B)` point.

NS4 corridor updates

---

hwy_data/CA/usaca/ca.ca111.wpt
hwy_data/CA/usaca/ca.ca111pal.wpt
hwy_data/CA/usai/ca.i010.wpt

Updates flagged in usaca peer review, and discussed in that forum thread.
CA I-10 label error fixes are in exit 110-112 range. No Updates entries needed. 110 and 111 are not in use, and 112 becomes an alternate label for 111.

CA I-10 and CA 111 updates

---

hwy_data/ME/usaus/me.us001.wpt

"Waypoint labels should avoid secret highway designations, i.e., designations travelers will not know about by driving and reading signs."

ME US1: I-495 +-> METpk

---

hwy_data/WI/usawi/wi.wi136.wpt
hwy_data/_systems/usawi.csv

Fixes some broken list lines:
> **bulldog1979.list:** WI WI123 CRDL WI33
**bulldog1979.list:** WI WI159 US12 WI123
**imgoph.list:** WI WI123 CRDL WI159
**imgoph.list:** WI WI159 US12 WI123
**julmac.list:** WI WI123 WI33 CRDI
**keithcavey.list:** WI WI123 CRDL WI159
**keithcavey.list:** WI WI123 WI113_S WI33
**keithcavey.list:** WI WI159 US12 WI123
**sipes23.list:** WI WI123 CRDL WI33
**sipes23.list:** WI WI159 US12 ParkRd
I'd like to get Jeff's approval for this [on the forum](http://forum.travelmapping.net/index.php?topic=3422).

WI136 AltRouteNames

---

hwy_data/PA/usai/pa.i095.wpt
hwy_data/PA/usapa/pa.pa003.wpt
hwy_data/PA/usapa/pa.pa073.wpt
hwy_data/PA/usapa/pa.pa100.wpt
hwy_data/PA/usapa/pa.pa113.wpt
hwy_data/PA/usaus/pa.us030.wpt
hwy_data/PA/usaus/pa.us322.wpt
hwy_data/PA/usausb/pa.us322trkdow.wpt
updates.csv

US 322 TRUCK (Downingtown): Extended to US 322/US 322 Business (West Chester) on the northwest side of West Chester via US 30, PA 100, US 202, Paoli Pike, PA 3, and US 322 Business (West Chester).  Note that the part in West Chester is WB only. (http://forum.travelmapping.net/index.php?topic=2779.0)
Other Changes:
I-95: Added +X02.
US 30: Changed US30BusDow Label to US30BusDow_A.  (see [US460BusChr labels on US 460](http://travelmapping.net/hb/index.php?units=miles&u=markkos1992&r=va.us460) for precendent)
US 322: Added Phoenixville Pike (PhoPk).
PA 3: Added Delchester Rd (DelRd) and Sandy Flash Dr (SanFlaDr).
PA 73: Added Joshua Rd (JosRd) (for Fort Washington State Park) and Castor Ave (CasAve).
PA 100: Added Mountainview Dr (MouDr).

US 322 TRUCK (Downingtown) Extension and Other Misc. PA Changes

---

hwy_data/FL/usaus/fl.us098.wpt

Forgot to remove mention of the now removed US-98 Truck (Brooksville).

fl.us098: forgot to update label

---

hwy_data/_systems/canqc.csv
hwy_data/_systems/canqc_con.csv

In each csv file, Rawson => Rawdon in line for qc.qc125.

canqc csvs typo fix

---

hwy_data/FL/usaus/fl.us090.wpt
hwy_data/FL/usausb/fl.us090altpen.wpt

Since it's back in the GIS, but don't know if it's posted yet.  Went with the old 'CR99' label for now because of that (since that what was posted per StreetView).

FL: Prep work for FL-99 coming back soon

---

hwy_data/NM/usanm/nm.nm028can.wpt

Per forum discussion, flips nm.nm028can waypoint order with no changes to waypoint labels. Also tweaks southern endpoint.

Flip NM28Can

---

hwy_data/PA/usai/pa.i080.wpt
hwy_data/PA/usapa/pa.pa026.wpt
hwy_data/PA/usapa/pa.pa031.wpt
hwy_data/PA/usapa/pa.pa072.wpt
hwy_data/PA/usaus/pa.us220.wpt
hwy_data/PA/usaus/pa.us322.wpt

Done to show realignment for new bridge over East Branch Brandywine Creek. (https://www.penndot.gov/regionaloffices/district-6/pages/details.aspx?newsid=5776)
Other Minor Changes:
PA 26: Added Future Connection to I-80 (Exit 163).
PA 31: Relocating I-70/76 Points.
PA 72: Recentered Rocherty Rd (RocRd).
I-80/US 220: Added Future I-80(Exit 163),

US 322: Added Skelp Level Rd (SkeLevRd)

---

hwy_data/NV/usai/nv.i011.wpt
hwy_data/NV/usaus/nv.us093.wpt
hwy_data/NV/usaus/nv.us095.wpt

Also affects US 93 and US 95. All labels in use kept as alternate labels. No Updates entry needed.
Datacheck.sh successful.

NV I-11 exit renumberings

---

hwy_data/PA/usapa/pa.pa230.wpt
hwy_data/PA/usapa/pa.pa441.wpt
hwy_data/PA/usapa/pa.pa441trkmid.wpt
hwy_data/_systems/usapa.csv
hwy_data/_systems/usapa_con.csv
updates.csv

PA 230: Changes due to PA 441 Realignment.  Also added +X0.
PA 441: Realigned to use former route of PA 441 TRUCK (Middletown) between Union St (UniSt_S) and PA230_E.  (https://forum.travelmapping.net/index.php?topic=3837.0)
Added Governor Stable Rd (GovStaRd), Falmouth Rd (FalRd), Powderhorn Rd (PowRd), and 28th St (28thSt_N).

PA 441 Realignment in Middletown

---

hwy_data/CA/usaca/ca.ca047.wpt
hwy_data/CA/usaca/ca.ca072.wpt
hwy_data/CA/usaca/ca.ca232.wpt
hwy_data/CA/usaca/ca.ca241.wpt
hwy_data/CA/usaca/ca.ca261.wpt
hwy_data/CA/usai/ca.i710.wpt
hwy_data/CA/usaus/ca.us101.wpt

Extends south end of I-710 to CA 47, over replacement for Gerald Desmond Bridge in Long Beach, per forum discussion. Also includes tweaks to other routes, some of them also discussed on forum.
Updates item in separate pull request #4244.

CA I-710 extension, other CA updates

---

hwy_data/ME/usame/me.me025.wpt

https://www.portlandmaine.gov/2286/Deerings-Corner-Roundabout
Brighton Ave east of ME25 appears to be permanently closed.

Deering's Corner Roundabout

---

hwy_data/TX/usasf/tx.intpkwy.wpt
hwy_data/TX/usatxs/tx.sp0097.wpt
hwy_data/_systems/usasf.csv
hwy_data/_systems/usasf_con.csv
hwy_data/_systems/usatxs.csv
updates.csv

Truncating TXSpr97 & replacing with International Pkwy in usasf.
https://forum.travelmapping.net/index.php?topic=3480.msg17905#msg17905
Didn't do the thing where I move all the old past-the-end points to the new terminus as AltLabels, because it seems the better thing to do here is break everybody's list file thereby making them realize something's changed, check out the updates page, and add their entries for `TX IntPkwy`.

truncate TXSpr97, add IntPkwy

---

hwy_data/MA/usama/ma.ma025.wpt
updates.csv

Relabeled exits from sequential to mileage-based. Exit 3 moved from US 6 / MA 28 (now Exit 10) to Maple Springs Rd (former Exit 2).
https://forum.travelmapping.net/index.php?topic=7.new#new
10 out of 49 list files will be broken.
*(This file didn't even use the sequential exit numbers till 2018ish, so a lot of people still use the old `MA28` label, and their .lists aren't broken.)*
Of those, 4 have updated via GitHub. Ping:
@420Traveler @benchase1 @freakwentflier @denishanson
Those who've updated by email:
brendan drebbin37 foresthills93 formulanone M3200 norheim valedc03ls

MA25 exit renumbering

---

hwy_data/MA/usama/ma.ma003.wpt
hwy_data/MA/usama/ma.ma003aply.wpt
updates.csv

This only affects neroute2.list, which was [broken ahead of time](https://github.com/TravelMapping/UserData/pull/4719), so this neither breaks nor fixes it (yet).

MA3 partial exit renumbering as of 2020-12-06

---

hwy_data/NS/cannss/ns.martrl.wpt
hwy_data/_systems/canqca_con.csv

Changes a few **`é`** characters to the standard UTF-8 **`C3 A9`** from **`C3 83 C2 A9`**. Strangely, after passing thru MySQL, PHP, and Apache the result is a normal-looking **`é`** in the HB, that looks like **`Ã©`** in userlogs.
https://community.bmc.com/s/feed/0D53n00007aEKvQCAW
> Viewing a tcpdump trace with Wireshark, we see that the "é" char is transmitted as "C3 83 C2 A9" instead of the simple UTF-8 translation "C3 A9".
>
> "C3 83 C2 A9" in UTF-8 is indeed "Ã©", which is the ANSI for the UTF-8 "é", so our guess is that there is a component on their side that is doing incorrect/unwanted transcoding.
These snuck in in ba109dab5e5 while fixing an extended ASCII **`è`**, aka **`E8`**.
This encoding is already used in the Montréal segment of A-20, and everywhere in canqc.csv. Ping …

canqca.con.csv: LATIN SMALL LETTER E WITH ACUTE

---

hwy_data/MA/usama/ma.ma003.wpt
hwy_data/MA/usaus/ma.us044.wpt
updates.csv

Relabeled exits from sequential to mileage-based. In-use labels that have moved: `17`, `16`, `12`, `7`.
https://forum.travelmapping.net/index.php?topic=7.new#new
aaroads afarina brendan dfilpus mapmikey master_son ~neroute2~ ntallyn okroads scott_stieglitz squatchis
afarina mapmikey master_son ~neroute2~ ntallyn
@ajfarina @mapmikey @ssoworld ~@neroute2~ @ntallyn 
aaroads brendan dfilpus okroads scott_stieglitz squatchis 
---
I believe this *fixes* MA3 for @neroute2.

complete MA3 exit renumbering

---

hwy_data/FL/usafl/fl.fl010ajac.wpt
hwy_data/FL/usafl/fl.fl113.wpt

Goofed here, and need to correct these labels before anybody uses them.  Since 10A doesn't technically intersect 113 (no ramps connecting each other), the labels on either shouldn't mention the other.  Only FL-115 has connections to either at that location.  There will still be a graph connection for all 3 routes there, but that can't be helped since it's the center of the interchange.  At least the labels will be correct.

usafl: correct labels

---

hwy_data/MA/usama/ma.ma003.wpt
hwy_data/MA/usama/ma.ma006ayar.wpt
hwy_data/MA/usama/ma.ma140.wpt
hwy_data/MA/usaus/ma.us006.wpt
hwy_data/MA/usaus/ma.us044.wpt
hwy_data/RI/usaus/ri.us001.wpt
hwy_data/RI/usaus/ri.us006.wpt

Non-newsworthy:
Formerly used old CHM-style crossroad-labels rather than the sequential exit numbers.
No labels moved; no .lists broken.

MA US6 exit renumbering

---

hwy_data/MA/usai/ma.i090.wpt
hwy_data/MA/usama/ma.ma009.wpt
hwy_data/MA/usama/ma.ma030.wpt
hwy_data/MA/usaus/ma.us020.wpt

Massachusetts' conversion to mileage-based exits continues.
Phase 2 (E of I-95) will happen when there's confirmation via AARoads that it's taken place in the field. When it does, it won't break any .lists, as the remaining future exits numbers are all way bigger than anything in the file now.
Somewhat surprisingly, only Exit 10 is broken.
dcharlie foresthills93 formulanone froggie hsford JamesMD jweeks mapmikey markkos1992 mojavenc noelbotevera paulthemapguy rlee roadgeek_adam roukan sipes23
formulanone froggie jweeks mapmikey markkos1992 mojavenc sipes23
@freakwentflier @ajfroggie @jweeksiii @mapmikey @Markkos1992 @NickCPDX @sipes23 …

I-90 phase 1 (W of I-95)

---

hwy_data/PA/usapa/pa.pa050.wpt
hwy_data/PA/usapa/pa.pa980.wpt

https://forum.travelmapping.net/index.php?topic=4088.0
PA 50: Added Fort Cherry Rd (FortCheRd) and Fayette Way (FayWay). (https://www.patpconstruction.com/southern_beltway/pdf/2020-10-30%20Southern%20Beltway%20Weekly%20Update.pdf)
PA 980:  Relocated and Unhid Fort Cherry Rd (FortCheRd) point. (https://www.patpconstruction.com/southern_beltway/pdf/2021-01-29%20Southern%20Beltway%20Weekly%20Update.pdf)  The file says the permanent traffic pattern is in place so I think that FortCheRd is open.

PA 50 and PA 980 Point Additions Related to PA 576

---

hwy_data/NY/usasf/ny.innloop.wpt
hwy_data/_systems/usasf.csv
hwy_data/_systems/usasf_con.csv
updates.csv

Data check passed.
Had a bit of a back-n-forth over whether to call it "Loop" or "Lp"; looked to existing HighwayData for guidance. Route names in CSVs used both inconsistently, so I went with "InnLoop" that's still present in a couple usany AltLabels.

Rochester Inner Loop

---

hwy_data/MN/usamn/mn.mn027.wpt
hwy_data/MN/usamn/mn.mn054.wpt
hwy_data/MN/usamn/mn.mn055.wpt
hwy_data/MN/usamn/mn.mn078.wpt
hwy_data/MN/usamn/mn.mn079.wpt
hwy_data/MN/usaus/mn.us059.wpt
hwy_data/_systems/usamn.csv
hwy_data/_systems/usamn_con.csv
updates.csv

MN 54 turned back, and MN 78 extended south to MN 79

MN 54 Turnback/MN 78 Extension

---

hwy_data/MN/usai/mn.i035w.wpt
hwy_data/MN/usaus/mn.us010.wpt

MnDOT recently changed exit numbers along I-35W in the vicinity of I-694 and US 10.  For @alexgotz @freakwentflier @NickCPDX , this affects your lists as you're currently using the "27" point on I-35W which has been renumbered 26B.  @yakra, can you add anyone to this notification who is using the "I-35W(28B)" point on mn.us010?  That label has changed to I-35W(28A) as a result of this exit renumbering.

I-35W/US 10 Exit Number Changes

---

hwy_data/TX/usai/tx.i069.wpt
hwy_data/TX/usaus/tx.us059.wpt

Other than marking it closed, went no-build on TXSpr529. Once all the dust settles, Exit 94 may end up being a little more to the SW. This leaves future options open.

I-69 exit numbers

---

hwy_data/CA/usaca/ca.ca125.wpt
hwy_data/NM/usaus/nm.us054.wpt
hwy_data/QC/canqc/qc.qc136mon.wpt
hwy_data/QC/canqc/qc.qc185.wpt
hwy_data/QC/canqca/qc.a015.wpt
hwy_data/QC/canqca/qc.a020.wpt
hwy_data/QC/canqca/qc.a085.wpt
hwy_data/QC/cantch/qc.tchmai.wpt
hwy_data/_systems/canqc.csv
hwy_data/_systems/canqc_con.csv
hwy_data/_systems/canqca.csv
hwy_data/_systems/canqca_con.csv

In Quebec:
-- A-720 decommissioned, replaced with new Montreal segment of QC 136
-- A-85 Riviere du Loup segment extended SE to new junction with QC 185
-- Conforming changes to QC 185 and TCHMai
In New Mexico, US 54 updated to reflect minor relocation in Logan to new bridge across the Canadian River
In California, preview route CA 125 updated to correct exit numbers and break false concurrency with CA 94
Updates items for Quebec and New Mexico changes to be made in separate pull request.

QC, CA, NM updates

---

hwy_data/TX/usai/tx.i040.wpt

Half-interchange. The existing Helium Rd underpass is farther W; the ramps are farther E. Splitting the difference & putting the point at the future TXLp335 location.

add TX I-40 63

---

hwy_data/MA/usai/ma.i395.wpt

4 7 
`6` was not retained as an AltLabel for `11`, because the 2 people using it have the old Exit 7 as the other waypoint. Rather than create bad stats & maps, I opted to just break these .list lines & thus include notes in the .log files that they need attention.
1 aaroads atsiatas ben114 charliezeb cl94 dantheman dave1693 dcm55343 deathtopumpkins dnthrox dougtone drebbin37 duke87 electronym foresthills93 froggie fwydriver405 gpw htm_duke hurricanehink JamesMD jjbers johninkingwood jpinyan jstalica lakewy17 lkefct M3200 mapcat mariethefoxy master_son neilbert nezinscot norheim okroads oscar ovoss_old pbryan sbeaver44 tbwillie tckma terescoj terminal_moraine ua747sp valedc03ls vdeane …

MA I-395 exit renumbering

---

hwy_data/MA/usai/ma.i091.wpt
hwy_data/MA/usama/ma.ma002.wpt
hwy_data/MA/usama/ma.ma002acam.wpt
hwy_data/MA/usama/ma.ma008.wpt
hwy_data/MA/usama/ma.ma010.wpt
hwy_data/MA/usama/ma.ma111.wpt
hwy_data/MA/usama/ma.ma116.wpt
hwy_data/MA/usama/ma.ma140.wpt
hwy_data/MA/usaus/ma.us005.wpt
hwy_data/MA/usaus/ma.us020.wpt
hwy_data/MA/usaus/ma.us202.wpt
updates.csv

No .list files broken.
The smallest new exit number is greater than the largest old number.
---
6 7 8 12 14 25 26 27
`16` was not retained as an AltLabel for `14`, because the 1 person using it has the old Exit 27 as the other waypoint. Rather than create bad stats & maps, I opted to just break osu_lsu.list & thus include a note in the .log file that it needs attention.
1 afarina ben114 bhemphill clark1mt dave1693 dfilpus fwydriver405 highplainstrvlr highway63 hsford Ib3kii jstalica julmac jwood lakewy17 M3200 mapmikey mc49399 mefailenglish mikeandkristie new_friends_gr ngrier njhighways osu_lsu sbeaver44 scott_stieglitz SK220 Smeeg101 sneezy squatchis stnyroads tckma thehighwayman3561 …

I-91 & MA2 renumbering, etc.

---

hwy_data/JPN/jpnh/jpn.n131.wpt
hwy_data/JPN/jpnh/jpn.n132.wpt
hwy_data/JPN/jpnh/jpn.n133.wpt
hwy_data/JPN/jpnh/jpn.n149.wpt
hwy_data/JPN/jpnh/jpn.n154.wpt
hwy_data/JPN/jpnh/jpn.n164.wpt
hwy_data/JPN/jpnh/jpn.n172.wpt
hwy_data/JPN/jpnh/jpn.n174.wpt
hwy_data/JPN/jpnh/jpn.n177.wpt
hwy_data/JPN/jpnh/jpn.n189.wpt
hwy_data/JPN/jpnh/jpn.n198.wpt
hwy_data/JPN/jpnh/jpn.n295.wpt
hwy_data/JPN/jpnh/jpn.n332.wpt
hwy_data/JPN/jpnh/jpn.n481.wpt
hwy_data/_systems/jpnh.csv
hwy_data/_systems/jpnh_con.csv
systems.csv

System files and minato (port) national highways wpt files for the **jpnh** Japan National Highway system. Minato highways are very short national highways that connect seaports/airports to other national highways.

Initial jpnh submission

---

hwy_data/QC/canqc/qc.qc185.wpt
hwy_data/QC/canqca/qc.a085.wpt
hwy_data/QC/cantch/qc.tchmai.wpt

Adjusts A-85 northern segment endpoint, at now-closed intersection with Route des Roches (bypassed segment of QC 185), to reflect corrected OSM mapping and my field check earlier this month. QC 185 and TCHMai route files adjusted accordingly.
No Updates entry needed.

Tweaks to QC A-85 extension in St-Antonin

---

hwy_data/PA/usapa/pa.pa028.wpt
hwy_data/PA/usapa/pa.pa060.wpt
hwy_data/PA/usapa/pa.pa066.wpt
hwy_data/PA/usapa/pa.pa168.wpt
hwy_data/PA/usapa/pa.pa351.wpt
hwy_data/PA/usausb/pa.us019trkpit.wpt

US 19 TRUCK (Pittsburgh): IgnRd>-IngRd
PA 28/PA 66: Replaced +X3A with SR1027.
PA 60: MainSt>-WalSt (Walbridge St).  Replaced +X3 with McMunn Ave (McMAve).  Removed TidRd.
PA 168: OldCheRd>-OldPA168.  Added Union Valley Rd (UniValRd).
PA 351: Added 4thSt_N and 4thSt_S.

US 19 TRUCK (Pittsburgh), PA 28, PA 60, PA 66, PA 168, and PA 351 Revisions

---

hwy_data/IA/usaus/ia.us063.wpt
hwy_data/WI/usawi/wi.wi042.wpt

US 63: Renamed SStaSt->StaSt.
WI 42: Added point IslCliFry.  Removed Unused Alternate Label.  (may solve or partially solve (https://forum.travelmapping.net/index.php?topic=3220.msg26001#msg26001))

US 63 (IA) and WI 42 Highway63 Updates

---

hwy_data/DE/usade/de.de020.wpt
hwy_data/DE/usade/de.de026.wpt
hwy_data/DE/usade/de.de054.wpt
hwy_data/DE/usaus/de.us113.wpt

US 113: DE24/30>-DE24. (https://forum.travelmapping.net/index.php?topic=4672.0)  Removed OldShaRd.
DE 20: DE24/30>-DE24. (https://forum.travelmapping.net/index.php?topic=4672.0)  Removed WooFerRd and BetConRd.
DE 26:  Fixed broken concurrency with DE 30/DE 54.  Removed IroLn.
DE 54:  Fixed broken concurrency with DE 26/DE 30.  Removed LawsPoiRd.

US 113/DE 20: DE24/30>-DE24

---

hwy_data/PA/usai/pa.i099.wpt
hwy_data/PA/usai/pa.i180.wpt
hwy_data/PA/usaif/pa.i099futloc.wpt
hwy_data/PA/usapa/pa.pa026.wpt
hwy_data/PA/usapa/pa.pa042trkeag.wpt
hwy_data/PA/usapa/pa.pa484.wpt
hwy_data/PA/usapa/pa.pa867trkroa.wpt
hwy_data/PA/usaus/pa.us220.wpt

Shaping Point Reduction along US 220 (and concurrencies), PA 26, and PA 867 TRUCK (Roaring Spring), 
Other Changes:
US 220:  Relocated HolHolRd.  Replaced ChaHillRd with VetMemRd (Veterans Memorial rd).  Replaced FaiRd with OldUS220_S.  Replaced +X200 with OldUS220_N.
PA 484:  Replaced +X1  with Stahle Rd (StaRd).  Replaced +X3 with Pigeon Cove Rd (PigCoveRd_N).

Point Revisions 11-22-2021

---

hwy_data/UT/usaut/ut.ut138.wpt
hwy_data/UT/usaut/ut.ut179.wpt

This fixes the 138/179 transition based on local tip that what OSM currently shows does not match ground reality

UT 138 truncation redux

---

hwy_data/NY/usasf/ny.hutrivpkwy.wpt
updates.csv

Hutchinson River Parkway has been renumbered from sequential to mileage-based.
**Broken exit numbers:**
2 3 7 13 15
alex barefoot_driver brendan cebarb98 chaddean chart33 dave1693 eth foresthills93 formulanone froggie gpw hurricanehink jackgaynor jaehak JamesMD keithcavey master_son nezinscot noelbotevera sbeaver44 shiggins
alex chart33 dave1693 eth formulanone froggie jackgaynor keithcavey master_son nezinscot
@alexgotz @cahart1 @dave1693 @tmharley @freakwentflier @ajfroggie @mrpoodlepants @keithcavey @ssoworld @denishanson 
barefoot_driver brendan cebarb98 chaddean foresthills93 gpw hurricanehink jaehak JamesMD noelbotevera sbeaver44 …

NY: Hutchinson River Parkway mileage-based exits

---

hwy_data/VA/usanp/va.gwmempkwymtv.wpt
hwy_data/VA/usausb/va.us460busapp.wpt
hwy_data/VA/usava/va.va326.wpt

VA131 is not currently in use so this was an easy fix.
Also fixed Label typo for the Mount Vernon portion of the GW Pkwy and switched the labels on VA 326 as HanJuvCen was supposed to become an alternate label for VirPSTC.

US 460 BUS (Appomattox): Fixing VA 131 Duplicate Label Error

---

hwy_data/TX/usai/tx.i369.wpt
hwy_data/TX/usatx/tx.tx007.wpt
hwy_data/TX/usatxl/tx.lp0012.wpt
hwy_data/TX/usatxl/tx.lp0354.wpt
hwy_data/TX/usatxl/tx.lp0368.wpt
hwy_data/TX/usatxs/tx.sp0482.wpt
hwy_data/TX/usausb/tx.us290buscyp.wpt
hwy_data/_systems/usatxl.csv
hwy_data/_systems/usatxl_con.csv
hwy_data/_systems/usausb.csv
hwy_data/_systems/usausb_con.csv
updates.csv

* **TXLp354:** https://publicdocs.txdot.gov/minord/MinuteOrderDocLib/115188.pdf
* **US290BusCyp** was removed from CHM due to being unsigned. Signage has since been added. Not the best, but [it's](https://www.google.com/maps/@29.9752065,-95.7077622,3a,75y,136.47h,94.13t/data=!3m6!1e1!3m4!1sSq-1DMaXM41rwt3oQPBQ_A!2e0!7i16384!8i8192) [something](https://www.google.com/maps/@29.9711851,-95.6933276,3a,15y,329.01h,90.85t/data=!3m6!1e1!3m4!1s0fUCrx_C9oUTwtLASD4-pw!2e0!7i16384!8i8192).

delete TXLp354, add US290BusCyp

---

hwy_data/DE/usade/de.de018.wpt
hwy_data/DE/usade/de.de023.wpt
hwy_data/DE/usade/de.de404.wpt
hwy_data/DE/usaus/de.us009.wpt
updates.csv

US 9: Relocated Sand Hill Rd.
DE 18: Removed SanRd.
DE 23.  Added Stockley Rd (StoRd).  (Slightly realigned between Stockley Rd (StoRd) and Hopkins Rd (HopRd) due to roundabout at new Anchors Run Subdivision between these two points.)
DE 404: Removed SanRd and relocated Sand Hill Rd.

US 9, DE 18, DE 23, and DE 404 Updates

---

hwy_data/TX/usatxf2/tx.fm0665.wpt
hwy_data/TX/usaus/tx.us077.wpt
hwy_data/TX/usausb/tx.us077busdri.wpt
hwy_data/_systems/usausb.csv
hwy_data/_systems/usausb_con.csv
updates.csv

Northbound US77 has been on the bypass since November, with the NB ramp to US77Bus [reported open](https://www.aaroads.com/forum/index.php?topic=3624.msg2699727#msg2699727) in January.
Don't know about the current southbound situation, but figure this is far enough along to make the change.
Hopefully, [the project will be completed in April](https://www.zachryconstructioncorp.com/Projects/Transportation/US-77-Driscoll-Bypass/) and we can have an I-69 extension then.
**This update affects:**
@TXStormchaser @bejacob @Duke87ofST @mrpoodlepants @jonfmorse @mapcat @ovoss @ryangentry @ua747sp

TX US77BusDri

---

hwy_data/IA/usaia/ia.ia001.wpt
hwy_data/IA/usaia/ia.ia003.wpt
hwy_data/IA/usaia/ia.ia136.wpt
hwy_data/IA/usaus/ia.us052.wpt
hwy_data/IA/usaus/ia.us151.wpt
hwy_data/IA/usausb/ia.us030busmtv.wpt
hwy_data/IA/usausb/ia.us151buscas.wpt
hwy_data/IL/usaib/il.i055blspr.wpt
hwy_data/IL/usail/il.il029.wpt
hwy_data/IL/usail/il.il104.wpt
hwy_data/IL/usaus/il.us054.wpt
hwy_data/IL/usaus/il.us067.wpt
hwy_data/MO/usaib/mo.i044blleb.wpt
hwy_data/MO/usamo/mo.mo005.wpt
hwy_data/MO/usamo/mo.mo032.wpt
hwy_data/MO/usamo/mo.mo064.wpt
hwy_data/MO/usamo/mo.mo079.wpt
hwy_data/MO/usaus/mo.us036.wpt
hwy_data/MO/usaus/mo.us054.wpt
hwy_data/MO/usausb/mo.us054buslak.wpt
hwy_data/MO/usaush/mo.us066hisstl.wpt
hwy_data/WI/usawi/wi.wi083.wpt
hwy_data/WI/usawi/wi.wi175.wpt
hwy_data/_systems/usaib.csv
hwy_data/_systems/usaib_con.csv
hwy_data/_systems/usausb.csv
hwy_data/_systems/usausb_con.csv
updates.csv

Illinois:
I-55 BL (Springfield, IL): Fixing IL29_S. (Done by @Markkos1992)
US 54: Slightly relocated point MO/IL for new bridge.
US 67: Added exit ConAreRd.
IL 29:  Removed from Springfield Road through Edinburg and relocated onto four-lane bypass on east side of Edinburg. Added points HicSt, WebSt_N.  (Corrected SanAve>-I-55BL_S by @Markkos1992)
IL 104:  Added point MorSt for new bridge across Illinois River. Added exit ConAreRd. (https://forum.travelmapping.net/index.php?topic=4814.0)
Iowa:
US 30 BUS (Mount Vernon, IA):  Added route.
US 52: Renamed IA3/136->IA3.
US 151: Renamed US151BusCas_S->248thSt.
US 151 BUS (Cascade, IA):  Removed from 1st Avenue southwest of IA 136 and relocated onto IA 136 between 1st Avenue and US 151 in Cascade. Point US151_S relocated from old south end to IA …

IL/IA/MO/WI Updates from Highway63  

---

hwy_data/IL/usaush/il.us066hischi.wpt

Fix from https://github.com/TravelMapping/HighwayData/pull/5657
Side note: DirPky should be changed to DirPkwy on I-55BL and US66HisChi

US 66 Historic (Chicago): Fixing I-55BL/IL 29 Broken Concurrency.

---

hwy_data/CT/usact/ct.ct017.wpt
hwy_data/CT/usact/ct.ct066.wpt
hwy_data/CT/usact/ct.ct068.wpt
hwy_data/CT/usact/ct.ct073.wpt
hwy_data/CT/usact/ct.ct157.wpt
hwy_data/CT/usaus/ct.us005.wpt
updates.csv

[CT: US 5, CT 73, and CT 157 Point Requests](https://forum.travelmapping.net/index.php?topic=4878)
[CT 17 in Middletown](https://forum.travelmapping.net/index.php?topic=4879)
This fixes the routing of CT17 in Middletown to follow Saint John's Square instead of Washington Street between CT 9 and CT 66.
It relocates the `CT CT17 CT66_W` point in use by:
@dave1693 @neilbert @ua747sp
and the `CT CT66 CT17_S` point in use by:
@bejacob @dave1693 @dgolub @njroadhorse @USRoute220

CT additions & fixes

---

hwy_data/CA/usaca/ca.ca058.wpt
hwy_data/CA/usaca/ca.ca058wes.wpt

Extends CA 58 (Westside Pkwy) west to I-5 over Stockdale Hwy; relabel of main CA 58 route's I-5 waypoint, ahead of planned 2023 switch of main route from Rosedale Hwy to Stockdale Hwy/Westside Pkwy corridor.
No Updates item needed, since usaca is a preview system.

CA 58 updates

---

systems.csv

One thing I thought I'd fixed, to mark as FP an NMP pair between CA 49 and CA 132, didn't get into the NMP FP log for some reason. I just put in a pull request to try to fix that. 
Other than that, ready to activate (with the system update table edit, to go into a separate pull request).

Activate usaca (part 1)

---

hwy_data/PA/usaus/pa.us030.wpt

Since TolHillRd (https://www.google.com/maps/@40.3063778,-79.5751976,3a,75y,89.82h,84.87t/data=!3m6!1e1!3m4!1soWIkob1zIZdxqjtYB64vbg!2e0!7i16384!8i8192) can be used in place of GreRd_A, I thought it was best to change GreRd_B back to GreRd.

US 30:  GreRd_A>-TolHillRd.  GreRd_B>-GreRd.

---

hwy_data/CA/usaca/ca.ca047.wpt

Includes exit number relabels (labels in use preserved) discussed on forum. Does not include extending CA 47 west of I-110.

CA 47 minor revisions

---

hwy_data/PA/usapa/pa.pa420.wpt
hwy_data/PA/usaus/pa.us030.wpt
updates.csv

https://forum.travelmapping.net/index.php?topic=5213.0
Also removed unused alternate label on PA 420.

US 30: Realigned east of WV/PA and west of PA 168 between *OldUS30_A and *OldUS30_B.

---

hwy_data/FL/usafl/fl.fl417.wpt

Forgot this 'ramp' had it's own exit number in the past.  Corrected this since nobody is using it yet at least.
https://forum.travelmapping.net/index.php?topic=5264.msg29722#msg29722

fl.fl417: used correct old exit number for closed FL-408 ramps

---

hwy_data/PA/usai/pa.i080.wpt
hwy_data/PA/usapa/pa.pa026.wpt
hwy_data/PA/usaus/pa.us220.wpt

https://forum.travelmapping.net/index.php?topic=5280.0
PA 26 will need to be checked for a future recentering.
On a more serious note, when PA 26 is presumably rerouted off of Jacksonville Rd during the I-80/I-99 interchange project, I am going to have to deal with a label nightmare.  Why PennDOT did not just reroute PA 26 onto I-80 and the Jacksonville Rd connector now from Exit 163 is beyond my brain.

I-80/US 220:  Added Exit 163.

---

hwy_data/TX/usatx/tx.tx211.wpt
hwy_data/TX/usatx/tx.tx211gov.wpt
hwy_data/_systems/usatx.csv
hwy_data/_systems/usatx_con.csv
updates.csv

Amended 898fb3b66fc530da25de7e802b934659dd7fc3e4
https://www.bexar.org/ArchiveCenter/ViewFile/Item/5054
> On Monday, November 14, 2022, the long anticipated section of State Highway (SH) 211 between
Potranco Road (FM 1957) and Culebra Road (FM 471) officially opened to motorists in far west Bexar
County. The corridor links two existing sections of SH 211 now allowing seamless travel between
Bandera Road (SH 16) and Highway 90.

TX211 new segment

---

hwy_data/QC/canqc/qc.qc185.wpt
hwy_data/QC/cantch/qc.tchmai.wpt

Another TCH segment relocated in eastern Quebec, to future A-85 freeway alignment.
Datacheck successful. Updates items in PR #6193.

QC: short TCH relocation

---

hwy_data/PA/usapa/pa.pa063.wpt
hwy_data/PA/usaus/pa.us019.wpt
hwy_data/PA/usaus/pa.us202.wpt
hwy_data/PA/usausb/pa.us019trkpit.wpt
hwy_data/PA/usausb/pa.us202alttrknor.wpt
hwy_data/_systems/usausb.csv
hwy_data/_systems/usausb_con.csv
updates.csv

https://forum.travelmapping.net/index.php?topic=5286.0
Other Changes:
US 19:  Added Pine Creek Rd (PineCreRd).  
US 19 TRUCK (Pittsburgh):  ViewAve>-WestViewAve.  Added Ross Park Mall Dr (RPMallDr) and Pine Creek Rd (PineCreRd).
US 202:  US202AltTrk_S>-MorRd
PA 63:  US202AltTrk_S>-NorWalRd

Deleting US 202 ALT TRUCK (North Wales) and US 19 TRUCK (Pittsburgh) Revisions

---

updates.csv

The update didn't actually happen until several days after the date initially listed in updates.csv.
This will enable update notifications at the beginning of formulanone.log & Smeeg101.log.

fix update date for Quinlan bypass/business

---

hwy_data/PA/usapa/pa.pa118.wpt
hwy_data/PA/usapa/pa.pa231.wpt
hwy_data/PA/usapa/pa.pa590.wpt
hwy_data/PA/usapa/pa.pa837.wpt
hwy_data/PA/usapa/pa.pa982.wpt

PA 118:  Removed +X1.
PA 231:  Point relocations.
PA 590:  Removed shaping points.  Replaced +X2 with Walker Rd (WalRd).
PA 837: Removed unused alternate label.
PA 982: Relocated PizBarnRd.

PA 118, PA 231, PA 590, PA 837, and PA 982 Minor Revisions

---

hwy_data/ON/canonf/on.on427.wpt

Also added in 'closed' intersection for Zenway Blvd, due to that being a temporary terminus for the temporary RR-99 extension that ON-427 took over on it's path north, just in case anybody might need it.

on.on427: Minor recentering on northern extenstion segment

---

hwy_data/AK/usanp/ak.parkrd.wpt

Using Shaping point X348051 - closure here due to pretty rocks landslide until 2026 busses do not go past it. see https://forum.travelmapping.net/index.php?topic=5551

DenaliParkRd: Add Visible wpt for EastForkBridge

---

hwy_data/PA/usapa/pa.pa056.wpt
hwy_data/PA/usapa/pa.pa065.wpt
hwy_data/PA/usapa/pa.pa087.wpt
hwy_data/PA/usaus/pa.us022.wpt
hwy_data/PA/usaus/pa.us062.wpt
hwy_data/PA/usaus/pa.us422.wpt

Fixed labels on US 422:  https://forum.travelmapping.net/index.php?topic=5639.0
Removed unused alternate labels on PA 56, PA 65, PA 87, US 22, and US 62.
Other notes:
PA 65: Removed shaping point that was holding the unused alternate label.
PA 87:  Changed shaping points to JacRd_W and JacRd_E (Jacks Rd).

PA Changes 7-25-2023

---

hwy_data/NV/usanv/nv.nv431.wpt

Preemptively added waypoints at several major roads and trailheads using local knowledge. Renamed and relocated "JupDr" to "CouClubDr". Waypoint "MtRoseSum" can probably eventually replace "FR051"; added as new waypoint because "FR051" is currently in use.

Added waypoints at major intersections

---

hwy_data/PA/usapa/pa.pa066.wpt
hwy_data/PA/usapa/pa.pa068.wpt
hwy_data/PA/usapa/pa.pa128.wpt
hwy_data/PA/usapa/pa.pa168.wpt
hwy_data/PA/usapa/pa.pa333.wpt

PA 66: Recentered at PA 128.
PA 68: Replaced +X0 with WolfRunRd.  Replaced +X0A with Barclay Hill Rd (BarHillRd).  Relocated and removed asterisk from OldTownRd.
PA 168: Relocated WesDr.
PA 333: Removed shaping points and unused alternate label.  Relocated McLRd.

PA Revisions 8-7-2023

---

hwy_data/AR/usaar/ar.ar072.wpt
hwy_data/AR/usai/ar.i049.wpt
hwy_data/AR/usaus/ar.us071.wpt
updates.csv

https://www.aaroads.com/forum/index.php?topic=3324.msg2843458#msg2843458
Northernmost 4 exits renumbered downward by 2 miles. Exit 102 moved from the northern AR 72 junction (now exit 100) to CR 34.
Ping @theRadison

AR I-49 exits: tripling down on the dumb

---

hwy_data/NY/usany/ny.ny012.wpt
hwy_data/NY/usany/ny.ny079.wpt
updates.csv

https://forum.travelmapping.net/index.php?topic=5857
**NY12:**
Waypoint NY79_E moved about 0.9 mi northeast from the OldNY79 waypoint to a new Chenango River bridge approach.
Ping @travmapdantheman @drebbin37
**NY79:**
Removed from "Old Route 79", a truss bridge over the Chenango River, and Pigeon Hill Road, and relocated onto NY 12 and a new Chenango River bridge about 0.6 mi northeast of the existing one, between waypoint OldNY79 and Pigeon Hill Road.
Ping @jteresco @bmacs001 @cl994 @travmapdantheman @drebbin37 @Duke87ofST @ajfroggie @Markkos1992 @dlainhart @vdeane

NY79 new Chenango River bridge

---

hwy_data/NY/usai/ny.i084.wpt
hwy_data/NY/usany/ny.ny003.wpt
hwy_data/NY/usany/ny.ny005.wpt
hwy_data/NY/usany/ny.ny012.wpt
hwy_data/NY/usany/ny.ny035.wpt
hwy_data/NY/usany/ny.ny079.wpt
hwy_data/NY/usany/ny.ny100.wpt
hwy_data/NY/usany/ny.ny116.wpt
hwy_data/NY/usany/ny.ny156.wpt
hwy_data/NY/usaus/ny.us009.wpt
updates.csv

https://forum.travelmapping.net/index.php?topic=5857.msg33026#msg33026
`+PigHillRd` is retained as an AltLabel, only in use by @jteresco, in case you feel like updating to the primary label.
---
https://forum.travelmapping.net/index.php?topic=5889
https://forum.travelmapping.net/index.php?topic=5890

NY forum fixes

---

hwy_data/TX/usai/tx.i020.wpt
hwy_data/TX/usaib/tx.i020blsta.wpt
hwy_data/TX/usaib/tx.i040blama.wpt
hwy_data/TX/usatx/tx.tx105.wpt
hwy_data/TX/usatx/tx.tx105buscle.wpt
hwy_data/TX/usatx/tx.tx146.wpt
hwy_data/TX/usatx/tx.tx158.wpt
hwy_data/TX/usatxf6/tx.fm2590.wpt
hwy_data/TX/usatxl/tx.lp0207.wpt
hwy_data/TX/usatxl/tx.lp0335.wpt
hwy_data/TX/usatxl/tx.lp0335swa.wpt
hwy_data/_systems/usatxl.csv
hwy_data/_systems/usatxl_con.csv
updates.csv

https://forum.travelmapping.net/index.php?topic=6019
Ping @mapcat because you were there.
Ping @Markkos1992 because you're good at finding errors.
https://forum.travelmapping.net/index.php?topic=5958
https://forum.travelmapping.net/index.php?topic=5994
https://forum.travelmapping.net/index.php?topic=5986
---
`2024-01-05;(USA) Texas;I-40 BL (Amarillo);tx.i040blama;Waypoint TXLp335_W moved approx. 0.9 mi west from FM 2590.`
Ping @aaroads @deathtopumpkins @flroads @marnen
`2024-01-05;(USA) Texas;TX Loop 335;tx.lp0335;Removed from a demolished curve & FM 2590 (Soncy Rd) and relocated onto Hollywood Rd & Helium Rd between waypoints *OldTXLp335 & FM2590_N.`
Ping @TXStormchaser @aaroads @bejacob @deathtopumpkins @flroads @mapcat @mapmikey @marnen @theweatherman561 @theRadison 
`2024-01-05;(USA) …

TX forum items, 2024-01-05

---

hwy_data/OK/usaok/ok.ok066.wpt
hwy_data/OK/usaok/ok.ok066b.wpt
hwy_data/OK/usaok/ok.ok136.wpt
updates.csv

https://forum.travelmapping.net/index.php?topic=5955
https://forum.travelmapping.net/index.php?topic=6020
`2024-01-06;(USA) Oklahoma;OK 66B;ok.ok066b;From waypoint N3320, removed from a demolished west-southwesterly road and relocated due south to OK 66.`
Ping @mapcat @ua747sp 
`2024-01-06;(USA) Oklahoma;OK 136;ok.ok136;Removed from Road II, Mile 30 & Road EE and relocated onto a direct north-south road between the Texas state line and Road EE.`
Ping @mapcat @theweatherman561 @ovoss

OK 66B & 136 relocations

---

hwy_data/OK/usaok/ok.ok033.wpt
hwy_data/OK/usaok/ok.ok066.wpt
hwy_data/OK/usaok/ok.ok117.wpt
hwy_data/OK/usaok/ok.ok117a.wpt
hwy_data/OK/usausb/ok.us075altsap.wpt
updates.csv

https://forum.travelmapping.net/index.php?topic=5496
**OK33:** East end truncated from US 75 Alt and OK 97 to OK 117.
**OK66:** Removed from Dewey Ave and relocated onto OK 117 & OK 117A (Mission St) between waypoints DewAve_W & DewAve_E.
Ping @dietrichmd @bejacob _@mapcat @si404_ @bhoward @ozarkman417 _@theradison @scott5114_ @ua747sp
...and a few others. Something's changed at GitHub and now my script won't pull usernames 100% of the time. :(

Sapulpa 2024-01-29

---

hwy_data/FL/usafl/fl.fl100.wpt
hwy_data/FL/usafl/fl.fl230.wpt

Just a minor swap of points for where the new bridge touches down.  Still in the original ROW, point wasn't in-use, thus, not really news worthy.

FL: minor tweaks due to new FL-100 bridge in Starke

---

hwy_data/PA/usapa/pa.pa618.wpt
hwy_data/PA/usaus/pa.us011.wpt

US 11:  Added Washington St (WasSt), Sanders St (SanSt), and Birch St (BirSt_W and BirSt_E) to clarify one-way alignments and turns in Scranton.
PA 618: Removed Unused Alternate Label.

US 11 and PA 618 Point Revisions

---

hwy_data/MN/usamn/mn.mn029.wpt
hwy_data/MN/usamn/mn.mn030.wpt
hwy_data/MN/usamn/mn.mn055.wpt
hwy_data/MN/usamn/mn.mn056.wpt
hwy_data/MN/usamn/mn.mn092.wpt
hwy_data/MN/usamn/mn.mn222.wpt
hwy_data/MN/usaus/mn.us014.wpt
hwy_data/MN/usaus/mn.us061.wpt
hwy_data/MN/usaus/mn.us063.wpt
hwy_data/MN/usausb/mn.us014busdod.wpt
hwy_data/_systems/usamn.csv
hwy_data/_systems/usamn_con.csv
hwy_data/_systems/usausb.csv
hwy_data/_systems/usausb_con.csv
updates.csv

BUS US 14 Dodge Center removed due to lack of signage.
MN 222 removed due to turnback.
MN 30 realigned north of Rochester Airport via CR 8/CR 16/US 63.

MN cleanup

---

hwy_data/CT/usasf/ct.cttpk.wpt
hwy_data/ME/usame/me.me004.wpt
hwy_data/ME/usame/me.me026.wpt
hwy_data/ME/usame/me.me026agra.wpt
hwy_data/ME/usame/me.me100.wpt
hwy_data/ME/usame/me.me115.wpt
hwy_data/ME/usaus/me.us202.wpt
hwy_data/_systems/usame.csv
hwy_data/_systems/usame_con.csv
updates.csv

**ME26 broken for:**
Based8 Cw9 dharwood JamesMD mapcat tckma terescoj w9tam wadsteckel
Ping @mapcat @tckma317 @jteresco
**Ping @USRoute220**
In making the new route of ME26 backwards-compatible with old .list entries for ME26A, I had to either:
* Keep the `I-95` point label at its existing location at Exit 53, breaking that point for the six people using it on ME26A, or
* Move plain `I-95` to Exit 63 and avoid breaking those six lists, breaking only SK220.list intead.
I chose the latter option as the lesser evil. You'll want to change `ME ME26 FalRd I-95` to `ME ME26 FalRd I-95(53)`.
**Ping @jteresco**
Label `ME26_N` has moved on both US202 & ME4. You'll want to use `ShaRd` instead.
Next time you go to Sunday River... well, I imagine'd that probably be via NH US2 rather than Southern …

ME26 relocated onto ME26A in Gray

---

hwy_data/ME/usame/me.me026.wpt
hwy_data/ME/usaus/me.us001.wpt

Not newsworthy in the TM sense; just a new waypoint on US1.
Newsworthy in the traditional sense:
**Bangor Daily News** (paywalled, though *maybe* we get some monthly freebies?)
* [New Madawaska international bridge opens to traffic](https://www.bangordailynews.com/2024/06/06/aroostook/aroostook-government/new-madawaska-international-bridge-opens-to-traffic/) (2024-06-06)
* [Weight restriction to be lifted on new international bridge in August](https://www.bangordailynews.com/2024/07/01/aroostook/aroostook-business/weight-restriction-to-be-lifted-on-new-international-bridge-in-august/) (2024-07-01)
**CBC** (no paywall)
* [New bridge between New Brunswick and Maine may not revive battered cross-border bonds](https://www.cbc.ca/news/canada/new-brunswick/new-brunswick-maine-bridge-1.7232926) …

New international bridge & old Sabbathday Rd

---

hwy_data/AL/usai/al.i010.wpt
hwy_data/FL/usai/fl.i010.wpt

Per a thread James started in the forum, and following the legal definition of the AL/FL border in the middle of the Perdido River, tweaked the waypoint to match the legal definition, which also more or less matches OSM.

I-10 AL/FL point

---

hwy_data/AR/usaar/ar.ar043sil.wpt
hwy_data/AR/usaar/ar.ar043sou.wpt
hwy_data/AR/usaar/ar.ar169.wpt
hwy_data/OK/usaar/ok.ar043.wpt
hwy_data/OK/usaok/ok.ok020.wpt
hwy_data/_systems/usaar.csv
hwy_data/_systems/usaar_con.csv
updates.csv

A multi-region concurrency with OK OK20 was flagged by a new datacheck under development.
This only breaks formulanone.list; everyone else is OK thanks to concurrency augments.

chop up AR43Sil

---

hwy_data/ON/canonf/on.on400.wpt

Opened 12/19/18.
https://www.barrietoday.com/local-news/line-5-highway-400-interchange-in-bradford-opens-without-fanfare-1167360

on.on400: Add Exit 61

---

hwy_data/NS/cannsf/ns.ns107.wpt
updates.csv

Found a couple YouTube videos that confirmed
* Burnside is another half of Exit 12.
If this were Connecticut or something, maybe I'd relabel the points 12A & 12B for a nice unbroken alphanumeric sequence.
But this is Nova Scotia, where it's very common to have Exit 42A come *before* Exit 42. So leaving all existing points as-is.
* The Anderson Lake Connector is Exit 11.
When the videos were shot a month or 2 ago, this wasn't open. Ramps were blocked off with [orange barrels](https://www.youtube.com/watch?v=8KB7LrKDfMo) & unplowed. IIUC it's not connected to anything else yet; no buildings.
Adding it as a visible point now anyway, in order to get the shaping points right and not have to take a `+` off later. And to keep people from asking, "Hey, why's there no point here?" ;P
Maybe come …

NS107 extension

---

hwy_data/CA/usaca/ca.ca190dea.wpt
hwy_data/CA/usasf/ca.alfharhwy.wpt
hwy_data/CA/usaus/ca.us395.wpt
hwy_data/CA/usausb/ca.us395busola.wpt
hwy_data/_systems/usaca.csv
hwy_data/_systems/usaca_con.csv
hwy_data/_systems/usasf.csv
hwy_data/_systems/usasf_con.csv
hwy_data/_systems/usausb.csv
hwy_data/_systems/usausb_con.csv
updates.csv

- Added US 395 Business in Olancha, CA along old alignment of US 395. Waypoints along US 395 and CA 190 updated to reflect change.
- Added Alfred Harrell Highway to usasf in Bakersfield, CA
- Fixed typo in indicator for CA 108 Business (Twain Harte)

US 395 Business, Alfred Harrell Highway, CA 108 Business typo

---

hwy_data/VT/usaus/vt.us005.wpt
hwy_data/VT/usavt/vt.vt119.wpt
hwy_data/VT/usavt/vt.vt142.wpt
updates.csv

Related to VT 119 relocation onto the new Brattleboro-Hinsdale Bridge.  Per signage (verified by field check on 3/14/25), VT 119 terminates at VT 142 and not at US 5.

VT 119 Relocation

---

hwy_data/LA/usala/la.la0088.wpt
hwy_data/LA/usala/la.la0089.wpt
hwy_data/LA/usala/la.la0682.wpt
updates.csv

Truncated route based on LA DOTD road transfer maps and updated GSV imagery showing signs have been removed.

LA 89 Truncated

---

hwy_data/LA/usala/la.la0035.wpt
hwy_data/LA/usala/la.la00931.wpt
hwy_data/LA/usala/la.la0342.wpt
hwy_data/LA/usala/la.la0343.wpt
hwy_data/LA/usala/la.la0700.wpt
hwy_data/LA/usala/la.la0724.wpt
hwy_data/LA/usala/la.la3246.wpt
updates.csv

LA 93-1, 342, and 3246 truncated
LA DOTD Road Transfer maps and GSV imagery confirm truncations

LA Route Truncations

---

hwy_data/MO/usaib/mo.i029blstj.wpt
hwy_data/MO/usamo/mo.mo005.wpt
hwy_data/MO/usamo/mo.mo007.wpt
hwy_data/MO/usamo/mo.mo041.wpt
hwy_data/MO/usamo/mo.mo179.wpt
hwy_data/MO/usaus/mo.us059.wpt
hwy_data/MO/usaus/mo.us065.wpt
hwy_data/MO/usaus/mo.us067.wpt
hwy_data/MO/usaus/mo.us071.wpt
updates.csv

I-29 BL (St. Joseph): Added PennSt.
US 59: Added MOsCC, MOsH.
US 65: Removed from Ash Street south of Buffalo and relocated onto new alignment immediately to the west.
US 67: Added OldOrcRd.
US 71: Reset I-70(2J) and I-70(2L).
MO 5: Removed from old road through Decaturville, between Camdenton and the Ozark County line, and relocated onto new alignment to the west. Removed MOsP_Cam and MO7_S. OldMO5_S>-*OldMO5_S. LR577>-HarRd.
MO 7: Renamed MO5BusCam_S->MO5/5Bus. Renamed MO5_S->OldMO5_CamS.  OldMO5_S>-*OldMO5_S.  LR577>-HarRd.
MO 41: Added MecSt.
MO 179: Added MisDr.

MO Updates from Highway63

---

hwy_data/RI/usari/ri.ri120.wpt

Added a point on Rhode Island state route 120 at North Attleboro Road.

RI route 120 point addition
