hwy_data/NY/usany/ny.ny050.wpt, hwy_data/NY/usaus/ny.us044.wpt
https://forum.travelmapping.net/index.php?topic=4195
https://forum.travelmapping.net/index.php?topic=4199
=> NY50 / US44 label fixes

hwy_data/WV/usaus/wv.us011.wpt, hwy_data/WV/usaus/wv.us052kin.wpt, hwy_data/WV/usawv/wv.wv009.wpt, hwy_data/WV/usawv/wv.wv028altrid.wpt, hwy_data/WV/usawv/wv.wv044.wpt, hwy_data/WV/usawv/wv.wv045.wpt, hwy_data/WV/usawv/wv.wv065.wpt, hwy_data/_systems/usaus.csv, hwy_data/_systems/usaus_con.csv, updates.csv
Fixes:
https://forum.travelmapping.net/index.php?topic=2273.0 (partial 'temporary' fix for completely separate US-52 segment)
https://forum.travelmapping.net/index.php?topic=4141.0
https://forum.travelmapping.net/index.php?topic=4142.0
https://forum.travelmapping.net/index.php?topic=4144.0
=> WV fixes/additions

hwy_data/TX/usatx/tx.tx170.wpt
https://forum.travelmapping.net/index.php?topic=4202
=> TX170 Alliance Connector points

hwy_data/QC/canqc/qc.qc148.wpt
No Updates entry, per forum discussion.
=> Synch QC 148 to new ON 148 border point

hwy_data/ON/canon/on.on017.wpt, hwy_data/ON/canon/on.on072.wpt, hwy_data/ON/canon/on.on148.wpt, hwy_data/ON/cantch/on.tchlak.wpt, hwy_data/_systems/canon.csv, hwy_data/_systems/canon_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=4232.0
https://forum.travelmapping.net/index.php?topic=4233.0
=> Ontario fixes

hwy_data/MA/usai/ma.i190.wpt, hwy_data/MA/usama/ma.ma012.wpt, hwy_data/MA/usama/ma.ma122awor.wpt, hwy_data/MA/usama/ma.ma146.wpt, updates.csv
All .list file breakage occurred on MA146. Nobody's travels on I-190 were affected.
ben114 charliezeb cl94 dantheman dougtone drebbin37 duke87 fwydriver405 hugbear51 jonsamuels lakewy17 lkefct M3200 mariethefoxy nezinscot skatcher terminal_moraine vdeane whopperman
ben114 cl94 duke87 jonsamuels nezinscot terminal_moraine vdeane
@benchase1 @cl994 @Duke87ofST @JonSamuels @denishanson @mbeller2016 @vdeane 
charliezeb dantheman dougtone drebbin37 fwydriver405 hugbear51 lakewy17 lkefct M3200 mariethefoxy skatcher whopperman
=> MA146 & I-190 exit renumbering

hwy_data/TX/usatx/tx.tx071.wpt
https://forum.travelmapping.net/index.php?topic=4266
=> TX71: add KelRd

hwy_data/KS/usaks/ks.ks032.wpt
https://forum.travelmapping.net/index.php?topic=4282
=> KS32: resync US69

hwy_data/TX/usatx/tx.tx249.wpt, hwy_data/TX/usatxf3/tx.fm1486.wpt, hwy_data/TX/usatxf4/tx.fm1774.wpt, updates.csv
https://twitter.com/txsh249/status/1375585215243038726
> We are excited to announce that as of Mar. 26,2021, Section 1B is now open to the public! It extends from FM1488 in Magnolia to FM1774 in Plantersville near Todd Mission. It's a controlled-access tollway with intermittent frontage roads. Tolling will begin immediately on opening.
=> TX249 Section 1B

hwy_data/PA/usapa/pa.pa347.wpt, hwy_data/PA/usausb/pa.us006buscar.wpt
https://forum.travelmapping.net/index.php?topic=2999.0
=> US 6 BUS(Carbondale)/PA 347: Restoring Graph Connection

hwy_data/NJ/usai/nj.i095sec.wpt
https://forum.travelmapping.net/index.php?topic=4308
=> NJ I-95Sec: 18W -> 19W

hwy_data/WA/usawa/wa.wa704.wpt, hwy_data/_systems/usawa.csv, hwy_data/_systems/usawa_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=4300.0
=> Add WA 704

hwy_data/TX/usaib/tx.i035bllar.wpt, hwy_data/TX/usatxf7/tx.fm3406.wpt, hwy_data/_systems/usatxf7.csv, hwy_data/_systems/usatxf7_con.csv
=> TX I-35BLLar: add ScoSt

hwy_data/ROU/roudj/rou.dj102f.wpt, hwy_data/ROU/roudj/rou.dj220a.wpt, hwy_data/_systems/roudj.csv, hwy_data/_systems/roudj_con.csv, updates.csv
@jteresco please hold on this one until @michihdeu confirms it's ok
=> roudj 220A

hwy_data/NE/usaib/ne.i080blpin.wpt, hwy_data/_systems/usaib.csv, hwy_data/_systems/usaib_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=4313
=> delete NE I-80BLPin

hwy_data/MN/usai/mn.i694.wpt, hwy_data/MN/usaib/mn.i035blalb.wpt, hwy_data/MN/usamn/mn.mn013.wpt, hwy_data/MN/usamn/mn.mn100.wpt, hwy_data/MN/usaus/mn.us065.wpt
=> MN NMP fixes

hwy_data/MN/usai/mn.i090.wpt, hwy_data/MN/usaus/mn.us014.wpt, hwy_data/MN/usaus/mn.us061.wpt
Fixed I-90 NMP at WI Line and corrected interchange location at I-90/US 14/US 61.
=> MN I-90 NMP

updates.csv
Highway63 has no issue with this tweak.
https://forum.travelmapping.net/index.php?topic=3861.msg23800#msg23800
=> IL: Updated I-294 entry to reduce confusion

updates.csv
https://github.com/TravelMapping/DataProcessing/issues/369
=> move E38 from root to route field

hwy_data/OK/usai/ok.i040.wpt, hwy_data/OK/usaib/ok.i040blsay.wpt, hwy_data/OK/usaok/ok.ok058med.wpt, hwy_data/OK/usaus/ok.us283.wpt, hwy_data/OK/usaush/ok.us066hiswea.wpt
https://forum.travelmapping.net/index.php?topic=3179
=> OK: US 66-adjacent things

updates.csv
=> FL: Fix FL-46mtd url

hwy_data/NY/usany/ny.ny394.wpt
https://forum.travelmapping.net/index.php?topic=4345
=> NY394 cleanup

hwy_data/WA/usaush/wa.us010hisgeo.wpt, hwy_data/_systems/usaush.csv, hwy_data/_systems/usaush_con.csv
More updates to extend US10HisFre to George and rename US10HisGeo
=> WA usaush updates

hwy_data/NY/usany/ny.ny394.wpt
https://forum.travelmapping.net/index.php?topic=4345
=> NY394: replace WinSt with 2ndSt_W

hwy_data/MA/usai/ma.i093.wpt, hwy_data/MA/usama/ma.ma003.wpt, hwy_data/MA/usama/ma.ma028.wpt, hwy_data/MA/usaus/ma.us001.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=7.new#new
18 20 22 23 24 26 27 28 31 40 46
Old Exit 41 was not needed at a new location, but intentionally broken and not kept as an AltLabel -- the only person using it in a .list file paired it with Exit 40, which has moved. Rather than create bad stats & maps, I opted to just break dantheman.list & thus include a note in dantheman.log that the line needs attention.
25or6to4 andrepoiy_total baugh17 Beerman ben114 clong cvoight dantheman dave1693 dfilpus dgolub finnedude georgiaroadgeek gpw hoss6884 hugbear51 Ib3kii intheam jackgaynor JamesMD jjbers julmac keithcavey kj kjslaughter lakewy17 lamsalfl lowenbrau M3200 mapmikey MatthewR …
=> MA I-93 exit renumbering

hwy_data/CA/usaca/ca.ca074.wpt, hwy_data/CA/usaca/ca.ca210.wpt, hwy_data/NM/usanm/nm.nm068.wpt, hwy_data/NM/usanm/nm.nm074.wpt, hwy_data/NM/usanm/nm.nm501.wpt, hwy_data/NM/usaus/nm.us054.wpt, hwy_data/NM/usausb/nm.us054bustuc.wpt, hwy_data/NM/usaush/nm.us066hissfe.wpt
Updates table entries for NM 68 and NM 74 in PM #4852.
NV changes to follow, but not today.
=> NM and a few CA updates

updates.csv
https://github.com/TravelMapping/HighwayData/pull/4844#issuecomment-854171328
=> fix I-93 updates entry

hwy_data/PA/usapa/pa.pa519trkhou.wpt
To fix broken concurrency with PA 50 I created last week.
=> PA 519 TRUCK (Houston):  Recentering FayWay

hwy_data/NV/usai/nv.i080.wpt, hwy_data/NV/usaib/nv.i080blren.wpt, hwy_data/NV/usanv/nv.nv289.wpt, hwy_data/NV/usanv/nv.nv401.wpt, hwy_data/NV/usaus/nv.us095.wpt
=> Rest of NV I-80 corridor NMP fixes

hwy_data/WI/usaus/wi.us061.wpt, hwy_data/WI/usawi/wi.wi035.wpt
Fixing issues from: https://github.com/TravelMapping/HighwayData/pull/4872
Caught here:  https://forum.travelmapping.net/index.php?topic=3506.msg24184#msg24184
I have emailed Highway63 to clarify the fixes in these files.  Please do not pull this in until I get the clarification to do so,
=> Fixing WI 35 and US 61 from PR#4872

hwy_data/PA/usapa/pa.pa418.wpt, hwy_data/PA/usapa/pa.pa718.wpt, hwy_data/PA/usapa/pa.pa760.wpt, hwy_data/PA/usausb/pa.us062bussha.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=4357.0
=>  PA 418: Extended to US 62 Business (Sharon) based on signage.

updates.csv
https://github.com/TravelMapping/HighwayData/pull/4875#issuecomment-858689503
=> fix Fayetteville ->Springdale in updates entry

hwy_data/_systems/usanp_con.csv
The problem is only with usanp's connected routes file. No issue with the chopped routes file, which is unchanged.
datacheck.sh run successful.
=> usanp csv fix for Datacheck error

hwy_data/AR/usaar/ar.ar014.wpt, hwy_data/AR/usaar/ar.ar018.wpt, hwy_data/AR/usaar/ar.ar075.wpt, hwy_data/AR/usaar/ar.ar081s.wpt, hwy_data/AR/usaar/ar.ar140.wpt, hwy_data/AR/usaar/ar.ar149.wpt, hwy_data/AR/usaar/ar.ar308mar.wpt, hwy_data/AR/usai/ar.i430.wpt, hwy_data/AR/usausb/ar.us063busmar.wpt, hwy_data/_systems/usausb.csv, hwy_data/_systems/usausb_con.csv, updates.csv
=> Marked Tree

hwy_data/WA/usawa/wa.wa108busmcc.wpt, hwy_data/WA/usawa/wa.wa108sprmcc.wpt, hwy_data/_systems/usawa.csv, hwy_data/_systems/usawa_con.csv, updates.csv
Had a massive brain fart when creating this route last night. It's actually a business loop, not a spur...
=> Change WA 108 Spur to WA 108 BL

hwy_data/ON/canonf/on.on427.wpt
Just a small fix that I wanted to get online right now that has nothing to do with the in-progress Secondary highways.
=> on.on427: Fix graph connection with 401

hwy_data/NB/cannbc/nb.nb101.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=4413
=> Fix NB101 S endpoint label

hwy_data/PA/usapa/pa.pa085.wpt, hwy_data/PA/usapa/pa.pa553.wpt, hwy_data/PA/usaus/pa.us119.wpt, hwy_data/PA/usaus/pa.us219.wpt
Other Changes:
US 119:  Added shaping points, Kimmel Rd (KimRd), and Wynkoop Rd (WynRd).
PA 85: Added Stone House Rd (StoHouRd) and a shaping point.
PA 553:  Added Laurel Run Rd (LauRunRd).
=> US 219/PA 553 Recentering

hwy_data/ROU/roudj/rou.dj602.wpt, hwy_data/ROU/roudj/rou.dj602a.wpt, hwy_data/ROU/roudj/rou.dj701b.wpt, hwy_data/_systems/roudj.csv, hwy_data/_systems/roudj_con.csv, updates.csv
=> ROU DJ602A

hwy_data/MA/usai/ma.i495.wpt, hwy_data/MA/usama/ma.ma028.wpt, hwy_data/MA/usama/ma.ma110.wpt, hwy_data/MA/usama/ma.ma140.wpt
12 14 15 19 22 25 27 36 41
**Indirectly broken labels:** These old labels were not needed at a new location, but were intentionally broken because everybody using them in a .list file paired them with one of the broken points above. Rather than create bad stats & maps for everyone, I opted to just break these .list lines & thus include notes in the .log files that they need attention.
34 35C
1995hoo 420Traveler a3 afarina angelsfreeek atsiatas bobcobb brendan capn chart33 dave1693 dcharlie dharwood gpw griffith highway63 hoss6884 hsford hurricanehink jackgaynor jaehak jjbers johninkingwood jonfmorse jonsamuels klundgren kubbage lowenbrau M3200 mapmikey mariethefoxy markkos1992 …
=> MA I-495 exit renumbering

hwy_data/MA/usai/ma.i495.wpt, hwy_data/MA/usama/ma.ma028.wpt, hwy_data/MA/usama/ma.ma110.wpt, hwy_data/MA/usama/ma.ma140.wpt, hwy_data/_systems/usatxs.csv
689dab1 is the same commit as in #4932; there won't be merge conflicts.
=> TXLp235 AltRouteName unused

hwy_data/NH/usai/nh.i093.wpt, hwy_data/NH/usai/nh.i293.wpt
https://forum.travelmapping.net/index.php?topic=4436
=> NH unnumbered exits

hwy_data/QC/cantch/qc.tchmai.wpt
Replaced qc.tchmai.wpt file, to fix Datacheck errors in PR #4964.
=> Error fix for #4964

hwy_data/NY/usany/ny.ny032.wpt, hwy_data/NY/usany/ny.ny159.wpt, hwy_data/NY/usasf/ny.tacstapkwy.wpt
https://forum.travelmapping.net/index.php?topic=3153
https://forum.travelmapping.net/index.php?topic=3954
=> NY32/159 / TacStaPkwy points

hwy_data/PA/usapa/pa.pa041.wpt, hwy_data/PA/usapa/pa.pa051.wpt, hwy_data/PA/usapa/pa.pa309buswil.wpt
PA 309 BUS (Wilkes-Barre): Added Pine St.
=> Minor PA Changes 7-17-2021

hwy_data/CA/usaca/ca.ca125.wpt
=> CA 125 exit tweak

hwy_data/NJ/usanj/nj.nj045.wpt, hwy_data/NJ/usanj/nj.nj056.wpt, hwy_data/NJ/usanj/nj.nj077.wpt, hwy_data/NJ/usaus/nj.us130.wpt, hwy_data/NJ/usaus/nj.us202.wpt, hwy_data/NJ/usaus/nj.us206.wpt
https://forum.travelmapping.net/index.php?topic=4483.0
=> topic 4483

hwy_data/PA/usapa/pa.pa120.wpt, hwy_data/PA/usapa/pa.pa286trkind.wpt
Also Removed Unused Alternate Label on PA 120
=>  PA 286 TRUCK (Indiana): Fixing Broken Concurrency With US 119

hwy_data/TX/usai/tx.i010.wpt, hwy_data/TX/usatxl/tx.lp0375.wpt, hwy_data/TX/usaus/tx.us085.wpt, hwy_data/TX/usaus/tx.us180elp.wpt
https://forum.travelmapping.net/index.php?topic=4497
=> TXLp375 & pals

hwy_data/TN/usatn/tn.tn092.wpt
add missing waypoint for new routing of US 411
=> TN: TN 92 fix

hwy_data/AR/usaar/ar.ar265.wpt, hwy_data/AR/usaar/ar.ar265fay.wpt, hwy_data/AR/usaus/ar.us082.wpt, hwy_data/AR/usausb/ar.us082sprcro.wpt, hwy_data/_systems/usaar.csv, hwy_data/_systems/usaar_con.csv, hwy_data/_systems/usausb.csv, hwy_data/_systems/usausb_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=4517
=> AR265 & US82SprCro

hwy_data/PA/usaus/pa.us030.wpt, hwy_data/PA/usaus/pa.us062.wpt
https://forum.travelmapping.net/index.php?topic=4528.0
Also removed unused alternate label on **US 30**.
=> US 62: MurRd>-MurDr

updates.csv
Updates item for changes in PR #5042
=> NM 181 updates

hwy_data/WV/usaus/wv.us035.wpt
https://forum.travelmapping.net/index.php?topic=4530.0
=> wv.us035: label correction

hwy_data/NJ/usanj/nj.nj140.wpt, hwy_data/NJ/usaus/nj.us040.wpt
The last couple changes to close out https://forum.travelmapping.net/index.php?topic=4010
=> NJ140 end label

hwy_data/TX/usatx/tx.tx095.wpt, hwy_data/TX/usaus/tx.us079.wpt, hwy_data/TX/usausb/tx.us079bustay.wpt, hwy_data/_systems/usausb.csv, hwy_data/_systems/usausb_con.csv, updates.csv
[Re: AASHTO approvals Spring 2019](https://forum.travelmapping.net/index.php?topic=3068.msg24523#msg24523)
[TX: US 79 Bus Taylor shown on the wrong route](https://forum.travelmapping.net/index.php?topic=3869)
=> TX US79BusTay deleted

hwy_data/TX/usai/tx.i030.wpt, hwy_data/TX/usatx/tx.tx360.wpt
https://forum.travelmapping.net/index.php?topic=4534
=> I-30/TX360

hwy_data/NE/usanp/ne.oldoretrl.wpt, hwy_data/NE/usanp/ne.sumrd.wpt, hwy_data/_systems/usanp.csv, hwy_data/_systems/usanp_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=4543
=> add NE SumRd

hwy_data/NJ/usanj/nj.nj031.wpt, hwy_data/NJ/usanj/nj.nj033.wpt, hwy_data/NJ/usanj/nj.nj071.wpt
https://forum.travelmapping.net/index.php?topic=4548
=> NJ: topic 4548

hwy_data/TX/usatxf/tx.fm0437.wpt, hwy_data/_systems/usatxf.csv, hwy_data/_systems/usatxf_con.csv
Leaving the .wpt around a bit longer just in case.
=> FM437Spr unsigned

updates.csv
=> MA I-395 renumbering updates entry

hwy_data/PA/usapa/pa.pa756.wpt
https://forum.travelmapping.net/index.php?topic=4138.msg25323#msg25323
=> PA 756: Relocating ScaAve for New Roundabout

hwy_data/OK/usai/ok.i044.wpt, hwy_data/OK/usaok/ok.ok066.wpt, hwy_data/OK/usaok/ok.ok364.wpt, hwy_data/OK/usaok/ok.ok412p.wpt, hwy_data/OK/usaus/ok.us412.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=4589
https://forum.travelmapping.net/index.php?topic=4590
=> OK412P realignment & I-44 exit numbers

hwy_data/CA/usaca/ca.ca259.wpt, hwy_data/NM/usai/nm.i010.wpt, hwy_data/NM/usaus/nm.us070.wpt, hwy_data/NM/usaus/nm.us085.wpt, hwy_data/NM/usaus/nm.us180.wpt, hwy_data/_systems/usaca.csv, hwy_data/_systems/usaca_con.csv
Misc NM label fixes in Las Cruces and Roswell. Also restores CA 259 to preview usaca system (no need for Updates table entry).
=> NM tweaks, add back CA 259

hwy_data/AR/usai/ar.i030.wpt, hwy_data/AR/usaus/ar.us067.wpt, hwy_data/AR/usaus/ar.us070.wpt
https://forum.travelmapping.net/index.php?topic=4597
=> AR I-30: double half interchanges @116

hwy_data/AR/usaar/ar.ar007.wpt, hwy_data/AR/usaar/ar.ar011.wpt, hwy_data/AR/usaar/ar.ar175.wpt, hwy_data/AR/usaar/ar.ar229.wpt, hwy_data/AR/usaus/ar.us070.wpt
https://forum.travelmapping.net/index.php?topic=4598
=> Operation Extraneous Suffix AR

hwy_data/PA/usapa/pa.pa054.wpt, hwy_data/PA/usapa/pa.pa152.wpt, hwy_data/PA/usapa/pa.pa390trkhaw.wpt, hwy_data/PA/usapa/pa.pa982trkder.wpt, hwy_data/PA/usaus/pa.us019.wpt, hwy_data/PA/usaus/pa.us040.wpt, hwy_data/PA/usaus/pa.us209.wpt
https://forum.travelmapping.net/index.php?topic=4598.msg25471#msg25471
(Also removed unused alternate labels on PA 54 and PA 152)
=> PA Label Cleanup 9-28-2021

hwy_data/TX/usatx/tx.tx158.wpt
https://forum.travelmapping.net/index.php?topic=65.msg25467#msg25467
=> break TX158/191 concurrency

hwy_data/NJ/usanj/nj.nj007.wpt, hwy_data/NJ/usausb/nj.us001trkjer.wpt, hwy_data/NJ/usausb/nj.us009trkjer.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=3061
=> Wittpenn Bridge

hwy_data/AR/usaar/ar.ar072.wpt, hwy_data/AR/usaar/ar.ar549bel.wpt, hwy_data/AR/usai/ar.i049.wpt, hwy_data/AR/usaif/ar.i049futbel.wpt, hwy_data/AR/usaus/ar.us071.wpt, hwy_data/IL/usai/il.i055.wpt, hwy_data/IL/usai/il.i064.wpt, hwy_data/IL/usail/il.il003.wpt, hwy_data/IL/usaus/il.us040.wpt, hwy_data/IL/usaus/il.us050.wpt, hwy_data/MO/usai/mo.i049.wpt, hwy_data/MO/usai/mo.i064.wpt, hwy_data/MO/usamo/mo.mo090.wpt, hwy_data/MO/usamo/mo.mo094.wpt, hwy_data/MO/usamo/mo.mo364.wpt, hwy_data/MO/usaus/mo.us040.wpt, hwy_data/MO/usaus/mo.us050.wpt, hwy_data/MO/usaus/mo.us071.wpt, hwy_data/SD/usai/sd.i090.wpt, hwy_data/_systems/usaar.csv, hwy_data/_systems/usaar_con.csv, hwy_data/_systems/usai.csv, hwy_data/_systems/usai_con.csv, hwy_data/_systems/usaif.csv, hwy_data/_systems/usaif_con.csv, updates.csv
siteupdate -e passed.
https://forum.travelmapping.net/index.php?topic=4314
https://forum.travelmapping.net/index.php?topic=4576
I'll post in the forum; let's get a thumbs-up from Highway63 before proceeding.
=> Bella Vista Bypass / STL area updates from Highway63

hwy_data/PA/usai/pa.i079.wpt, hwy_data/PA/usapa/pa.pa576.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=4088.0
=> Extending PA 576

hwy_data/PA/usai/pa.i079.wpt, hwy_data/PA/usapa/pa.pa519trkhou.wpt
=> Fixing PA 519 TRUCK (Houston)/I-79 Concurrency

hwy_data/PA/usapa/pa.pa028.wpt, hwy_data/PA/usaus/pa.us322.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=4230.0
=> US 322/PA 28: Slight Realignment in Brookville

hwy_data/PA/usaib/pa.i376blmoo.wpt, hwy_data/PA/usapa/pa.pa034.wpt, hwy_data/PA/usapa/pa.pa174.wpt
PA 34:  Added Ball Park Dr, Green Mountain Rd (GreMouRd), Bonnybrook Rd (BonRd), Sleepy Hollow Rd (SleHolRd), a shaping point, and Little Buffalo Rd (LitBufRd).
PA 174: Added Boonybrook Rd (BonRd), Peffer Rd (PefRd), and Hauck Rd (HauRd).
Also removed unused alternate label on I-376 BL (Moon).
=> PA 34 and PA 174 Revisions

hwy_data/TX/usaib/tx.i045blcor.wpt, hwy_data/TX/usatx/tx.tx022.wpt, hwy_data/TX/usatx/tx.tx031.wpt, hwy_data/TX/usatx/tx.tx031buscor.wpt, hwy_data/TX/usatx/tx.tx205.wpt, hwy_data/TX/usatx/tx.tx276.wpt, hwy_data/TX/usatxf/tx.fm0236.wpt, hwy_data/TX/usatxf2/tx.fm0709.wpt, hwy_data/TX/usatxf3/tx.fm1315.wpt, hwy_data/TX/usatxf4/tx.fm1685.wpt, hwy_data/TX/usatxf6/tx.fm2555.wpt, hwy_data/TX/usatxl/tx.lp0463.wpt, hwy_data/TX/usaus/tx.us077.wpt, hwy_data/TX/usaus/tx.us287.wpt, hwy_data/TX/usaus/tx.us290.wpt, hwy_data/TX/usaus/tx.us377.wpt, hwy_data/_systems/usatx.csv, hwy_data/_systems/usatx_con.csv, updates.csv
The Corsicana bypass opened a few months earlier than expected.
https://www.corsicanadailysun.com/news/economic-development-update-hwy-31-bypass-done-by-january-qt-to-open-soon/article_4210adfa-e177-11eb-99ff-dfbdbc997110.html
https://www.corsicanadailysun.com/news/message-from-the-mayor-hwy-31-relief-route-to-open-soon/article_217a429e-2c46-11ec-a103-ef67293de490.html#tncms-source=block-contextual-fallback
https://www.corsicanadailysun.com/news/highway-31-relief-route-opens-thursday/article_9ad68560-32b0-11ec-8a8d-f3d914f8c8b1.html
Ping @queenwsx @freakwentflier @jonfmorse @mapcat @ovoss @ryangentry @ua747sp
Relocated at west end, begging for a relocation of the TX276 point on TX205.
Ping @Duke87ofST @mrpoodlepants
=> TX31 & TX276 relocations

hwy_data/TX/usai/tx.i045.wpt
GMSV: [NB](https://www.google.com/maps/@32.0336384,-96.4440281,3a,15y,354.74h,89.27t/data=!3m7!1e1!3m5!1sxCQla5puxAAzSls0_YWVew!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fpanoid%3DxCQla5puxAAzSls0_YWVew%26cb_client%3Dmaps_sv.tactile.gps%26w%3D203%26h%3D100%26yaw%3D80.63611%26pitch%3D0%26thumbfov%3D100!7i16384!8i8192) [SB](https://www.google.com/maps/@32.0514865,-96.4496341,3a,75y,204.04h,88.41t/data=!3m9!1e1!3m7!1s2hCmi0F83oMuA4HgQyYsSg!2e0!7i16384!8i8192!9m2!1b1!2i40)
=> TX I-45 227

hwy_data/OK/usai/ok.i044.wpt, hwy_data/OK/usaok/ok.ok004.wpt, hwy_data/OK/usaok/ok.ok076.wpt, hwy_data/OK/usasf/ok.norspurtpk.wpt, hwy_data/OK/usaus/ok.us062.wpt, hwy_data/OK/usaus/ok.us277.wpt, hwy_data/_systems/usaok.csv, hwy_data/_systems/usasf.csv, hwy_data/_systems/usasf_con.csv, updates.csv
https://www.aaroads.com/forum/index.php?topic=18359.msg2678355#msg2678355
=> NorSpurTpk -> OK4

hwy_data/PA/usapa/pa.pa031trkman.wpt, hwy_data/PA/usapa/pa.pa056.wpt, hwy_data/PA/usapa/pa.pa096trkman.wpt, hwy_data/PA/usapa/pa.pa756.wpt, hwy_data/_systems/usapa.csv, hwy_data/_systems/usapa_con.csv, updates.csv
Other Changes:
PA 31 TRUCK (Manns Choice): Fixing Broken Concurrency With US 30.
PA 56: Replaced +X10 with Clear Shade Wild Area (CleShaWA).
PA 96 TRUCK (Manns Choice): Added route (https://forum.travelmapping.net/index.php?topic=4216.msg25923#msg25923).
=> PA 756 Realignment West of PA 160

hwy_data/WV/usaus/wv.us035.wpt, hwy_data/WV/usawv/wv.wv131.wpt, hwy_data/WV/usawv/wv.wv279.wpt, hwy_data/WV/usawv/wv.wv817.wpt, hwy_data/WV/usawv/wv.wv892.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=4387.0
https://forum.travelmapping.net/index.php?topic=4572.0 (partial)
=> usawv: New US-35 alignment + other tweaks

hwy_data/MO/usaush/mo.us066hisflo.wpt, updates.csv
=> US 66 Historic (Flo): Recentered I-44 to match US 61/US 67

hwy_data/PA/usapa/pa.pa136.wpt, updates.csv
Extended east from US 30 to Hamilton Ave (HamAve). (https://forum.travelmapping.net/index.php?topic=4630.msg25921#msg25921)  Removed +X0 and ThoSchRd.
=> PA 136: Point Revisions

hwy_data/WV/usaus/wv.us220.wpt, hwy_data/WV/usawv/wv.wv014.wpt, hwy_data/WV/usawv/wv.wv028.wpt, hwy_data/WV/usawv/wv.wv031.wpt, hwy_data/WV/usawv/wv.wv055.wpt
https://forum.travelmapping.net/index.php?topic=4572.0
=> WV: US-220 corridor cleanup

hwy_data/PA/usapa/pa.pa064.wpt, hwy_data/PA/usapa/pa.pa550.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=4669.0
PA 550:  Removed JulPike and ForAve.
=> PA 550 Realignment at PA 64

hwy_data/NJ/usanj/nj.nj007.wpt, hwy_data/NJ/usanj/nj.nj007nut.wpt, hwy_data/NJ/usanj/nj.nj052.wpt, hwy_data/_systems/usanj.csv, hwy_data/_systems/usanj_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=4628
https://forum.travelmapping.net/index.php?topic=4678
=> NJ7 merged; NJ52 end label

hwy_data/NE/usai/ne.i076.wpt, hwy_data/NE/usai/ne.i080.wpt
https://forum.travelmapping.net/index.php?topic=4683
=> NE: I-76/80

hwy_data/KS/usaus/ks.us054.wpt, hwy_data/KS/usaus/ks.us160.wpt, hwy_data/OK/usaok/ok.ok022.wpt, hwy_data/OK/usaok/ok.ok078.wpt, hwy_data/OK/usaus/ok.us060.wpt, hwy_data/OK/usaus/ok.us062.wpt
Early Google coords (from what like TIGER or whatever?) strike again.
These coordinates were pretty precise if you look at the intersection layout before... [before 1981](https://historicaerials.com/location/37.285851/-100.315808/1965/18).
=> US54_E/US160_E recentering / OK city suffixes

hwy_data/CT/usact/ct.ct015.wpt, hwy_data/CT/usaus/ct.us001.wpt, hwy_data/MA/usama/ma.ma001asal.wpt, hwy_data/MA/usama/ma.ma009.wpt, hwy_data/MA/usama/ma.ma030.wpt, hwy_data/MA/usaus/ma.us202.wpt, hwy_data/NH/usanh/nh.nh009.wpt, hwy_data/NH/usanh/nh.nh011.wpt, hwy_data/NH/usanh/nh.nh011a.wpt, hwy_data/NH/usanh/nh.nh028.wpt, hwy_data/NH/usanh/nh.nh107.wpt, hwy_data/NH/usausb/nh.us003buslac.wpt, hwy_data/RI/usari/ri.ri001a.wpt
=> New England city suffixes

hwy_data/ME/usame/me.me004.wpt, hwy_data/ME/usame/me.me005.wpt, hwy_data/ME/usame/me.me006.wpt, hwy_data/ME/usame/me.me011.wpt, hwy_data/ME/usame/me.me015.wpt, hwy_data/ME/usame/me.me024busbru.wpt, hwy_data/ME/usame/me.me035.wpt, hwy_data/ME/usame/me.me043.wpt, hwy_data/ME/usame/me.me100.wpt, hwy_data/ME/usame/me.me103.wpt, hwy_data/ME/usame/me.me104.wpt, hwy_data/ME/usame/me.me112.wpt, hwy_data/ME/usame/me.me117.wpt, hwy_data/ME/usame/me.me121.wpt, hwy_data/ME/usame/me.me148.wpt, hwy_data/ME/usame/me.me155.wpt, hwy_data/ME/usame/me.me160.wpt, hwy_data/ME/usame/me.me172.wpt, hwy_data/ME/usame/me.me175.wpt, hwy_data/ME/usame/me.me236.wpt, hwy_data/ME/usaus/me.us002.wpt, hwy_data/ME/usaus/me.us201.wpt, hwy_data/ME/usaus/me.us202.wpt
In case I ever want to use this again:
```sh
( echo "sed \\"
for file in $(git diff --name-only | grep -v busbru); do
rte=$(echo $file | cut -f2 -d. | sed -e 's~^me0*~ME~' -e 's~^us0*~US~')
for pair in $(paste -d% \
<(git diff $file | grep '^-' | tail -n +2 | cut -f1 -d' ' | sed 's~.~~') \
<(git diff $file | grep '^+' | tail -n +2 | cut -f1 -d' ' | sed 's~.~~')); do
old=$(echo $pair | cut -f1 -d%)
new=$(echo $pair | cut -f2 -d%)
echo -n "-e 's~ME $rte $old ~ME $rte $new ~' "
echo -n "-e 's~ME $rte \(..*\) $old$~ME $rte \1 $new~' "
echo    "-e 's~ME $rte \(..*\) $old \(.*\)$~ME $rte \1 $new \2~' \\"
done
done
echo ~/ytm/UserData/list_files/yakra.list '>' ~/ytm/UserData/list_files/yakra2.list
echo mv ~/ytm/UserData/list_files/yakra2.list ~/ytm/UserData/list_files/yakra.list
) > yakra.sh
``` …
=> ME city suffixes

hwy_data/NY/usaus/ny.us009.wpt
https://forum.travelmapping.net/index.php?topic=4694
=> NY US9 CR63

hwy_data/ROU/eure/rou.e70.wpt, hwy_data/ROU/roudn/rou.dn006.wpt, hwy_data/ROU/roudn/rou.dn06h.wpt, hwy_data/_systems/roudn.csv, hwy_data/_systems/roudn_con.csv, updates.csv
=> ROU DN6H (Mihailesti Bypass) opened

hwy_data/NE/usanes/ne.l55k.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=4699
=> extend L55K

hwy_data/PA/usai/pa.i083.wpt, hwy_data/PA/usapa/pa.pa291.wpt, hwy_data/PA/usapa/pa.pa851.wpt
PA 851: Added HillSt_S.
PA 291: Removed Unused Alternate Label.
=> I-83/PA 851 Recentering at DDI

hwy_data/PA/usai/pa.i376.wpt, hwy_data/PA/usaus/pa.us022.wpt, hwy_data/PA/usaus/pa.us030.wpt
The new project currently in design for the I-376/US 22/US 30/PA 60 interchange turns this interchange into a DDI, and allows for the I-376 WB to PA 60 SB movement at the interchange.  There are no plans to close Exit 60B on I-376 WB so it technically would then become its own interchange.
=> I-376: Added 60B.

hwy_data/PA/usapa/pa.pa286trkind.wpt
=> PA 286 TRUCK (Indiana): Fixing US 422/PA 56 Broken Concurrency

hwy_data/MN/usamn/mn.mn056.wpt, hwy_data/MN/usamn/mn.mn111.wpt, hwy_data/MN/usaus/mn.us014.wpt, hwy_data/MN/usausb/mn.us014busdod.wpt, updates.csv
Changes related to US 14 being relocated onto new alignment between Owatonna and Dodge Center
=> MN:  US 14 Owatonna - Dodge Center

hwy_data/HUN/hunm/hun.m044.wpt, hwy_data/HUN/hunm/hun.m085.wpt, updates.csv
M44 opened between Tiszakurt and Lakitelek
=> HUN M44 opening

hwy_data/TX/usai/tx.i069e.wpt, hwy_data/TX/usatx/tx.tx021.wpt, hwy_data/TX/usaus/tx.us062.wpt, hwy_data/TX/usaus/tx.us062elp.wpt, hwy_data/TX/usaus/tx.us077.wpt, hwy_data/TX/usaus/tx.us082.wpt, hwy_data/TX/usaus/tx.us180elp.wpt, updates.csv
...and other minor changes.
It's possible that I-69E extends N of Yturria Co Rd, maybe even almost halfway across Kenedy County. I'll extend northward as more shields are confirmed.
=> 3 more miles of I-69E

hwy_data/ROU/eure/rou.e70.wpt, hwy_data/ROU/roudn/rou.dn005.wpt, hwy_data/ROU/roudn/rou.dn05d.wpt, hwy_data/_systems/roudn.csv, hwy_data/_systems/roudn_con.csv, updates.csv
=> ROU DN5D (Giurgiu Bypass) opened

hwy_data/QC/canqc/qc.qc185.wpt, hwy_data/QC/canqc/qc.qc291.wpt, hwy_data/QC/cantch/qc.tchmai.wpt
Relocation of short QC 185 segment, which also affects TCH (Main) and QC 291. Discussed on forum.
Datacheck successful. Edits to Updates table to be made in separate pull request.
=> QC185 relocation

hwy_data/NY/usai/ny.i295.wpt, hwy_data/NY/usany/ny.ny023.wpt, hwy_data/NY/usany/ny.ny024.wpt, hwy_data/NY/usany/ny.ny025.wpt, hwy_data/NY/usany/ny.ny106.wpt, hwy_data/NY/usany/ny.ny182.wpt, hwy_data/NY/usaus/ny.us062.wpt
https://forum.travelmapping.net/index.php?topic=4635
https://forum.travelmapping.net/index.php?topic=4636
https://forum.travelmapping.net/index.php?topic=4765
https://forum.travelmapping.net/index.php?topic=4766
https://forum.travelmapping.net/index.php?topic=4767
=> NY forum items, 2021-12-30

hwy_data/TX/usai/tx.i069.wpt, hwy_data/TX/usatxs/tx.sp0529.wpt, hwy_data/TX/usaus/tx.us059.wpt, updates.csv
...by a whopping quarter mile!
=> Extend TX I-69 to Exit 94

hwy_data/CT/usact/ct.ct082.wpt, hwy_data/CT/usact/ct.ct148lym.wpt
https://forum.travelmapping.net/index.php?topic=4784
=> Gillette Castle SP

hwy_data/OK/usaok/ok.ok036.wpt
https://forum.travelmapping.net/index.php?topic=4788
=> resync OK36 I-44(30)

hwy_data/PA/usai/pa.i084.wpt, hwy_data/PA/usapa/pa.pa402.wpt, hwy_data/PA/usapa/pa.pa402trkhaw.wpt, hwy_data/PA/usapa/pa.pa655.wpt
Also removed alternate label on PA 655
=> PA 402: Recentering Again

hwy_data/PA/usai/pa.i084.wpt, hwy_data/PA/usapa/pa.pa028.wpt, hwy_data/PA/usapa/pa.pa066.wpt, hwy_data/PA/usapa/pa.pa390trkhaw.wpt, hwy_data/PA/usapa/pa.pa402trkhaw.wpt
Also removed shaping point on I-84.  (fixes from PR #5518)
It is even easy for me to break a concurrency.
=> Fixing I-84/PA 402 TRUCK/PA 390 TRUCK Broken Concurrencies from PR #5518

updates.csv
https://github.com/TravelMapping/HighwayData/pull/5519#issuecomment-1013117642
=> remove vestigial tx.sp0379

hwy_data/NY/usany/ny.ny878far.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=4629
=> extend NY878Far

hwy_data/CA/usaca/ca.ca139.wpt, hwy_data/CA/usaca/ca.ca161.wpt, hwy_data/CA/usai/ca.i680.wpt, hwy_data/NM/usai/nm.i040.wpt, hwy_data/NM/usaus/nm.us070.wpt, hwy_data/NM/usaush/nm.us066hisabq.wpt
In NM, new/relocated points on I-40 in Albuquerque, and label fix on US 70 in Las Cruces, per forum discussion, Also some NMP fixes in CA.
@si404, one of the I-40 tweaks requires a conforming change to US66HisAbq, which is included in this PR.
=> NM and CA tweaks

systems.csv, systemupdates.csv
53% of Japan national highways are now in preview
=> Promote Tohoku roads in jpnh to preview

hwy_data/PA/usapa/pa.pa045trkspr.wpt, hwy_data/PA/usapa/pa.pa217.wpt, hwy_data/PA/usapa/pa.pa381.wpt, hwy_data/PA/usapa/pa.pa550.wpt, hwy_data/PA/usapa/pa.pa711.wpt
PA 45 TRUCK (Spruce Creek)/PA 550: Relocated StiRd.
PA 217:  LatDerRd>-IndBlvd.
PA 381:  Removed shaping points, KooRd, and WashRunRd.
PA 711:  StaRd>-ThaRd.  ShaCreRd_S>-ShaCreRd_N.  Removed shaping points, WashRunRd, and ShaCreRd_N.
=> Point Revisions 2-4-2022

hwy_data/TX/usatxf4/tx.fm1516.wpt, hwy_data/TX/usatxf4/tx.fm1976.wpt, hwy_data/TX/usatxl/tx.lp0368.wpt, updates.csv
https://ftp.txdot.gov/pub/txdot/commission/2022/0127/9.pdf
https://forum.travelmapping.net/index.php?topic=3076.msg26866#msg26866
=> re-extend TXLp368 

hwy_data/PA/usapa/pa.pa320.wpt, hwy_data/PA/usapa/pa.pa352.wpt, hwy_data/PA/usaus/pa.us013.wpt, hwy_data/PA/usaus/pa.us322.wpt
https://forum.travelmapping.net/index.php?topic=4804.msg26926#msg26926
=> Fixing Labels Related to US 13 Reroute in Chester

hwy_data/NJ/usanj/nj.nj018.wpt, hwy_data/NJ/usanj/nj.nj021.wpt, hwy_data/NJ/usanj/nj.nj044.wpt, hwy_data/NJ/usanj/nj.nj156.wpt, hwy_data/NJ/usanj/nj.nj172.wpt, hwy_data/NJ/usaus/nj.us001.wpt, hwy_data/NJ/usaus/nj.us130.wpt
https://forum.travelmapping.net/index.php?topic=4821
=> NJ: topic 4821

hwy_data/NY/usany/ny.ny059.wpt, hwy_data/NY/usany/ny.ny100c.wpt, hwy_data/NY/usany/ny.ny303.wpt, hwy_data/NY/usany/ny.ny304.wpt
https://forum.travelmapping.net/index.php?topic=4821
=> NY: topic 4821

hwy_data/WV/usawv/wv.wv046.wpt, hwy_data/WV/usawv/wv.wv090.wpt, hwy_data/WV/usawv/wv.wv115.wpt, hwy_data/WV/usawv/wv.wv230.wpt
https://forum.travelmapping.net/index.php?topic=4734.0
=> usawv: label cleanup

hwy_data/TX/usai/tx.i035.wpt, hwy_data/TX/usaus/tx.us083.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=4834
=> extend I-35 to Hidalgo St

hwy_data/NY/usai/ny.i278.wpt, hwy_data/NY/usany/ny.ny340.wpt
and delete NY340 PieAve; was mentioned on the forum somewhere
=> NY I-278: recenter NJ/NY

hwy_data/GA/usaga/ga.ga014sprlag.wpt, hwy_data/GA/usaga/ga.ga017.wpt, updates.csv
GA 14 Spr truncation. GA17 point rename.
=> Minor GA updates

hwy_data/HI/usanp/hi.crarimdr.wpt
Per forum discussion. Datacheck sucessful.
Updates table entry in PR #5662.
=> HI: Crater Rim Drive extension

updates.csv
=> Fixing US 84 and GA 38 Update Typos

hwy_data/AL/usaal/al.al021.wpt, hwy_data/AL/usaal/al.al041.wpt, hwy_data/AL/usaal/al.al069.wpt, hwy_data/AL/usai/al.i359.wpt, hwy_data/AL/usaus/al.us043.wpt, updates.csv
Corrections to my update from the other day, as well as revising the I-359 endpoint under 1PPI.
=> More Alabama fixes

updates.csv
@ajfroggie   Just doing this now since I noticed it for US231BusOza and I do not want it to get lost in case you do not make any more updates for a while.
=> Removing AL Update Roots for Deleted Routes.

hwy_data/MB/canmb/mb.mb075.wpt, hwy_data/MB/canmbp/mb.mb200.wpt
https://forum.travelmapping.net/index.php?topic=4868
=> MB200 realignment

hwy_data/JPN/jpne/jpn.e001a.wpt, hwy_data/JPN/jpne/jpn.e070.wpt, hwy_data/JPN/jpne/jpn.e070izu.wpt
Add E1A exit 3-1 
Modify E70 wp names
=> Add E1A exit 3-1

hwy_data/PA/usapa/pa.pa113.wpt, hwy_data/PA/usapa/pa.pa715.wpt
PA 113:  FriValRd>-FreValRd.
PA 715:  Replaced +X1 with HayRd.
=> PA 113 and PA 715 Revisions

hwy_data/NJ/usanj/nj.nj124.wpt
https://forum.travelmapping.net/index.php?topic=4898
=> NJ124 graph connection @ JFKenPkwy

hwy_data/NY/usai/ny.i086bin.wpt, hwy_data/NY/usaif/ny.i086futbin.wpt, hwy_data/NY/usany/ny.ny009a.wpt, hwy_data/NY/usany/ny.ny017bin.wpt, hwy_data/NY/usany/ny.ny025.wpt, hwy_data/NY/usany/ny.ny025a.wpt, hwy_data/NY/usany/ny.ny030.wpt, hwy_data/NY/usasf/ny.tacstapkwy.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=4866
https://forum.travelmapping.net/index.php?topic=4897
=> I-81/86 olap / NY25/25A jct

hwy_data/CA/usaca/ca.ca175.wpt, hwy_data/CA/usai/ca.i105.wpt, hwy_data/CA/usai/ca.i780.wpt
I-105 eastern extension; I-780 western extension; also tweaks (per forum) to preview CA 175.
Datacheck successful. Updates items for I-105 and I-780 in PR#5733.
=> CA: Interstate dangling ends, CA 175 tweaks

hwy_data/KY/usausb/ky.us027buscyn.wpt, hwy_data/OH/usaus/oh.us030.wpt
https://forum.travelmapping.net/index.php?topic=4923.0
=> OH & KY point labels

hwy_data/CT/usact/ct.ct109.wpt, hwy_data/CT/usact/ct.ct317.wpt, hwy_data/CT/usaus/ct.us006.wpt, hwy_data/CT/usaus/ct.us202.wpt, hwy_data/MA/usai/ma.i090.wpt, hwy_data/MA/usama/ma.ma128.wpt
https://forum.travelmapping.net/index.php?topic=4954
=> CT: topic 4954

hwy_data/NY/usany/ny.ny096b.wpt
https://forum.travelmapping.net/index.php?topic=4966
=> NY96B AluCir

hwy_data/TX/usatx/tx.tx099.wpt, hwy_data/TX/usatx/tx.tx099bay.wpt, hwy_data/TX/usatx/tx.tx146.wpt, hwy_data/TX/usatxf2/tx.fm0565.wpt, hwy_data/TX/usatxf2/tx.fm0686.wpt, hwy_data/TX/usatxf3/tx.fm1413.wpt, hwy_data/TX/usatxf3/tx.fm1485.wpt, hwy_data/TX/usatxf4/tx.fm1960.wpt, hwy_data/TX/usatxl/tx.lp0494.wpt, hwy_data/TX/usaus/tx.us090.wpt, hwy_data/_systems/usatx.csv, hwy_data/_systems/usatx_con.csv, updates.csv
May or may not want to extend this a little farther, concurrent with TX146Bus to TX146.
Holding off till there's newer imagery there.
=> TX99 Segments H and I-1

hwy_data/NV/usanv/nv.nv518.wpt, hwy_data/_systems/usanv.csv, hwy_data/_systems/usanv_con.csv
In Carson City, per forum discussion.
Updates table entry to follow in separate pull request. Datacheck successful.
=> Remove NV518

hwy_data/ON/canon/on.on011.wpt, hwy_data/ON/canon/on.on071.wpt, hwy_data/ON/canon/on.on137.wpt, hwy_data/ON/canonf/on.on405.wpt
https://forum.travelmapping.net/index.php?topic=3754.15
=> canon: fix USA border labels

hwy_data/NY/usai/ny.i295.wpt
https://forum.travelmapping.net/index.php?topic=5020
=> NY I-295 exits 9 & 12

hwy_data/JPN/jpnh/jpn.n339kai.wpt, hwy_data/JPN/jpnh/jpn.n339sot.wpt
Points from these files were merged into N339.
=> Remove obsolete N339 files

hwy_data/AK/usaak/ak.ak011.wpt
Discussed on forum. Datacheck successful.
=> AK 11 point request

hwy_data/TX/usatx/tx.tx063.wpt, hwy_data/TX/usaus/tx.us069.wpt, updates.csv
https://www.kltv.com/video/2022/06/25/us-overpass-kltv-news-pm-/
Ping @Duke87ofST @mapcat @ovoss @mbeller2016
=> US69 Zavalla

hwy_data/PA/usapa/pa.pa403.wpt, hwy_data/PA/usapa/pa.pa985.wpt
PA 403: Removed +X6R.
PA 985: Replaced +X1 with Old Somerset Pike (OldSomPike).  FraSt>-FraSt_N.
=> PA Updates 7-2-2022

hwy_data/MN/usaus/mn.us052.wpt
Correcting broken concurrency along I-94/US 52.
=> Correcting broken concurrency along MN I-94/US 52

hwy_data/PA/usapa/pa.pa044.wpt, hwy_data/PA/usapa/pa.pa049.wpt, hwy_data/PA/usapa/pa.pa405.wpt, hwy_data/PA/usapa/pa.pa654.wpt, hwy_data/PA/usapa/pa.pa880.wpt
PA 44: Removed PepRd.  Added Bell Run Rd.
PA 49:  Removed Unused Alternate Label.
PA 405: Removed +X0R.
PA 654: Removed +X3.
PA 880: Removed +X2.  Added Gottshall Rd (GotRd).
=> Minor PA Updates 7-10-2022

hwy_data/CO/usaco/co.co109trklaj.wpt, hwy_data/_systems/usamt.csv
Sorry about that, thought I could link the upgraded route with the old route
=> fix for #5913

hwy_data/VT/usavt/vt.vt007a.wpt, hwy_data/VT/usavt/vt.vt011.wpt, hwy_data/VT/usavt/vt.vt030.wpt
Cleaning up points in Manchester and adding missing VT 30 point along VT 7A concurrency.
=> VT:  Manchester Malfunction Junction cleanup

hwy_data/AR/usaar/ar.ar463pin.wpt, hwy_data/AR/usaus/ar.us071.wpt, hwy_data/AR/usausb/ar.us063buspin.wpt, hwy_data/_systems/usaar.csv, hwy_data/_systems/usaar_con.csv, hwy_data/_systems/usausb.csv, hwy_data/_systems/usausb_con.csv, updates.csv
=> US63BusPin -> AR463Pin

hwy_data/ON/cannf/on.linalepkwy.wpt, hwy_data/ON/cannf/on.redhillpkwy.wpt
https://forum.travelmapping.net/index.php?topic=30.msg28495#msg28495
< no update entry needed due to system not being active yet >
=> cannf: Fix start/end points for linalepkwy/redhillpkwy.

hwy_data/CT/usact/ct.ct035.wpt, hwy_data/CT/usact/ct.ct116.wpt, hwy_data/CT/usai/ct.i084.wpt, hwy_data/NY/usany/ny.ny006n.wpt, hwy_data/NY/usany/ny.ny009a.wpt, hwy_data/NY/usany/ny.ny012f.wpt, hwy_data/NY/usany/ny.ny016.wpt, hwy_data/NY/usany/ny.ny035.wpt, hwy_data/NY/usany/ny.ny074.wpt, hwy_data/NY/usany/ny.ny100.wpt, hwy_data/NY/usany/ny.ny116.wpt, hwy_data/NY/usany/ny.ny121.wpt, hwy_data/NY/usany/ny.ny123.wpt, hwy_data/NY/usany/ny.ny207.wpt, hwy_data/NY/usasf/ny.sawmillpkwy.wpt, hwy_data/NY/usasf/ny.tacstapkwy.wpt, hwy_data/NY/usaus/ny.us006.wpt, hwy_data/NY/usaus/ny.us009.wpt
https://forum.travelmapping.net/index.php?topic=5111
Ping @ajfroggie -- NY74's endpoint changed `NY/VT` -> `TicFry`; suggest doing same on VT74.
=> NY/CT: topic 5111

hwy_data/FL/usafl/fl.fl005jac.wpt, hwy_data/FL/usafl/fl.fl399.wpt, hwy_data/FL/usaus/fl.us001.wpt, hwy_data/FL/usaus/fl.us090.wpt, hwy_data/_systems/usafl.csv, hwy_data/_systems/usafl_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=4789.0
https://forum.travelmapping.net/index.php?topic=4484.msg24759#msg24759
=> usafl: FL-399 & FL-5Jac changes

hwy_data/PA/usaif/pa.i099futman.wpt, hwy_data/PA/usapa/pa.pa028.wpt, hwy_data/PA/usapa/pa.pa044.wpt, hwy_data/PA/usapa/pa.pa088.wpt, hwy_data/PA/usapa/pa.pa346.wpt, hwy_data/PA/usapa/pa.pa501.wpt, hwy_data/PA/usaus/pa.us013.wpt, hwy_data/PA/usaus/pa.us222.wpt
PA 44:  Relocated HebRd.  SteSt>-SteSt_N.  OswSt>-OswSt_S.
Also removed unused alternate labels on I-99 FUT (Mansfield), PA 28, PA 88, PA 346, PA 501, US 13, and US 222.
=> PA 44: Minor Point Revisions

hwy_data/FL/usafl/fl.fl062.wpt, hwy_data/FL/usafl/fl.fl064.wpt, hwy_data/FL/usaus/fl.us041.wpt, hwy_data/FL/usaus/fl.us098.wpt
Point additions.
https://forum.travelmapping.net/index.php?topic=4251.0
=> usafl: minor tweaks

hwy_data/PA/usapa/pa.pa008trktit.wpt, hwy_data/PA/usapa/pa.pa027trktit.wpt
https://www.penndot.pa.gov/regionaloffices/district-1/pages/details.aspx?newsid=1922
The S Perry St bridge over Oil Creek is being removed and will not be replaced.
=> PA 8 TRUCK (Titusville)/PA 27 TRUCK (Titusville):  PerSt_S>-*PerSt_S

hwy_data/NY/usasf/ny.tacstapkwy.wpt
[https://forum.travelmapping.net/index.php?topic=5111.0](url)
It has been a few weeks and no action has been taken to fix this point yet.
=> Fix CR10 waypoint on TacStaPkwy

hwy_data/PA/usapa/pa.pa611.wpt, hwy_data/PA/usapa/pa.pa715trksta.wpt
Added Pattison Ave (PatAve). (for @ovoss)  ParRd>-ParkRd.  *Replaced +X9B with Oltmans-Strasse Rd (OltStrRd).
*Also done on PA 715 TRUCK ((South) Tannersville)
=> PA 611 Revisions

hwy_data/PA/usai/pa.i095.wpt, hwy_data/PA/usapa/pa.pa029.wpt, hwy_data/PA/usapa/pa.pa462.wpt, hwy_data/PA/usasf/pa.betrossbri.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5154.0
Other Revisions:
PA 29:  Removed Unused Alternate Label.  SR3004>-StrHillRd.
PA 462:  Removed Unused Alternate Label.
=> Betsy Ross Bridge Extension

hwy_data/CA/usaca/ca.ca004.wpt, hwy_data/CA/usaca/ca.ca020.wpt, hwy_data/CA/usaca/ca.ca039azu.wpt, hwy_data/CA/usaca/ca.ca071.wpt, hwy_data/CA/usaca/ca.ca099busmod.wpt, hwy_data/CA/usaca/ca.ca108.wpt, hwy_data/CA/usaca/ca.ca116.wpt, hwy_data/CA/usaca/ca.ca132.wpt, hwy_data/CA/usaca/ca.ca162.wpt, hwy_data/CA/usaus/ca.us101.wpt, hwy_data/NM/usanm/nm.nm095.wpt, hwy_data/NM/usanm/nm.nm177.wpt, hwy_data/NM/usanm/nm.nm195ele.wpt, hwy_data/NM/usanm/nm.nm572.wpt, hwy_data/_systems/usanm.csv, hwy_data/_systems/usanm_con.csv
Truncation and NM changes discussed on forum. Other fixes to usaca routes.
Updates items to be in separate pull request, once this one clears Datacheck.
=> CA US101 truncation, other CA and NM changes

hwy_data/CA/usaca/ca.ca004.wpt, hwy_data/CA/usaca/ca.ca099busmad.wpt, hwy_data/CA/usaca/ca.ca162oro.wpt, hwy_data/NV/usanv/nv.nv156.wpt, hwy_data/NV/usanv/nv.nv157.wpt, hwy_data/NV/usanv/nv.nv158.wpt
No Updates items needed (minor NV changes, usaca is preview system).
=> NV datacheck fixes, more usaca tweaks

hwy_data/TX/usai/tx.i037.wpt, hwy_data/TX/usaus/tx.us181.wpt
https://forum.travelmapping.net/index.php?topic=5084
=> I-37 / TXSpr122 connection

hwy_data/CA/usaca/ca.ca001.wpt, hwy_data/CA/usaca/ca.ca004busang.wpt, hwy_data/CA/usaca/ca.ca138.wpt, hwy_data/CA/usaca/ca.ca140.wpt, hwy_data/CA/usaca/ca.ca254.wpt, hwy_data/CA/usanp/ca.kincanrd.wpt, hwy_data/CA/usaus/ca.us101.wpt
=> NMP, concurrency, other usaca fixes

updates.csv
fix for https://github.com/TravelMapping/HighwayData/commit/8f8e36922ae7052cd0b955380c7b88fc687d9fe9
=> fix updates.csv

hwy_data/NV/usausb/nv.us006busely.wpt, hwy_data/_systems/usausb.csv, hwy_data/_systems/usausb_con.csv
Datacheck successful (looks like problem with PR #6065 was fixed). PR for Updates table edit to follow.
=> Delete US 6 Bus in Ely NV

hwy_data/BC/canbc/bc.bc007.wpt, hwy_data/BC/canbc/bc.bc007b.wpt
Discussed in BC NMPs topic on forum. Main change is reroute to BC 7B's west end. Conforming changes and other tweaks to BC 7.
Updates item for BC 7B reroute in PR #6095.
=> BC NMPs fix

hwy_data/ROU/eure/rou.e671.wpt, hwy_data/ROU/eure/rou.e81.wpt, hwy_data/ROU/roudj/rou.dj194.wpt, hwy_data/ROU/roudn/rou.dn019.wpt, hwy_data/ROU/roudn/rou.dn19a.wpt, hwy_data/ROU/roudn/rou.dn19h.wpt, hwy_data/_systems/roudn.csv, hwy_data/_systems/roudn_con.csv, updates.csv
=> Satu Mare Bypass

hwy_data/PA/usapa/pa.pa005.wpt, hwy_data/PA/usapa/pa.pa027.wpt, hwy_data/PA/usapa/pa.pa069.wpt, hwy_data/PA/usapa/pa.pa089.wpt, hwy_data/PA/usapa/pa.pa290.wpt, hwy_data/PA/usapa/pa.pa427.wpt, hwy_data/PA/usapa/pa.pa430.wpt, hwy_data/PA/usapa/pa.pa531.wpt, hwy_data/PA/usapa/pa.pa832.wpt
Only slight recentering unless mentioned below:
PA 5/PA 290: I-79/5>-I-79. GreRd>-GreBlvd.
PA 27: GuysMillRd>-GuysMilRd.  Pa27TrkTit_N>-PA27TrkTit.
PA 832: Added Rick Rd.
=> PA Revisions 10-26-2022

hwy_data/CT/usai/ct.i084.wpt
https://forum.travelmapping.net/index.php?topic=5111.msg29633#msg29633
=> Waterbury exit number tweaks

hwy_data/TUR/turd/tur.d160.wpt, hwy_data/TUR/turd/tur.d230.wpt, hwy_data/TUR/turd/tur.d595.wpt, updates.csv
=> TUR D160 and D595

hwy_data/ROU/eure/rou.e584.wpt, hwy_data/ROU/roudn/rou.dn15b.wpt
the 2 romanian labels are corrected
=> ROU labels

hwy_data/PA/usapa/pa.pa061trknsu.wpt
https://forum.travelmapping.net/index.php?topic=5276.0
=> PA 61 TRUCK (Sunbury-North): Fixed Labels

hwy_data/CT/usact/ct.ct010.wpt, hwy_data/CT/usact/ct.ct022.wpt, hwy_data/CT/usact/ct.ct040.wpt, hwy_data/RI/usai/ri.i095.wpt, hwy_data/RI/usari/ri.ri003.wpt, hwy_data/RI/usari/ri.ri010.wpt, hwy_data/RI/usaus/ri.us001.wpt, hwy_data/RI/usaus/ri.us006.wpt, updates.csv
29 27 21 19 18 14 9
a3 ajgrigg91 baugh17 bejacob ben114 bhemphill crosboro7 cvoight dantheman dy670 flroads Ib3kii imgoph jjbers jonsamuels jt2022 lakewy17 navigator neroute2 noelbotevera nrm1221 NWI_Irish96 pnrrth rebelgtp regoarrarr RMA58 scott_stieglitz sipes23 skoutr1 sneezy tikester whopperman
bejacob ben114 dy670 flroads jjbers jonsamuels navigator neroute2 pnrrth rebelgtp sipes23
@bejacob @eliotchase @TNT670 @flroads @jjbers @JonSamuels @measuren @neroute2 @pnrrth @rebelgtp @sipes23 
a3 ajgrigg91 baugh17 bhemphill crosboro7 cvoight dantheman Ib3kii imgoph jt2022 lakewy17 …
=> RI I-95 exit renumbering

hwy_data/HUN/hunf/hun.f071.wpt, hwy_data/HUN/hunf/hun.f076.wpt, hwy_data/HUN/hunm/hun.m076.wpt, updates.csv
=> HUN M76 extension added

hwy_data/KS/usaus/ks.us036.wpt, hwy_data/NE/usaus/ne.us136.wpt, hwy_data/_systems/usai.csv
central states dashboard 2022-11-19
=> central states dashboard 2022-11-19

hwy_data/NY/usany/ny.ny006n.wpt, hwy_data/NY/usany/ny.ny118.wpt
https://forum.travelmapping.net/index.php?topic=5297
=> topic 5297

hwy_data/PA/usapa/pa.pa029pho.wpt, hwy_data/PA/usapa/pa.pa443.wpt, hwy_data/PA/usapa/pa.pa902.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5270.0
Also removed unused alternate label on PA 29 (Phoenixville)
=> PA 443 at PA 902

hwy_data/NV/usasf/nv.cr215.wpt, hwy_data/NV/usaus/nv.us093.wpt
Per forum discussion.
No Updates table entry needed. Datacheck successful.
=> NV: new or relabeled exits on CR215 beltway, fix broken I-15/US93 concurrence

hwy_data/QC/cantch/qc.tchmai.wpt
=> Broken concurrency fix for PR #6192

hwy_data/GA/usaga/ga.ga025.wpt, hwy_data/GA/usaga/ga.ga057.wpt, hwy_data/GA/usaga/ga.ga219.wpt, hwy_data/GA/usaga/ga.ga540.wpt, hwy_data/GA/usaus/ga.us017.wpt
=> GA updates

hwy_data/PA/usaus/pa.us030.wpt
https://forum.travelmapping.net/index.php?topic=5324.msg30006#msg30006
=> US 30:  Fixing LinWayMcC Labels

hwy_data/ON/canon/on.on066.wpt
See: https://forum.travelmapping.net/index.php?topic=5324.msg30033#msg30033
=> on.on066: Minor label fix

hwy_data/CA/usaca/ca.ca001.wpt
Resynchs CA 1 to US 101, at 101's exits 113 and 116.
=> CA broken concurrence fix

hwy_data/PA/usapa/pa.pa192.wpt
Added as a new access to Penn's Cave Wildlife Park.
=> PA 192: Added Sara Campbell Ln (SaraCamLn).

updates.csv
@mapmikey  (https://forum.travelmapping.net/index.php?topic=5350.msg30345#msg30345)
=> Fixed I-840 (NC) Updates Entry

hwy_data/ON/cannf/on.donvalpkwy.wpt, hwy_data/ON/cannf/on.ecrowexpy.wpt, hwy_data/ON/cannf/on.redhillpkwy.wpt, hwy_data/ON/cannf/on.rr174.wpt, hwy_data/ON/canonf/on.on403.wpt, hwy_data/ON/canonf/on.ondvp.wpt
https://forum.travelmapping.net/index.php?topic=30.msg30321#msg30321
https://forum.travelmapping.net/index.php?topic=30.msg30330#msg30330
https://forum.travelmapping.net/index.php?topic=30.msg30409#msg30409
=> cannf: Ontario tweaks

hwy_data/CA/usaus/ca.us101.wpt
Datacheck pending -- hope it'll work this time.
=> CA-101-tweak

hwy_data/WV/usai/wv.i070.wpt
@mapcat wanted to update the location of this.  He'll be submitting the OH part later.
=> WV: I-70, updated OH border point

hwy_data/ROU/eure/rou.e581.wpt, hwy_data/ROU/roudj/rou.dj252h.wpt, hwy_data/ROU/roudn/rou.dn024.wpt, hwy_data/ROU/roudn/rou.dn025.wpt, hwy_data/ROU/roudn/rou.dnvo24f.wpt, hwy_data/_systems/roudn.csv, hwy_data/_systems/roudn_con.csv, updates.csv
=> Tecuci Bypass opening

hwy_data/BC/cannf/bc.golearsway.wpt, hwy_data/BC/cannf/bc.knist.wpt, hwy_data/NV/usai/nv.i015.wpt, hwy_data/NV/usai/nv.i080.wpt, hwy_data/NV/usaus/nv.us006.wpt, hwy_data/NV/usaus/nv.us093.wpt, hwy_data/NV/usaus/nv.us095.wpt, hwy_data/QC/canqc/qc.qc172.wpt, hwy_data/SK/cannf/sk.ringrd.wpt, hwy_data/SK/cansk/sk.sk006.wpt
=> cannf and NV changes

hwy_data/TX/usai/tx.i410.wpt, hwy_data/_systems/usaib.csv
https://forum.travelmapping.net/index.php?topic=5389.msg30583#msg30583
also, I-40BSGle unused
=> I-410: restore exit 27 to primary

updates.csv
See: https://github.com/TravelMapping/HighwayData/pull/6393#issuecomment-1426954087
=> MN: delete route links

hwy_data/ROU/roudj/rou.dj222.wpt, hwy_data/ROU/roudj/rou.dj229n.wpt, hwy_data/_systems/roudj.csv, hwy_data/_systems/roudj_con.csv, updates.csv
=> New route ROU DJ229N

hwy_data/MA/usama/ma.ma008acha.wpt, hwy_data/MA/usama/ma.ma010.wpt, hwy_data/MA/usama/ma.ma066.wpt
https://forum.travelmapping.net/index.php?topic=5407
https://forum.travelmapping.net/index.php?topic=5408
=> MA 8A, 10, 66 point requests

hwy_data/MS/usams/ms.ms007.wpt, hwy_data/MS/usams/ms.ms009w.wpt, hwy_data/MS/usams/ms.ms015dib.wpt, hwy_data/MS/usams/ms.ms032sceeni.wpt, hwy_data/MS/usams/ms.ms050.wpt, hwy_data/MS/usams/ms.ms198luc.wpt, hwy_data/MS/usams/ms.ms310.wpt, hwy_data/MS/usams/ms.ms310law.wpt, hwy_data/MS/usams/ms.ms315scesar.wpt, hwy_data/MS/usams/ms.ms514.wpt, hwy_data/MS/usams/ms.ms818.wpt, hwy_data/MS/usaus/ms.us051.wpt, hwy_data/_systems/usams.csv, hwy_data/_systems/usams_con.csv
A smattering of MS corrections and requests
=> MS corrections/requests

hwy_data/DE/usade/de.de024.wpt, hwy_data/DE/usade/de.de026.wpt, hwy_data/DE/usade/de.de030.wpt, hwy_data/DE/usade/de.de054.wpt, hwy_data/DE/usaus/de.us013.wpt, updates.csv
Meant to do DE branch, but it was easier to stay in the PA Branch once I made the mistake.
This is what happens when I do this during the Daytona 500.
https://forum.travelmapping.net/index.php?topic=4672.0
=> DE 30 Truncation

hwy_data/FL/usausb/fl.us027altper.wpt
https://forum.travelmapping.net/index.php?topic=5421.0
=> fl.us027altper: CR339 intersection relocation

hwy_data/DE/usade/de.de001.wpt, hwy_data/DE/usade/de.de030.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5048.msg30833#msg30833
Also removed unused alternate labels on DE 30.
=> DE 1 Extension to DE 4

hwy_data/NY/usany/ny.ny067.wpt
https://forum.travelmapping.net/index.php?topic=5362
=> NY NY67 CR59

hwy_data/MS/usaus/ms.us049.wpt, hwy_data/MS/usaus/ms.us051.wpt
Clearing out (new) remaining unused alt labels.
=> MS unused alt labels

hwy_data/GA/usaga/ga.ga001.wpt, hwy_data/GA/usaga/ga.ga005.wpt, hwy_data/GA/usaga/ga.ga008.wpt, hwy_data/GA/usaga/ga.ga016.wpt, hwy_data/GA/usaga/ga.ga017.wpt, hwy_data/GA/usaga/ga.ga021.wpt, hwy_data/GA/usaga/ga.ga026.wpt, hwy_data/GA/usaga/ga.ga154.wpt, hwy_data/GA/usaus/ga.us001.wpt, hwy_data/GA/usaus/ga.us023.wpt, hwy_data/GA/usaus/ga.us027.wpt, hwy_data/GA/usaus/ga.us041.wpt, hwy_data/GA/usaus/ga.us078.wpt, hwy_data/GA/usaus/ga.us082.wpt, hwy_data/GA/usaus/ga.us084.wpt
Unused Alt label cleanup for GA
=> Unused Alt label cleanup for GA

hwy_data/ROU/roudj/rou.dj222c.wpt, hwy_data/ROU/roudj/rou.dj229l.wpt, hwy_data/ROU/roudj/rou.dj229m.wpt, hwy_data/_systems/roudj.csv, hwy_data/_systems/roudj_con.csv, updates.csv
=> ROU DJ229L and 229M introduced

hwy_data/TX/usai/tx.i035e.wpt, hwy_data/TX/usatx/tx.tx276busqui.wpt, hwy_data/TX/usaus/tx.us067.wpt, hwy_data/TX/usaus/tx.us077.wpt, updates.csv
The Southern Gateway Project closed a few exits & renumbered a few existing ones. While in here, I'm taking the opportunity to unfudge a few fudged exit number labels.
ping @atsiatas: 
You'll want to change `TX I-35E 428C 467` to `TX I-35E 428B 467`.
ping @richiekennedy56:
You'll want to change `TX I-35E 428C 429D` to `TX I-35E 428B 429D`.
=> Southern Gateway

hwy_data/CT/usact/ct.ct009.wpt, hwy_data/CT/usact/ct.ct017.wpt, hwy_data/CT/usact/ct.ct154.wpt, hwy_data/CT/usact/ct.ct372.wpt, updates.csv
29 22 21 19 15 7 5
bobcobb cebarb98 dave1693 dharwood foresthills93 golubcar johninkingwood jpinyan justjake jwood lkefct lowenbrau M3200 mariethefoxy mikeandkristie mr_matt_k njroadhorse nrm1221 scott_stieglitz skatcher w9tam
dave1693 golubcar mr_matt_k njroadhorse w9tam
@dave1693 @dgolub @mr-matt-k @njroadhorse @tamesser 
bobcobb cebarb98 dharwood foresthills93 johninkingwood jpinyan justjake jwood lkefct lowenbrau M3200 mariethefoxy mikeandkristie nrm1221 scott_stieglitz skatcher
=> CT9 exit renumbering

hwy_data/FL/usaus/fl.us001.wpt
https://forum.travelmapping.net/index.php?topic=5434.0
=> fl.us001: Add WesBlvd

hwy_data/FL/usafl/fl.fl922.wpt, hwy_data/FL/usai/fl.i004.wpt
https://forum.travelmapping.net/index.php?topic=5264.msg30963#msg30963
=> fl.i004: 101C is now 101D

hwy_data/AR/usaar/ar.ar980cli.wpt
https://forum.travelmapping.net/index.php?topic=5458
=> AR980Cli south end

hwy_data/ROU/roudj/rou.dj291c.wpt, hwy_data/ROU/roudj/rou.dj291d.wpt, hwy_data/ROU/roudj/rou.dj291e.wpt, hwy_data/ROU/roudj/rou.dj291f.wpt, hwy_data/_systems/roudj.csv, hwy_data/_systems/roudj_con.csv, updates.csv
=> ROU DJ291E & DJ291F

hwy_data/TX/usai/tx.i010.wpt, hwy_data/TX/usatxf3/tx.fm1409.wpt, hwy_data/TX/usatxf3/tx.fm1409cov.wpt, hwy_data/_systems/usatxf3.csv, hwy_data/_systems/usatxf3_con.csv
https://m.facebook.com/story.php?story_fbid=443074411202348&id=100064993774399
=> FM1409 bridge

hwy_data/NY/usany/ny.ny331.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5472
=> NY331 truncated to Montgomery/Fulton line

hwy_data/PA/usapa/pa.pa837.wpt, hwy_data/PA/usapa/pa.pa837trkdon.wpt, hwy_data/_systems/usapa.csv, hwy_data/_systems/usapa_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=5476.0
=> Adding PA 837 TRUCK (Donora)

hwy_data/TUR/asiah/tur.ah086.wpt, hwy_data/TUR/eure/tur.e97.wpt, hwy_data/TUR/turd/tur.d885.wpt, updates.csv
=> TUR: D885/E97/AH86 Zigana Tunnel opening

hwy_data/ROU/roudn/rou.dn021.wpt, updates.csv
=> Relocation ROU DN21, Drajna Overpass opened

hwy_data/WV/usaus/wv.us048.wpt, hwy_data/WV/usaus/wv.us050.wpt, hwy_data/WV/usaus/wv.us052.wpt, hwy_data/WV/usaus/wv.us119.wpt, hwy_data/WV/usawv/wv.wv008.wpt
https://forum.travelmapping.net/index.php?topic=4908.0
https://forum.travelmapping.net/index.php?topic=5534.0
=> usawv: minor changes

hwy_data/WV/usaus/wv.us019.wpt, hwy_data/WV/usaus/wv.us460.wpt, hwy_data/WV/usawv/wv.wv004.wpt, hwy_data/WV/usawv/wv.wv041.wpt, hwy_data/WV/usawv/wv.wv270.wpt
https://forum.travelmapping.net/index.php?topic=4908.0
=> usawv: minor fixes

hwy_data/ROU/eure/rou.e87.wpt, hwy_data/ROU/roudj/rou.dj221b.wpt, hwy_data/ROU/roudn/rou.dn022.wpt, hwy_data/ROU/roudn/rou.dn22b.wpt, hwy_data/ROU/roudn/rou.dn22j.wpt, hwy_data/ROU/roudn/rou.dn22s.wpt, hwy_data/_systems/roudn.csv, hwy_data/_systems/roudn_con.csv, updates.csv
=> opening Braila Danube bridge

hwy_data/WV/usaus/wv.us250.wpt, hwy_data/WV/usausb/wv.us250trkmou.wpt, hwy_data/WV/usawv/wv.wv002.wpt, hwy_data/_systems/usausb.csv, hwy_data/_systems/usausb_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=5503.0
=> WV: Add US-250 Trk (Moundsville).

hwy_data/NV/usanv/nv.nv028.wpt, hwy_data/NV/usanv/nv.nv341.wpt, hwy_data/NV/usaus/nv.us050.wpt
Added waypoints at Lakeshore Blvd, Country Club Drive, Sand Harbor State Beach using local knowledge
=> Added waypoints

hwy_data/ROU/roudj/rou.dj102g.wpt, hwy_data/ROU/roudj/rou.dj103d.wpt, hwy_data/ROU/roudj/rou.dj104a.wpt, hwy_data/ROU/roudj/rou.dj105b.wpt, hwy_data/_systems/roudj.csv, hwy_data/_systems/roudj_con.csv, updates.csv
=> DJ102G and DJ102D extension

hwy_data/DE/usai/de.i095.wpt
https://forum.travelmapping.net/index.php?topic=5732.msg32233#msg32233
=> I-95:  Replaced +X1 with Biden Welcome Center (BidWelCen)

hwy_data/HUN/hunf/hun.f025.wpt, hwy_data/HUN/hunf/hun.f252.wpt, hwy_data/ROU/eure/rou.e60.wpt, hwy_data/ROU/eure/rou.e87.wpt, hwy_data/ROU/roua/rou.a004.wpt, hwy_data/ROU/roudn/rou.dn03c.wpt, hwy_data/_systems/hunf.csv, hwy_data/_systems/hunf_con.csv, updates.csv
=> Corrections HUN & ROU

hwy_data/PA/usapa/pa.pa228.wpt, hwy_data/PA/usaus/pa.us322.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5760.0
=> PA 228 Realignment

hwy_data/TX/usai/tx.i010.wpt, hwy_data/TX/usai/tx.i014.wpt, hwy_data/TX/usatxf4/tx.fm1670.wpt, hwy_data/TX/usaus/tx.us087.wpt, hwy_data/TX/usaus/tx.us190.wpt
https://forum.travelmapping.net/index.php?topic=2703
=> I-14 exit numbers & TX I-10 548

hwy_data/FL/usafl/fl.fl085.wpt, hwy_data/FL/usafl/fl.fl123.wpt
Fixed a missing graph connection at the southern junction between FL-85 & FL-123.
=> usafl: fix graph connection issue with FL-85/123.

hwy_data/TX/usai/tx.i110.wpt, hwy_data/TX/usaus/tx.us054elp.wpt, hwy_data/TX/usaus/tx.us059.wpt
https://forum.travelmapping.net/index.php?topic=5550
https://forum.travelmapping.net/index.php?topic=5559
https://forum.travelmapping.net/index.php?topic=5600
=> I-110 & US54, El Paso

hwy_data/AR/usaar/ar.ar980cor.wpt, hwy_data/AR/usaar/ar.ar980rec.wpt, hwy_data/AR/usaus/ar.us412.wpt, hwy_data/AR/usausb/ar.us067buswal.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5179
https://forum.travelmapping.net/index.php?topic=5536
https://forum.travelmapping.net/index.php?topic=5590
=> AR980, US67BusWal

hwy_data/PA/usapa/pa.pa074.wpt, hwy_data/PA/usapa/pa.pa641.wpt
Signed as way to get to I-81 SB from PA 641 and I-81 NB from PA 74.
=> PA 74 and PA 641:  Added Connector Rd (ConRd).

hwy_data/TX/usaus/tx.us281.wpt
https://forum.travelmapping.net/index.php?topic=5603
=> TX US281 Stone Oak area interchanges

hwy_data/WV/usaus/wv.us048.wpt, hwy_data/WV/usawv/wv.wv093.wpt
https://forum.travelmapping.net/index.php?topic=5782.0
=> WV: Fix mutliplex of US-48/WV-93

hwy_data/NY/usany/ny.ny029a.wpt, hwy_data/NY/usany/ny.ny309.wpt, hwy_data/NY/usany/ny.ny418.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5601
=> NY 418, 309 endpoints

hwy_data/AR/usaar/ar.ar035.wpt, hwy_data/AR/usaar/ar.ar146s.wpt, hwy_data/AR/usaar/ar.ar267.wpt, hwy_data/AR/usaus/ar.us079.wpt, hwy_data/AR/usausb/ar.us067bussea.wpt
https://forum.travelmapping.net/index.php?topic=5605
=> topic 5605

hwy_data/NB/cannbl/nb.nb555.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5607
=> NB555 ext W

hwy_data/AR/usaar/ar.ar017.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5610
=> AR17 trunc S

hwy_data/NY/usany/ny.ny039.wpt, hwy_data/NY/usany/ny.ny063.wpt, hwy_data/NY/usany/ny.ny247.wpt, hwy_data/NY/usany/ny.ny364.wpt, hwy_data/NY/usausb/ny.us020altgen.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5650
https://forum.travelmapping.net/index.php?topic=5654
=> NY forum stuff

hwy_data/TX/usatxs/tx.sp0342.wpt
https://forum.travelmapping.net/index.php?topic=5653
=> TXSpr342 SteRd

hwy_data/TX/usai/tx.i045.wpt
https://forum.travelmapping.net/index.php?topic=5602.msg32592#msg32592
=> TX I-45 exit 283

hwy_data/NY/usany/ny.ny173.wpt, hwy_data/NY/usany/ny.ny370.wpt
https://forum.travelmapping.net/index.php?topic=5652
=> NY 173 & 370 points

hwy_data/CZE/czed/cze.d007lou.wpt, hwy_data/CZE/czei/cze.i007lou.wpt, hwy_data/CZE/czeii/cze.ii229.wpt, hwy_data/_systems/czed.csv, hwy_data/_systems/czed_con.csv, updates.csv
https://www.skyscrapercity.com/threads/1464920/post-185367996
Keeping I7 on concurrency since it is just an upgrade on same alignment and the next section to the east will be opened by end of the year, i.e. it makes no sense to split the I7 route and create a new one for just 3 months including breaking list files.
=> CZE D7 Louny opened

hwy_data/NY/usany/ny.ny016.wpt, hwy_data/NY/usany/ny.ny039.wpt, hwy_data/NY/usany/ny.ny277.wpt
https://forum.travelmapping.net/index.php?topic=5656
=> NY16,  39 & 277 points

hwy_data/ON/canon/on.on003win.wpt, hwy_data/WV/usaus/wv.us219.wpt
Updated it's location after [mapmikey](https://forum.travelmapping.net/index.php?action=profile;u=5) agreed to the new location.
https://forum.travelmapping.net/index.php?topic=5616.0
+ minor ON-3 label fix.
=> WV: US-219 border w/ VA

hwy_data/NE/usane/ne.ne035.wpt, hwy_data/NE/usaus/ne.us081.wpt, hwy_data/OK/usaok/ok.ok007.wpt, hwy_data/OK/usaus/ok.us081.wpt, updates.csv
Added `IndHwy` points to US81 & NE35 per https://forum.travelmapping.net/index.php?topic=5764
**NE35 relocation:**
Removed from the NE 35 Frontage Road and relocated northwestward onto a parallel 4-lane divided highway between waypoints *OldNE35_S & *OldNE35_N to reflect a circa 2012-2014 realignment.
This may or may not affect @ntallyn & @mbeller2016, depending on when they traveled NE35.
=> US81 & pals / NE35 & OK7 relocations

hwy_data/CT/usact/ct.ct066.wpt, hwy_data/CT/usai/ct.i691.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5498
=> CT I-691 renumbering

hwy_data/NY/usai/ny.i088.wpt, hwy_data/NY/usany/ny.ny007.wpt, hwy_data/NY/usany/ny.ny014a.wpt, hwy_data/NY/usany/ny.ny054.wpt
https://forum.travelmapping.net/index.php?topic=5632.msg32547#msg32547
https://forum.travelmapping.net/index.php?topic=5803
=> NY 7 & 54, I-88

hwy_data/AR/usaar/ar.ar005lit.wpt, hwy_data/AR/usaar/ar.ar007.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5809
=> AR5Lit Hot Springs Bypass

hwy_data/NY/usai/ny.i081.wpt, hwy_data/NY/usai/ny.i678.wpt, hwy_data/NY/usany/ny.ny005s.wpt, hwy_data/NY/usany/ny.ny041.wpt, hwy_data/NY/usaus/ny.us011.wpt
https://forum.travelmapping.net/index.php?topic=5802
https://forum.travelmapping.net/index.php?topic=5813
https://forum.travelmapping.net/index.php?topic=5814
=> NY forum bits

hwy_data/ROU/roua/rou.a003sup.wpt, hwy_data/ROU/roudn/rou.dn01h.wpt, hwy_data/_systems/roua.csv, hwy_data/_systems/roua_con.csv, updates.csv
=> ROU A3 Suplacu

updates.csv
https://github.com/TravelMapping/HighwayData/pull/6869
=> Fixing PA 401 ALT TRUCK Updates Entry Typo

hwy_data/NY/usanyp/ny.niascepkwynia.wpt, hwy_data/NY/usasf/ny.lasexpy.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=2701
=> LaSalle W end

hwy_data/ME/usame/me.me011.wpt, hwy_data/ME/usame/me.me100.wpt, hwy_data/ME/usame/me.me100awin.wpt, hwy_data/ME/usame/me.me104.wpt, hwy_data/ME/usame/me.me137.wpt, hwy_data/ME/usame/me.me137buswat.wpt, hwy_data/ME/usaus/me.us201.wpt, updates.csv
[AASHTO Spring 2023 Meeting](https://forum.travelmapping.net/index.php?topic=5770)
Along the way, removed a few over-dense extra points in the immediate area & fixed a couple of the more significant off-coord points.
I'm gonna run a quick siteupdate here on BiggaTomato and make sure the graph looks OK.
**Edit:** Looks OK.
=> US201 couplet -> 2-way

hwy_data/NE/usane/ne.ne092.wpt, hwy_data/NE/usane/ne.ne097.wpt, updates.csv
Ping @ovoss -- I believe this happened in 2022.
=> Tryon North

hwy_data/WV/usawv/wv.wv891.wpt
https://forum.travelmapping.net/index.php?topic=5842.0
=> wv.wv891: label fix

hwy_data/OK/usaus/ok.us270.wpt, updates.csv
[AASHTO SCOH USRN Fall 2020](https://forum.travelmapping.net/index.php?topic=4046)
Ping @mapcat @ovoss @TBKS1
=> Wister OK US270 realignment

hwy_data/PA/usapa/pa.pa014.wpt, hwy_data/PA/usaus/pa.us006.wpt
https://forum.travelmapping.net/index.php?topic=5844.0
=> US 6 and PA 14:  Added Porter Rd.

hwy_data/OK/usaus/ok.us069.wpt, hwy_data/OK/usaus/ok.us075.wpt
[10 SB](https://www.google.com/maps/@33.963164,-96.4167586,3a,75y,187.24h,84.74t/data=!3m9!1e1!3m7!1sMqJgom4YbCSXeIC-LOoikQ!2e0!7i16384!8i8192!9m2!1b1!2i41?entry=ttu)
[11A NB](https://www.google.com/maps/@33.9398748,-96.420576,3a,57y,44.54h,88.61t/data=!3m9!1e1!3m7!1suNsOTwbBxWriYey1yBEIpA!2e0!7i16384!8i8192!9m2!1b1!2i41?entry=ttu)
11B NB overhead as seen from [main](https://www.google.com/maps/@33.9437861,-96.4179376,3a,39.6y,39.81h,93.99t/data=!3m9!1e1!3m7!1sv3cZMyvJr75aIMtOqsK5JA!2e0!7i16384!8i8192!9m2!1b1!2i41?entry=ttu) & [frontage](https://www.google.com/maps/@33.9436047,-96.417758,3a,32.7y,1.2h,94.92t/data=!3m9!1e1!3m7!1sV8J4UxSeZkYFT3d7hiJ3dw!2e0!7i16384!8i8192!9m2!1b1!2i41?entry=ttu)
[11B NB gore](https://www.google.com/maps/@33.9456385,-96.4169375,3a,43y,340.37h,89.64t/data=!3m10 …
=> US69/75 Calera/Durant exit numbers

hwy_data/TX/usatx/tx.tx217.wpt, hwy_data/TX/usatxf3/tx.fm1427.wpt, hwy_data/TX/usatxf5/tx.fm2221.wpt, hwy_data/TX/usatxf6/tx.fm2521.wpt, hwy_data/TX/usatxl/tx.lp0048.wpt, hwy_data/TX/usaus/tx.us083.wpt, hwy_data/TX/usaus/tx.us087.wpt, hwy_data/TX/usausb/tx.us083busmca.wpt, hwy_data/_systems/usatxl.csv, hwy_data/_systems/usatxl_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=397.msg32818#msg32818
https://forum.travelmapping.net/index.php?topic=397.msg32845#msg32845
=> TXLp48 deletion / La Joya Bypass

hwy_data/NY/usany/ny.ny005s.wpt, hwy_data/NY/usany/ny.ny890.wpt
https://forum.travelmapping.net/index.php?topic=5804
=> NY890 cleanup

hwy_data/NY/usany/ny.ny282.wpt
https://forum.travelmapping.net/index.php?topic=5856
=> NY282 WRivRd ->ERivRd

hwy_data/ROU/roudj/rou.dj106d.wpt, hwy_data/ROU/roudj/rou.dj106e.wpt, updates.csv
@rmihailucian Thanks for the update. Data check was fine. However, I made some changes. PLEASE check [pointsinuse.log](https://travelmapping.net/logs/pointsinuse.log) next time!
=> ROU fixes for #6911

hwy_data/TUR/asiah/tur.ah087.wpt, hwy_data/TUR/eure/tur.e96.wpt, hwy_data/TUR/turd/tur.d300.wpt, hwy_data/TUR/turd/tur.d555sal.wpt, hwy_data/TUR/turd/tur.d585.wpt, hwy_data/TUR/turd/tur.d650.wpt, hwy_data/TUR/turd/tur.d825gok.wpt, hwy_data/_systems/turd.csv, hwy_data/_systems/turd_con.csv, updates.csv
=> Some TUR changes

hwy_data/WV/usaus/wv.us019.wpt, hwy_data/WV/usawv/wv.wv007.wpt
https://forum.travelmapping.net/index.php?topic=5903.0
=> WV: US19/WV7 Broken multiplex

hwy_data/JPN/jpne/jpn.e004.wpt, hwy_data/JPN/jpnh/jpn.n293.wpt, hwy_data/JPN/jpnh/jpn.n401.wpt, hwy_data/JPN/jpnh/jpn.n401hak.wpt, hwy_data/_systems/jpnh.csv, hwy_data/_systems/jpnh_con.csv
E4 new exit 8-2.
N401 opening of Hakase Tunnel. Old road is now N401Hak.
=> E4 and N401 recent changes

hwy_data/PA/usausb/pa.us030busdow.wpt
PennDOT - District 6 News: New Southbound Ship Road (Ship Road Couplet) to Open Tuesday in West Whiteland Township
https://www.penndot.pa.gov/RegionalOffices/district-6/pages/details.aspx?newsid=8823
=> US 30 BUS (Downingtown): Relocated ShipRd.

hwy_data/NE/usane/ne.ne036.wpt, hwy_data/NE/usane/ne.ne079.wpt, hwy_data/NE/usaus/ne.us030.wpt, hwy_data/NE/usaus/ne.us077.wpt, hwy_data/NE/usaus/ne.us275.wpt, hwy_data/NE/usausb/ne.us030busfre.wpt, hwy_data/NE/usausb/ne.us275busfre.wpt, hwy_data/OK/usai/ok.i044.wpt, hwy_data/_systems/usausb.csv, hwy_data/_systems/usausb_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=5926
> Waypoint US30 moved from 6th St to a divided 4-lane expressway about 1.5 miles north.
aaroads charliezeb dharwood flroads terminal_moraine
aaroads flroads terminal_moraine
@aaroads @flroads @mbeller2016 
charliezeb dharwood 
---
> Removed from the Lincoln Highway and relocated onto a divided 4-lane expressway 1.5-2 miles north between waypoints \*OldUS30_Nor and \*OldUS30_Fre.
**All travelers with affected .lists:**
25or6to4 aaroads barefoot_driver bhemphill brendan charliezeb dharwood DJCane flroads highplainstrvlr highway63 hoopitypoop Ib3kii iowahighways justjake mapcat navigator oscar …
=> NE: US 30/77 relocation, Fremont

hwy_data/NE/usausb/ne.us030busfre.wpt
https://github.com/TravelMapping/HighwayData/pull/6968#issuecomment-1806865017
=> NE US30BusFre: US77 +-> BroSt

hwy_data/FL/usai/fl.i095.wpt, hwy_data/FL/usaus/fl.us001.wpt, hwy_data/FL/usaus/fl.us041.wpt
https://forum.travelmapping.net/index.php?topic=4013.0
=> usafl: minor label updates

hwy_data/DE/usade/de.de001.wpt
https://www.aaroads.com/forum/index.php?topic=372.msg2885195#msg2885195
https://deldot.gov/projects/index.shtml?dc=details&projectNumber=T201612501
https://deldot.gov/public.ejs?command=PublicProjectPortalDocument&iDID=1597375&iProjectObjectID=49431
=> DE 1: Making New Rd Visible

hwy_data/WA/usausb/wa.us395futspo.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5915.0
=> Add newly opened North Spokane Corridor extension

hwy_data/ROU/eure/rou.e574.wpt, hwy_data/ROU/roudn/rou.dn073.wpt, hwy_data/ROU/roudn/rou.dn73e.wpt, hwy_data/_systems/roudn.csv, hwy_data/_systems/roudn_con.csv, updates.csv
=> ROU DN73 & DN73E

hwy_data/FL/usaus/fl.us001.wpt
https://forum.travelmapping.net/index.php?topic=5456.0
=> fl.us001: label updates

hwy_data/FL/usafl/fl.fl100.wpt, hwy_data/FL/usafl/fl.fl200fer.wpt, hwy_data/FL/usafl/fl.fla1afer.wpt, hwy_data/FL/usaus/fl.us017.wpt, hwy_data/FL/usaus/fl.us092.wpt, hwy_data/FL/usaus/fl.us441.wpt
https://forum.travelmapping.net/index.php?topic=5456.0
=> usafl: minor label fixes/additions

hwy_data/ON/canon/on.on017.wpt, hwy_data/ON/cantch/on.tchott.wpt
https://forum.travelmapping.net/index.php?topic=5935.0
=> ON: New exit number on ON-17

hwy_data/WV/usawv/wv.wv108.wpt, hwy_data/WV/usawv/wv.wv123.wpt, hwy_data/_systems/usawv.csv, hwy_data/_systems/usawv_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=5976.0
=> WV: Add newly opened WV-108.

hwy_data/WV/usawv/wv.wv002.wpt
https://forum.travelmapping.net/index.php?topic=4301.0
=> wv.wv002: Wellsburg Bridge now open

updates.csv
=> ROU fix for #7098

hwy_data/KY/usaky/ky.ky0044.wpt, hwy_data/KY/usaky/ky.ky2706.wpt, hwy_data/KY/usaus/ky.us031e.wpt, hwy_data/KY/usausb/ky.us031ebusmtw.wpt, hwy_data/OH/usaoh/oh.oh160.wpt, hwy_data/_systems/usausb.csv, hwy_data/_systems/usausb_con.csv, updates.csv
Business 31E Mt Washington is no more
=> KY: Delete ex-US31EX

hwy_data/ROU/eure/rou.e70.wpt, hwy_data/ROU/roua/rou.a000jil.wpt, hwy_data/ROU/roudn/rou.dn005.wpt, hwy_data/ROU/roudn/rou.dn006.wpt, hwy_data/_systems/roua.csv, hwy_data/_systems/roua_con.csv, updates.csv
=> ROU A0 new opening (between DN5 and DN6)

hwy_data/NV/usanv/nv.nv225.wpt, hwy_data/NV/usanv/nv.nv278.wpt
=> NV point additions to reduce visible distance

updates.csv
https://github.com/TravelMapping/HighwayData/pull/7137#pullrequestreview-1807509526
=> exit number correction for #7137

hwy_data/TX/usasf/tx.fbptollrd.wpt, hwy_data/TX/usatx/tx.tx021.wpt, hwy_data/TX/usatxf/tx.fm0110.wpt, hwy_data/TX/usatxf6/tx.fm2611.wpt, hwy_data/TX/usatxs/tx.sp0419.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=1808.msg33630#msg33630
https://www.kxan.com/traffic/hays-county-traffic/new-road-opens-in-east-san-marcos-providing-an-alternative-route-to-i-35/
=> TX extensions & truncations

hwy_data/CT/usact/ct.ct009.wpt, hwy_data/CT/usact/ct.ct025.wpt, hwy_data/CT/usact/ct.ct037.wpt, hwy_data/CT/usact/ct.ct045.wpt, hwy_data/CT/usact/ct.ct072.wpt, hwy_data/CT/usact/ct.ct182.wpt, hwy_data/CT/usact/ct.ct182a.wpt, hwy_data/CT/usact/ct.ct183.wpt, hwy_data/CT/usact/ct.ct184.wpt, hwy_data/CT/usact/ct.ct341.wpt, hwy_data/CT/usact/ct.ct372.wpt, hwy_data/CT/usaus/ct.us007.wpt
https://forum.travelmapping.net/index.php?topic=6040
=> CT: topic 6040

hwy_data/NY/usaif/ny.i086futbin.wpt, hwy_data/NY/usaif/ny.i086futmon.wpt, hwy_data/NY/usany/ny.ny017bin.wpt, hwy_data/NY/usasf/ny.crocoupkwy.wpt, hwy_data/NY/usasf/ny.harrivdr.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5981
https://forum.travelmapping.net/index.php?topic=5990
https://forum.travelmapping.net/index.php?topic=5991
=> NY forum items

hwy_data/AR/usaar/ar.ar338.wpt, hwy_data/AR/usai/ar.i040.wpt, hwy_data/AR/usaus/ar.us062.wpt, hwy_data/AR/usaus/ar.us063.wpt, hwy_data/AR/usaus/ar.us070.wpt, hwy_data/AR/usaus/ar.us079.wpt, hwy_data/AR/usaus/ar.us167.wpt
https://forum.travelmapping.net/index.php?topic=6005
https://forum.travelmapping.net/index.php?topic=6050
https://forum.travelmapping.net/index.php?topic=6051
=> AR forum-o-roonie

hwy_data/NC/usanc/nc.nc057.wpt
Reentering as it was inadvertently removed. (@mapmikey)
https://github.com/Markkos1992/HighwayData/commit/fdf25ff7934fdaf852950d60e3e36f70b1303f1a
https://forum.travelmapping.net/index.php?topic=6042.msg33770#msg33770
=> NC 57: Reentered US158_W

hwy_data/ON/canonf/on.onqew.wpt, hwy_data/ON/cansf/on.doupkwy.wpt, hwy_data/ON/cansf/on.hwy2a.wpt, hwy_data/ON/cansf/on.niktesblvd.wpt, hwy_data/_systems/cansf.csv, hwy_data/_systems/cansf_con.csv, updates.csv
See: https://forum.travelmapping.net/index.php?topic=30.msg33788#msg33788
=> ON: Add 3 new routes to cansf

updates.csv
@mapcat,  this should fix the links on the updates page.
=> Fixing Recent KY Updates Entries

hwy_data/OK/usaok/ok.ok009.wpt, hwy_data/OK/usaus/ok.us277.wpt
https://forum.travelmapping.net/index.php?topic=6063
=> broken US62 olap

hwy_data/TX/usatxl/tx.lp0335.wpt, hwy_data/TX/usaus/tx.us281.wpt, hwy_data/TX/usausb/tx.us281buspre.wpt, hwy_data/_systems/usatxl.csv, hwy_data/_systems/usausb.csv, hwy_data/_systems/usausb_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=6064
=> US281 Premont

hwy_data/PA/usaus/pa.us013.wpt
https://forum.travelmapping.net/index.php?topic=6077.0
=> US 13: Added Tennis Ave (TenAve)

hwy_data/FL/usafl/fl.fl417.wpt, hwy_data/FL/usafl/fl.fl429.wpt
https://forum.travelmapping.net/index.php?topic=5264.15
https://forum.travelmapping.net/index.php?topic=5685.0
No need for an update entry, as old numbers could be retained as alt labels.
=> FL: FL-417/429 exit number updates

hwy_data/FL/usafl/fl.fl080.wpt, hwy_data/FL/usaus/fl.us041.wpt, hwy_data/FL/usaus/fl.us098.wpt, hwy_data/FL/usaus/fl.us301.wpt, hwy_data/FL/usaus/fl.us441.wpt
https://forum.travelmapping.net/index.php?topic=5456.msg34048#msg34048
=> usafl: label updates/fixes

hwy_data/PA/usapa/pa.pa320.wpt, hwy_data/PA/usapa/pa.pa420alttrkpro.wpt, hwy_data/PA/usatr/pa.natrd.wpt, hwy_data/PA/usaus/pa.us040.wpt
https://forum.travelmapping.net/index.php?topic=6158.msg34226#msg34226
Also removed unused alternate labels on PA 320 and PA 420 ALT TRUCK (Prospect Park)
=> Fixing US 40 and National Road Broken Concurrency

hwy_data/ROU/roudn/rou.dn001.wpt, hwy_data/_systems/roudn_con.csv
=> ROU fixes for #7351

hwy_data/DE/usade/de.de404trkgeo.wpt, hwy_data/DE/usaus/de.us113.wpt, hwy_data/DE/usausb/de.us009trkgeo.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5982.0
=> US 9 TRUCK (Georgetown) Realignment

hwy_data/TX/usatx/tx.tx094.wpt, hwy_data/TX/usatx/tx.txosr.wpt, hwy_data/TX/usatxl/tx.lp0266.wpt, hwy_data/TX/usatxs/tx.sp0278.wpt, hwy_data/TX/usausb/tx.us059busluf.wpt, hwy_data/TX/usausb/tx.us380trkden.wpt, hwy_data/_systems/usatxl.csv, hwy_data/_systems/usatxl_con.csv, hwy_data/_systems/usausb.csv, hwy_data/_systems/usausb_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=6146
https://forum.travelmapping.net/index.php?topic=6219
https://forum.travelmapping.net/index.php?topic=6232
=> TX forum items

hwy_data/MEX-TAM/mexd/mextam.mex097d.wpt, hwy_data/MEX-TAM/mexf/mextam.mex002.wpt, hwy_data/MEX-TAM/mexf/mextam.mex002rey.wpt, hwy_data/_systems/mexd.csv, hwy_data/_systems/mexd_con.csv, updates.csv
=> Mexico (Reynosa area bypasses)

hwy_data/MN/usamn/mn.mn015.wpt, hwy_data/MN/usamn/mn.mn044.wpt, hwy_data/MN/usamn/mn.mn044buscal.wpt, hwy_data/MN/usamn/mn.mn076.wpt, hwy_data/MN/usaus/mn.us014.wpt, hwy_data/_systems/usamn.csv, hwy_data/_systems/usamn_con.csv, updates.csv
Relocated US 14 onto the new Courtland bypass and added BUS MN 44 Caledonia.
=> MN:  US 14 and BUS MN 44 Caledonia

hwy_data/NE/usane/ne.ne074.wpt, hwy_data/NE/usane/ne.ne091.wpt, hwy_data/NE/usanes/ne.l01e.wpt, hwy_data/NE/usaus/ne.us077.wpt, hwy_data/NE/usaus/ne.us275.wpt, hwy_data/NE/usaus/ne.us281.wpt, hwy_data/_systems/usanes.csv, hwy_data/_systems/usanes_con.csv, updates.csv
=> L1E removal & Scribner bypass

updates.csv
Fixes missing route links in #7461.
@yakra
=> NE route links

hwy_data/MA/usama/ma.ma079.wpt, hwy_data/MA/usama/ma.ma138.wpt, hwy_data/MA/usaus/ma.us006.wpt, hwy_data/NH/usanh/nh.nh016.wpt, hwy_data/NH/usanh/nh.nh028.wpt, updates.csv
https://www.dot.nh.gov/projects-plans-and-programs/project-center/dummer-cambridge-errol-16304
=> NH & MA relocations

hwy_data/PA/usapa/pa.pa424.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5924.0
=> PA 424: Extended slightly further west to Mount Pleasant Ln (MouPleLn)

hwy_data/PA/usapa/pa.pa018.wpt
https://forum.travelmapping.net/index.php?topic=6307.0
=> PA 18: Added Peach St

hwy_data/PA/usapa/pa.pa059.wpt, hwy_data/PA/usapa/pa.pa077.wpt
PA 59:  Replaced +X3 with Big Bend Overlook (BigBendOve).  Added Bradford Regional Airport (BraRegAir).
PA 77:  NewRicRd>-NorRicRd.  JohnBroRd>-NewRicRd.
=> PA 59 and PA 77 Point Revisions

hwy_data/KS/usaks/ks.ks254.wpt, hwy_data/KS/usaks/ks.ks254trkeld.wpt, hwy_data/KS/usaus/ks.us054.wpt, hwy_data/KS/usaus/ks.us077.wpt, hwy_data/KS/usausb/ks.us054trkeld.wpt, hwy_data/KS/usausb/ks.us077trkeld.wpt, hwy_data/_systems/usaks.csv, hwy_data/_systems/usaks_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=2260
=> Stupid Truck Routes, El Dorado KS Edition

hwy_data/NE/usane/ne.ne002lin.wpt
**82nd:**
https://1053thebone.com/2023/11/08/lincoln-south-beltway-update-82nd-street-opens-up/
http://www.huskeradio.com/2023/11/08/new-segments-open-for-lincoln-south-beltway/
https://dot.nebraska.gov/media/jtxajlnt/2023-bna-tia.pdf
**Jamaica:**
https://www.youtube.com/watch?v=fCOndbtigPo
=> NE2Lin Jamaica & 82nd interchanges

hwy_data/CHN-HE/chng/chnhe.g0121don.wpt, hwy_data/CHN-TJ/chng/chntj.g0121.wpt, hwy_data/_systems/chng_con.csv
=> Connect G0121

hwy_data/NY/usasf/ny.hutrivpkwy.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=6336
=> Hutch exit 2

hwy_data/FL/usafl/fl.fl072.wpt, hwy_data/FL/usafl/fl.fl758.wpt, hwy_data/FL/usafl/fl.fl780.wpt
https://forum.travelmapping.net/index.php?topic=6354.0
=> usafl: point requests

hwy_data/WV/usaus/wv.us033.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=6348.0
=> WV: US-33 Scott Miller Hill Bypass now open

hwy_data/FL/usafl/fl.fl228.wpt
https://github.com/TravelMapping/HighwayData/pull/7575#issuecomment-2244135527
=> fl.fl228: update label

hwy_data/TX/usai/tx.i035.wpt, hwy_data/TX/usatx/tx.tx288.wpt, hwy_data/TX/usatxl/tx.lp0335.wpt, hwy_data/TX/usaus/tx.us075.wpt, hwy_data/TX/usaus/tx.us079.wpt, hwy_data/TX/usaus/tx.us281.wpt
https://forum.travelmapping.net/index.php?topic=6361
=> TX288: topic 6361

hwy_data/ME/usai/me.i095.wpt, hwy_data/ME/usame/me.me009.wpt, hwy_data/ME/usame/me.me126.wpt
https://www.maineturnpike.com/News/Recent-News/New-Southbound-On-Ramp-on-Lewiston-Road-in-West-Ga.aspx
=> for all the people who love graph connections

hwy_data/PA/usapa/pa.pa258.wpt, hwy_data/PA/usapa/pa.pa518.wpt, hwy_data/PA/usaus/pa.us062.wpt
**US 62:** ConBlvd>-ConBlvd_W. SkyRd>-SkyDr.
**PA 258:** LibPlaRd>-PlaNLRd. SkyRd>-SkyDr.
**PA 518:** ThoAve_E>-ThoSt_E
=> US 62, PA 258, and PA 518 Minor Revisions

hwy_data/HUN/hunm/hun.m006.wpt, hwy_data/HUN/hunm/hun.m044.wpt, updates.csv
=> HUN M44 and M6

hwy_data/ROU/eure/rou.e81.wpt, hwy_data/ROU/roua/rou.a000jil.wpt, hwy_data/ROU/roua/rou.a002.wpt, updates.csv
ROU A0 opening between DN4 and A2
=> ROU A0 opening between DN4 and A2

hwy_data/_systems/roudn.csv, hwy_data/_systems/roudn_con.csv, updates.csv
=> DNCORA renamed to DNVO1Z

hwy_data/HUN/hunf/hun.f045.wpt, hwy_data/HUN/hunf/hun.f047.wpt, hwy_data/HUN/hunf/hun.f451.wpt, hwy_data/ROU/eure/rou.e87.wpt, hwy_data/ROU/roudj/rou.dj229.wpt, hwy_data/ROU/roudj/rou.dj229c.wpt, hwy_data/ROU/roudj/rou.dj687j.wpt, hwy_data/ROU/roudj/rou.dj692b.wpt, hwy_data/ROU/roudj/rou.dj708d.wpt, hwy_data/ROU/roudn/rou.dn006.wpt, hwy_data/ROU/roudn/rou.dn022.wpt, hwy_data/_systems/roudj.csv, hwy_data/_systems/roudj_con.csv, updates.csv
=> HUN F451, ROU DJ 692B and DJ229C

hwy_data/FL/usafl/fl.fl865.wpt
https://forum.travelmapping.net/index.php?topic=6363.0
=> fl.fl865: point request

hwy_data/WV/usaus/wv.us035.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=5978.0
=> WV: US-35 extension

hwy_data/ITA-SAR/itass2/itasar.ss134.wpt, hwy_data/ITA/itass/ita.ss134.wpt
=> ITA point request

hwy_data/PA/usapa/pa.pa251.wpt
Added Darlington Rd (DarRd_W) and Shenango Rd (SheRd_S).
=> PA 251: Added Points

hwy_data/AL/usaal/al.al158.wpt, hwy_data/AL/usaal/al.al217.wpt, hwy_data/AL/usaus/al.us098.wpt, updates.csv
List updates for the extension of AL 158 west to US 98.
=> AL 158 Extension

hwy_data/PA/usai/pa.i070.wpt, hwy_data/PA/usai/pa.i076.wpt, hwy_data/PA/usapa/pa.pa120.wpt, hwy_data/PA/usapa/pa.pa655.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=6400.0
=> I-70/I-76, PA 120, and PA 655 Point Revisions

hwy_data/WV/usaus/wv.us019.wpt, hwy_data/WV/usawv/wv.wv009.wpt
https://forum.travelmapping.net/index.php?topic=6400.msg35429#msg35429
=> WV: point requests

hwy_data/AL/usansf/al.al158.wpt
https://forum.travelmapping.net/index.php?topic=5410.0
This is fix #7647 fully, and allow the link on the 'update' page to properly show the updated route.
@ajfroggie
=> Sync AL-158 in usansf w/ version in usaal

hwy_data/PA/usapa/pa.pa018.wpt, hwy_data/PA/usapa/pa.pa066.wpt, hwy_data/PA/usapa/pa.pa168.wpt, hwy_data/PA/usapa/pa.pa551.wpt, hwy_data/PA/usaus/pa.us422.wpt, updates.csv
US 422: Realignment at Margaret Rd (https://forum.travelmapping.net/index.php?topic=6392.0)
PA 18/PA 168: Created short concurrency at intersection by West Pittsburg
PA 66: US119>-0  (https://forum.travelmapping.net/index.php?topic=6409.0)
PA 551: 37thSt>-37thStExt
=> PA Updates 8-26-2024

hwy_data/ROU/eure/rou.e60.wpt, hwy_data/ROU/roudn/rou.dn013.wpt
=> ROU DN13 new WP

updates.csv
@mapcat  https://forum.travelmapping.net/index.php?topic=6441.0
=> Fixing dates on LA Updates Entries

hwy_data/PA/usapa/pa.pa026.wpt
https://forum.travelmapping.net/index.php?topic=6448.0
=> PA 26: I-80(163)>-WaltRd

hwy_data/WV/usaus/wv.us019.wpt, hwy_data/WV/usawv/wv.wv041.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=6464.0
=> WV: WV-41 reroute in Beckley

hwy_data/WV/usaus/wv.us250.wpt, hwy_data/WV/usawv/wv.wv002.wpt
Just some minor cleanups that I wanted to get onto the site right away.
=> usawv minor cleanups

systems.csv
@rmihailucian data check successful 😄
=> itass back to preview

hwy_data/_systems/usausb.csv, hwy_data/_systems/usausb_con.csv
https://forum.travelmapping.net/index.php?topic=6143.0
=> usausb: Fix Sylvania, GA spelling

hwy_data/AB/canab/ab.ab201.wpt
https://skyscraperpage.com/forum/showthread.php?p=10265658#post10265658
=> AB AB201 57

hwy_data/PA/usapa/pa.pa041.wpt, hwy_data/PA/usapa/pa.pa926.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=6502.0
=> PA 41/PA 926 Roundabout Realignments

hwy_data/PA/usapa/pa.pa082alttrkeas.wpt, updates.csv
=> PA 82 ALT TRUCK: Fixing PA 41 Concurrency

hwy_data/TX/usatx/tx.tx255.wpt, hwy_data/TX/usatxf/tx.fm0255.wpt, hwy_data/TX/usausb/tx.us059busluf.wpt, hwy_data/_systems/usatxf.csv, hwy_data/_systems/usatxf_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=6517
=> TX255 trunc

hwy_data/AB/canab/ab.ab026.wpt, hwy_data/AB/canab/ab.ab056.wpt, hwy_data/AB/canabs/ab.ab834.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=6523
=> AB56 ext, AB834 trunc

hwy_data/AB/canab/ab.ab016.wpt, hwy_data/AB/canab/ab.ab216.wpt, hwy_data/AB/cantch/ab.tchyel.wpt
https://forum.travelmapping.net/index.php?topic=6536
https://forum.travelmapping.net/index.php?topic=6537
=> AB fixes from forum

hwy_data/WV/usai/wv.i077.wpt, hwy_data/WV/usaus/wv.us019.wpt, hwy_data/WV/usaus/wv.us052.wpt, hwy_data/WV/usaus/wv.us060.wpt, hwy_data/WV/usawv/wv.wv014.wpt, hwy_data/WV/usawv/wv.wv020.wpt, hwy_data/WV/usawv/wv.wv031.wpt
https://forum.travelmapping.net/index.php?topic=5882.0
=> WV: minor cleanups

hwy_data/AR/usaar/ar.ar009b.wpt, hwy_data/AR/usaar/ar.ar095.wpt, hwy_data/AR/usaar/ar.ar132.wpt, hwy_data/AR/usaar/ar.ar247mor.wpt, hwy_data/_systems/usaar.csv, hwy_data/_systems/usaar_con.csv, updates.csv
https://www.ardot.gov/wp-content/uploads/Admin-Circular-2024-10-Minutes-of-the-August-7-and-September-18-AHC-Meetings.pdf
Oct 2024 GMSV shows all signage removed.
=> AR132 deleted

hwy_data/WV/usaus/wv.us033.wpt, hwy_data/WV/usaus/wv.us119.wpt, hwy_data/WV/usaus/wv.us250.wpt
https://forum.travelmapping.net/index.php?topic=5882.0
=> usawv: minor cleanups

hwy_data/PA/usaus/pa.us022.wpt, hwy_data/WV/usaus/wv.us022.wpt
https://forum.travelmapping.net/index.php?topic=6576.0
=> WV/PA: Update WV/PA location on US-22

hwy_data/FL/usasf/fl.fltpk.wpt
Since you can legally U-Turn @ them.
https://forum.travelmapping.net/index.php?topic=6558.0
=> fl.fltpk: Add all 8 SP's.

hwy_data/NM/usanm/nm.nm460.wpt
=> Flip nm.nm460.wpt waypoint order

hwy_data/MN/usamn/mn.mn047.wpt, hwy_data/MN/usamn/mn.mn101.wpt, hwy_data/MN/usaus/mn.us010.wpt, hwy_data/MN/usaus/mn.us012.wpt, hwy_data/MN/usaus/mn.us169.wpt, updates.csv
US 12 Willmar realignment
US 10/169 new interchanges
MN 101 unused (and no longer existing intersection) point dropped
=> MN Updates

hwy_data/ROU/roudj/rou.dj108c.wpt, hwy_data/ROU/roudj/rou.dj763.wpt, updates.csv
=> ROU DJ763 extended

hwy_data/ROU/roudex/rou.dex12.wpt, hwy_data/ROU/roudj/rou.dj641.wpt, hwy_data/ROU/roudj/rou.dj643f.wpt, hwy_data/ROU/roudn/rou.dn65a.wpt, hwy_data/ROU/roudn/rou.dn65f.wpt, hwy_data/_systems/roudj.csv, hwy_data/_systems/roudj_con.csv, updates.csv
=> ROU DEX 12 new openings

hwy_data/ROU/eure/rou.e58.wpt, hwy_data/ROU/roudn/rou.dn017.wpt, hwy_data/ROU/roudn/rou.dn17d.wpt, hwy_data/ROU/roudn/rou.dn17f.wpt, hwy_data/_systems/roudn.csv, hwy_data/_systems/roudn_con.csv, updates.csv
=> ROU DN17F (Beclean bypass)

hwy_data/DE/usade/de.de001.wpt, hwy_data/DE/usade/de.de007.wpt, hwy_data/DE/usaus/de.us013.wpt
https://forum.travelmapping.net/index.php?topic=6604.0
=> Adding Points for US 13/DE 1 and DE 7

hwy_data/MA/usama/ma.ma286.wpt, hwy_data/NH/usanh/nh.nh028.wpt, hwy_data/NH/usanh/nh.nh286.wpt
[RocParkBlvd street sign](https://www.google.com/maps/@42.7693277,-71.2205949,3a,15y,219.54h,92.8t/data=!3m10!1e1!3m8!1svvxdwjprKtXNFby4CIHGFg!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D-2.801973316755422%26panoid%3DvvxdwjprKtXNFby4CIHGFg%26yaw%3D219.5443258074613!7i16384!8i8192!9m2!1b1!2i40?entry=ttu&g_ep=EgoyMDI0MTIwNC4wIKXMDSoASAFQAw%3D%3D)
[better angle](https://www.google.com/maps/@42.7694127,-71.2206579,3a,15y,178.53h,91.6t/data=!3m10!1e1!3m8!1skH19w3BFTQmBXIG-iReQsQ!2e0!6shttps:%2F%2Fstreetviewpixels-pa.googleapis.com%2Fv1%2Fthumbnail%3Fcb_client%3Dmaps_sv.tactile%26w%3D900%26h%3D600%26pitch%3D-1.600082036123581%26panoid%3DkH19w3BFTQmBXIG-iReQsQ%26yaw%3D178.5260290580322!7i16384!8i8192!9m2!1b1!2i4 …
=> Nampshachusetts

hwy_data/NH/usanh/nh.nh119.wpt, updates.csv
=> W end NH119

hwy_data/NY/usai/ny.i086owe.wpt, hwy_data/NY/usaif/ny.i086futbin.wpt, hwy_data/NY/usany/ny.ny026.wpt, hwy_data/NY/usany/ny.ny034.wpt, hwy_data/NY/usany/ny.ny096.wpt, hwy_data/NY/usany/ny.ny282.wpt, hwy_data/NY/usany/ny.ny434.wpt, hwy_data/NY/usaus/ny.us009.wpt, hwy_data/PA/usai/pa.i086swa.wpt, hwy_data/PA/usaif/pa.i086futswa.wpt, hwy_data/_systems/usai.csv, hwy_data/_systems/usai_con.csv, hwy_data/_systems/usaif.csv, hwy_data/_systems/usaif_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=6585
Ping @Markkos1992 @rickmastfan67 @cockroachking
@jteresco et al:
I *may* add more commits to this and bang out some forum items.
If not *(or if so!)*, I plan to leave this PR in a state that's ready to merge at any time.
If that changes, I'll comment or close the PR.
Let's assume we're Ready to Rock unless anyone says otherwise.
=> I-86 (Owego)

hwy_data/AB/canab/ab.ab002.wpt
https://forum.travelmapping.net/index.php?topic=6534
=> AB AB2 TR284

hwy_data/TX/usatxl/tx.lp0008.wpt
https://forum.travelmapping.net/index.php?topic=6586
=> TXLp8: topic 6586

hwy_data/NJ/usanj/nj.nj143.wpt
https://forum.travelmapping.net/index.php?topic=4325
Forgoing an updates entry here, as it's more or less a different representation of the same junction.
I'll use that as justification as writing the update text would be an awkward PitA otherwise. ;)
If there are strong objections, I'm open to suggestion.
=> NJ143 N end

hwy_data/NE/usane/ne.ne064.wpt
https://forum.travelmapping.net/index.php?topic=6556
=> NE NE64 300thSt

hwy_data/ROU/eure/rou.e85.wpt, hwy_data/ROU/roua/rou.a001.wpt, hwy_data/ROU/roua/rou.a007foc.wpt, hwy_data/ROU/roudj/rou.dj203k.wpt, hwy_data/ROU/roudj/rou.dj205p.wpt, hwy_data/ROU/roudj/rou.dj205r.wpt, hwy_data/ROU/roudn/rou.dn002.wpt, hwy_data/ROU/roudn/rou.dn022bra.wpt, hwy_data/ROU/roudn/rou.dn023.wpt, hwy_data/ROU/roudn/rou.dn02n.wpt, hwy_data/ROU/roudn/rou.dn07c.wpt, hwy_data/_systems/roua.csv, hwy_data/_systems/roua_con.csv, updates.csv
@michihdeu please perform datacheck on this one. The last segment of A7 opens today, between Ramnicu Sarat and Focsani Sud.
=> ROU A1 & A7 Buzau N - Focsani N openings

hwy_data/NS/cannsc/ns.ns213.wpt, hwy_data/NS/cannsf/ns.ns103.wpt, hwy_data/NS/cannsf/ns.ns104.wpt, hwy_data/NS/cannst/ns.ns004ngl.wpt, hwy_data/NS/cantch/ns.tchmai.wpt
https://www.facebook.com/groups/592859740828399/posts/8042901962490769/
https://atlantic.ctvnews.ca/new-interchange-in-bridgewater-n-s-expected-to-improve-traffic-flow-1.7153935
https://news.novascotia.ca/en/2024/12/20/new-bridgewater-interchange-open
=> NS: Exits 12A & 28

hwy_data/CHN-AH/chng/chnah.g36.wpt, hwy_data/CHN-FJ/chng/chnfj.g1523.wpt, hwy_data/CHN-FJ/chng/chnfj.g72.wpt, hwy_data/CHN-GD/chng/chngd.g2518.wpt, hwy_data/CHN-GD/chngd/chngd.s06.wpt, hwy_data/CHN-GD/chngd/chngd.s63.wpt, hwy_data/CHN-GX/chng/chngx.g65.wpt, hwy_data/CHN-GZ/chng/chngz.g56.wpt, hwy_data/CHN-HA/chng/chnha.g55.wpt, hwy_data/CHN-HA/chng/chnha.g5512.wpt, hwy_data/CHN-HE/chng/chnhe.g25.wpt, hwy_data/CHN-HE/chng/chnhe.g95.wpt, hwy_data/CHN-NM/asiah/chnnm.ah003.wpt, hwy_data/CHN-NM/asiah/chnnm.ah035sij.wpt, hwy_data/CHN-SD/chng/chnsd.g22.wpt, hwy_data/CHN-SX/chng/chnsx.g55.wpt, hwy_data/CHN-TJ/chng/chntj.g0111.wpt, hwy_data/CHN-XJ/asiah/chnxj.ah068.wpt, hwy_data/CHN-YN/chng/chnyn.g56.wpt, hwy_data/CHN-YN/chng/chnyn.g85.wpt
https://forum.travelmapping.net/index.php?topic=6561.0
=> CHN fixes for BORDER_LABEL

hwy_data/ROU/roua/rou.a003buc.wpt, hwy_data/ROU/roua/rou.a007miz.wpt, hwy_data/ROU/roudj/rou.dj100c.wpt, hwy_data/ROU/roudn/rou.dn01d.wpt, hwy_data/_systems/roua.csv, hwy_data/_systems/roua_con.csv, updates.csv
=> ROU A7 A3-Mizil

updates.csv
https://github.com/TravelMapping/DataProcessing/issues/62
=> I'm too stupid!

hwy_data/PA/usapa/pa.pa981.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=6185.0
=> PA 981: Realignments between PA819_S and WinHillDr (north of Mount Pleasant)

updates.csv
https://github.com/TravelMapping/DataProcessing/issues/62
=> fix broken roots in updates.csv

hwy_data/DEU-SN/deub/deusn.b172a.wpt, hwy_data/_systems/asiah.csv, hwy_data/_systems/asiah_con.csv, updates.csv
https://github.com/TravelMapping/DataProcessing/issues/62#issuecomment-2616739871
=> Invalid links

hwy_data/PA/usapa/pa.pa351.wpt, hwy_data/PA/usapa/pa.pa351trkell.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=6674.0
=> PA 351 TRUCK (Ellwood City): Making route westbound only west of 5th St due to no eastbound signs on PA 351.

updates.csv
See: https://forum.travelmapping.net/index.php?topic=6560.msg36912#msg36912
=> Correct file links

hwy_data/PRT/prtve/prt.ve003.wpt, hwy_data/PRT/prtve/prt.ve008.wpt, hwy_data/_systems/prtve.csv, hwy_data/_systems/prtve_con.csv, updates.csv
VE8 source: https://www.madeira.gov.pt/drestradas/Estrutura/DRE/ctl/Read/mid/10535/InformacaoId/14272/UnidadeOrganicaId/22
=> PRT Madeira

hwy_data/BC/cantch/bc.tchbuscha.wpt, hwy_data/BC/cantch/bc.tchmai.wpt
Two changes are in this pull request. Three others will be in separate pull requests.
=> Chase BC business route changes

hwy_data/_systems/usapa.csv, hwy_data/_systems/usapa_con.csv
I originally did Datacheck so I have no idea how I forgot the csv files.  #8203
=> PA 74 TRUCK (Ickesburg) Part 2

hwy_data/JPN/jpntk/jpn.he11.wpt
=> Japan HE11 fix - switch exit numbers

hwy_data/OK/usai/ok.i040.wpt, hwy_data/OK/usai/ok.i044.wpt, hwy_data/OK/usaok/ok.ok066.wpt, hwy_data/OK/usaok/ok.ok099.wpt, hwy_data/OK/usaok/ok.ok351.wpt, hwy_data/OK/usasf/ok.gilexpy.wpt, hwy_data/OK/usasf/ok.lltispkwy.wpt, hwy_data/OK/usaus/ok.us060.wpt, hwy_data/OK/usaus/ok.us070.wpt, hwy_data/OK/usaus/ok.us270.wpt, hwy_data/OK/usaush/ok.us066hisokl.wpt, updates.csv
[OK: annoying US60 & US70 relocations](https://forum.travelmapping.net/index.php?topic=4014)
[OK: L.L. Tisdale Parkway](https://forum.travelmapping.net/index.php?topic=6696)
[OK: I-40 updates](https://forum.travelmapping.net/index.php?topic=6763)
[OK: OK-351 exit number update](https://forum.travelmapping.net/index.php?topic=6762)
[OK: OK-66 point suggestion](https://forum.travelmapping.net/index.php?topic=6760)
=> OK forum items 2025-03-21

hwy_data/QC/canqca/qc.a085.wpt
Per forum discussion, of a waypoint in concurrent TCH Main that needed to be added to A-85 route file.
=> Fix missing point in qc.a085.wpt

hwy_data/ALB/alba/alb.a001.wpt, hwy_data/ALB/albsf/alb.unalin.wpt, hwy_data/ALB/albsh/alb.sh001tir.wpt, hwy_data/ALB/albsh/alb.sh002.wpt, hwy_data/ALB/albsh/alb.sh004.wpt, hwy_data/RKS/rksn/rks.n002.wpt, hwy_data/RKS/rksn/rks.n009.wpt, hwy_data/RKS/rksrr/rks.r128.wpt
https://forum.travelmapping.net/index.php?topic=6851 https://forum.travelmapping.net/index.php?topic=6853
=> Kosovo and Albania

hwy_data/FL/usafl/fl.fl559aub.wpt, hwy_data/FL/usafl/fl.fl570.wpt
https://forum.travelmapping.net/index.php?topic=6874.0
=> fl.fl570: New exit 20

hwy_data/PA/usapa/pa.pa051.wpt, hwy_data/PA/usaus/pa.us019.wpt
https://forum.travelmapping.net/index.php?topic=6892.0
Other changes:
PA 51: Also replaced +X1 with High Rd.
=> US 19/PA 51: Adding Wabash Street RIRO

hwy_data/LA/usala/la.la0001.wpt, hwy_data/LA/usala/la.la0022.wpt, hwy_data/LA/usala/la.la0031.wpt, hwy_data/LA/usala/la.la0040.wpt, hwy_data/LA/usala/la.la0044.wpt, hwy_data/LA/usala/la.la0113.wpt, hwy_data/LA/usala/la.la0328.wpt
Added points on LA 31 and LA 328.  Updated labels on other points.
=> LA Waypoints

hwy_data/KY/usakyp/ky.commtnpkwy.wpt, hwy_data/KY/usaus/ky.us460.wpt, hwy_data/OH/usaus/oh.us033.wpt, hwy_data/OH/usaus/oh.us035.wpt, hwy_data/TN/usai/tn.i055.wpt, hwy_data/TN/usatn/tn.tn109.wpt, hwy_data/TN/usaus/tn.us061.wpt, hwy_data/TN/usaus/tn.us064.wpt, hwy_data/TN/usaus/tn.us070.wpt, hwy_data/TN/usaus/tn.us078.wpt, hwy_data/TN/usaus/tn.us079.wpt
Also new alignment of I-55 exit 12 in Memphis
=> Points for new interchanges or things that sort of look like interchanges

hwy_data/LA/usaus/la.us084.wpt, hwy_data/LA/usaus/la.us090.wpt, hwy_data/LA/usaus/la.us167.wpt, hwy_data/LA/usausb/la.us090busnew.wpt
Removed from US and US auxiliary routes.
=> Removing Unused Alternate Waypoint Labels

hwy_data/LA/usala/la.la0010.wpt, hwy_data/LA/usala/la.la0417red.wpt, hwy_data/LA/usala/la.la3105.wpt, hwy_data/LA/usaus/la.us071.wpt, updates.csv
LA 10 end relocation
LA 3105 truncated to US 71
=> LA 10 end relocation and LA 3105 truncation

hwy_data/LA/usala/la.la0001.wpt, hwy_data/LA/usala/la.la0008.wpt, hwy_data/LA/usala/la.la0025.wpt, hwy_data/LA/usala/la.la0033.wpt, hwy_data/LA/usala/la.la0041.wpt, hwy_data/LA/usala/la.la0064.wpt, hwy_data/LA/usala/la.la0069.wpt, hwy_data/LA/usala/la.la0093.wpt, hwy_data/LA/usala/la.la0124.wpt, hwy_data/LA/usala/la.la0142.wpt, hwy_data/LA/usala/la.la0147.wpt, hwy_data/LA/usala/la.la0157.wpt, hwy_data/LA/usala/la.la0182.wpt, hwy_data/LA/usala/la.la0331.wpt, hwy_data/LA/usala/la.la0342.wpt, hwy_data/LA/usala/la.la0431.wpt, hwy_data/LA/usala/la.la0593.wpt, hwy_data/LA/usala/la.la0655.wpt, hwy_data/LA/usala/la.la0685.wpt, hwy_data/LA/usala/la.la0724.wpt, hwy_data/LA/usala/la.la0828.wpt, hwy_data/LA/usala/la.la0898.wpt, hwy_data/LA/usala/la.la0934.wpt, hwy_data/LA/usala/la.la0990.wpt, hwy_data/LA/usala/la.la1058.wpt, hwy_data/LA/usala/la.la1077.wpt, hwy_data/LA/usala/la.la1078.wpt, hwy_data/LA/usala/la.la3102.wpt, hwy_data/LA/usala/la.la3246.wpt
Also removed unused waypoint for defunct intersection on LA 8.
=> Removing Unused Deprecated Waypoint Labels

hwy_data/LA/usala/la.la0394.wpt, hwy_data/LA/usala/la.la0486.wpt, hwy_data/LA/usala/la.la0555.wpt, hwy_data/LA/usala/la.la0572.wpt, hwy_data/LA/usala/la.la0865nwi.wpt, hwy_data/LA/usala/la.la0906.wpt, hwy_data/LA/usala/la.la0961.wpt, hwy_data/LA/usala/la.la12081.wpt, hwy_data/LA/usatr/la.grrbat.wpt, hwy_data/LA/usaus/la.us065.wpt, hwy_data/LA/usaus/la.us071.wpt, hwy_data/LA/usaus/la.us080.wpt, hwy_data/LA/usaus/la.us090.wpt, hwy_data/LA/usausb/la.us165busale.wpt
Also corrected GRR after re-positioning points on US 61.
=> LA Waypoint Labels and Positions

hwy_data/WV/usawv/wv.wv083.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=7042.0
VA update already submitted via: https://github.com/TravelMapping/HighwayData/commit/8f2fcf885b203f0edcd5fec8d38e61dea174344f#diff-c5622afeb568fe255754255391882f60319b4d82b75e7105085b06311eaf7c6d
=> WV: WV-83 border point relocation

hwy_data/TX/usai/tx.i037.wpt, hwy_data/TX/usai/tx.i069.wpt, hwy_data/TX/usatx/tx.tx035.wpt, hwy_data/TX/usatx/tx.tx286.wpt, hwy_data/TX/usatxl/tx.lp0049.wpt, hwy_data/TX/usatxs/tx.sp0407.wpt, hwy_data/TX/usaus/tx.us059.wpt, hwy_data/TX/usaus/tx.us069.wpt, hwy_data/TX/usaus/tx.us087.wpt, hwy_data/TX/usaus/tx.us175.wpt, hwy_data/TX/usaus/tx.us181.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=7035
=> Harbor Bridge

updates.csv
This happens to fix the entry dates for #8470 so they show up properly on the update log.
@yakra
=> TX: Fix dates on entries

hwy_data/ROU/eure/rou.e85.wpt, hwy_data/ROU/eure/rou.e87gal.wpt, hwy_data/ROU/roua/rou.a000.wpt, hwy_data/ROU/roudn/rou.dn002.wpt, hwy_data/ROU/roudn/rou.dn022.wpt, hwy_data/ROU/roudn/rou.dn02b.wpt, hwy_data/ROU/roudn/rou.dn02s.wpt, updates.csv
=> ROU A0 north and DN2S

hwy_data/MO/usaus/mo.us071.wpt
https://forum.travelmapping.net/index.php?topic=7077.0
=> US 71: Major Fix

hwy_data/FL/usai/fl.i004.wpt
https://forum.travelmapping.net/index.php?topic=7101.0
=> fl.i004: New exit 70

hwy_data/ROU/eure/rou.e81.wpt, hwy_data/ROU/roua/rou.a001.wpt, hwy_data/ROU/roudex/rou.dex12.wpt, updates.csv
=> DEX12 new opening

hwy_data/FL/usafl/fl.fl044.wpt, hwy_data/FL/usafl/fl.fl589.wpt, updates.csv
https://forum.travelmapping.net/index.php?topic=7163.0
=> FL: FL-589 extension

hwy_data/OH/usaoh/oh.oh018.wpt, hwy_data/OH/usaus/oh.us020.wpt
Add points for historic route's endpoints to US 20 & OH 18
=> OH: Fix problems with US20HisBel

hwy_data/DE/usade/de.de020.wpt, hwy_data/DE/usade/de.de024.wpt, hwy_data/DE/usade/de.de024busmil.wpt, hwy_data/DE/usade/de.de030.wpt, hwy_data/DE/usaus/de.us113.wpt, hwy_data/_systems/usade.csv, hwy_data/_systems/usade_con.csv, updates.csv
https://forum.travelmapping.net/index.php?topic=6699.0
=> North Millsboro Bypass Changes

updates.csv
=> DE 24, DE 24 BUS (Millsboro), and DE 30 Updates Entries

hwy_data/RI/usari/ri.ri177.wpt
Adding a point to Rhode Island state route 177.
=> RI177 point addition

hwy_data/RI/usari/ri.ri126.wpt
Added two points to Rhode Island state route 126.
=> RI126 Point Addition

hwy_data/CT/usact/ct.ct234.wpt
Added a point to Connecticut state route 234.
=> Connecticut route 234 point addition
